### ISSUE TITLE
[CAMERA][BETA] Problème avec le widget (icone refresh) 

### ISSUE THREAD

**Issue by philippeMo** [jeedom/issues#1]
après installation beta du 02/06/2016 9:42
je constate le problème suivant:
des icônes de rafraîchissement apparaissent une fraction de seconde sur des widgets qui n'en ont pas habituellement comme par ex les sondes rfxcom.
cela rend le dashboard instable.
par d'erreur constatée sur la console

**Comment by zoic21** [comment]
Bonjour,
Si tu créer un objet avec seulement une caméra et une sonde rfxcom et que tu n'affiches que cette objet le probleme existe t-il ?

**Comment by philippeMo** [comment]
Salut loic , content de te revoir.
je viens de faire le test et non apparament le problème ne se produit pas dans ce cas la.

**Comment by zoic21** [comment]
Dans ce cas le soucis ne vient pas du plugin caméra je ferme donc la demande.

**Comment by philippeMo** [comment]
je constate a nouveaux le problème sur une install propre d'un raspberry avec la dernière image en téléchargement,  en ayant comme plugins activés, uniquement "caméra" et "app mobile"

**Comment by philippeMo** [comment]
je pense que je viens de comprendre la cause , en faite le problème se produit si l'on perd  la connexion avec une caméra .

**Comment by zoic21** [comment]
Puis je avoir une capture du soucis ?

**Comment by philippeMo** [comment]
![capture](https://cloud.githubusercontent.com/assets/19261395/15986794/406c5a38-3012-11e6-9c7c-c118b5c8aa84.PNG)

là par exemple, sur le premier widget qui est un module zwave , il apparait l'icone refresh une fraction de seconde toutes les X secondes , parce-que j'ai perdu le réseau de la caméra qui se trouve à coté 
si je desactive la caméra le problèmes disparaît.
si tu veux reproduire le soucis débranche une cam sans la désactiver et tu devrais avoir les icones refresh qui vont clignoter sur tous tes  widget qui n'en n'ont pas.

**Comment by tmartinez69009** [comment]
Loic, j'ai le même phénomène chez moi. À ta dispo pour réaliser des tests.

**Comment by zoic21** [comment]
Je viens de repousser une version en beta du plugin car j'arrive vraiment pas a reproduire, pouvez vous tester avec ?

**Comment by philippeMo** [comment]
je viens de tester la dernière version , mais le problème persiste .

**Comment by tmartinez69009** [comment]
Pareil, le problème persiste pour moi aussi, voici une vidéo du pb : https://youtu.be/96VezinsAMM

**Comment by zoic21** [comment]
Ben je comprend pas faut tester avec quoi comme navigateur ? Sur chrome il y a le soucis ?

**Comment by philippeMo** [comment]
de mon coté je peux reproduire le problème  sur firefox ou chrome .

**Comment by zoic21** [comment]
Ok je pensais ca arrivait pas sur chrome. Pour le coup tant que je reproduis je pourrais pas corriger.

**Comment by philippeMo** [comment]
ok, si tu veux prendre le pi2 que j'ai fraîchement installé, il n'y a pas de problème ..

**Comment by zoic21** [comment]
JE veux bien accès oui il me faut un accès http et ssh

**Comment by zoic21** [comment]
Corrigé dans la dernière beta
