### ISSUE TITLE
[MOBILE][BETA][V80] Nouvelle installation Jeedom, affichage météo KO apps mobile

### ISSUE THREAD

**Issue by phifi92** [jeedom/issues#10]
Apps mobile : V80
Plugin mobile : 2016-06-14 11:37:42
Plugin météo : 2016-05-31 17:30:19
iPhone 6S

J'ai refait une installation de zéro du Jeedom (nouvelle machine). Le plugin météo officiel est bien installé, et ce dernier est fonctionnel (hors apps mobile).

Quand je désire consulter le plugin météo sur l'apps mobile :
- via la pièce, j'obtiens le message : [DISPLAY] undefined is not an objet (evaluating 't.conditionid[0]')
- via le menu plugin, j'obtiens le message : Pop-up iOS, titre : Erreur Météo, contenu : Une ou Plusieurs infoirmations du plugin sonr manquantes !

Je vais tester d'ajouter les bonnes Type générique.

Les "Type générique" ne devraient-ils pas être renseignés automatiquement lors de l'installation du plugin ? Même pour les non utilisateurs de l'apps mobile.

**Comment by rocket13011** [comment]
Résolu sur la V83, qui est dispo

**Comment by phifi92** [comment]
pb tjrs présent, le plugin météo, par défaut, ne paramètre plus de type generic.
J'ai bien supprimé l'objet du plugin Météo pour en créer un nouveau

**Comment by rocket13011** [comment]
problème lier au plugin météo, pas de souci niveau app
