### ISSUE TITLE
[APP] Affichage de l'historique pour des objets de type sondes/temperature

### ISSUE THREAD

**Issue by ouaibsky** [jeedom/issues#100]
Demande de nouvelle feature pour l'application mobile:
- Possibilité d'afficher l'historique pour les valeurs qui sont configurées comme tel.

Cordialement
Christophe.

**Comment by rocket13011** [comment]
Une bonne idée peux être a prévoir pour les version futur avec les notifications et message de l'app (1.2)

**Comment by rocket13011** [comment]
historique sera dans une prochaine version (roadmap OK) je Clos
