### ISSUE TITLE
[APP][1.1]Serrure inversée sur la 1.0.2 il faut que 0 soit considéré comme Ouvert

### ISSUE THREAD

**Issue by rocket13011** [jeedom/issues#101]

**Comment by gui59169** [comment]
en binaire ce n'est pas plutot 0 = fermé, 1 = ouvert ?

**Comment by rocket13011** [comment]
dans le core pour les serrures non, j'ai cru la meme chose que toi quand j'ai codé la serrure sur l'app mobile pour le moment elle est en > 0 = fermé, 1 = ouvert. et pour être pareil que le core il faut l'inverse ;-)

**Comment by nechry** [comment]
en zwave sur la danalock 
Lock = 1
Unlock = 0
Le widget est pas en mode inversé donc prend tel-quelle

**Comment by cyayon** [comment]
Bonjour,

N'y a t-il pas le même problème avec les cadenas ?

Sur l'interface web, le cadena vaut 1 quand il est fermé et vaut 0 quant il est ouvert. 
Sur l'appli IOS, c'est l'inverse qui est pris en compte...
Bien entendu, le mode inversé n'est pas actvé.
