### ISSUE TITLE
[APP][1.1] Bug sur prises multiples virtuel

### ISSUE THREAD

**Issue by gui59169** [jeedom/issues#104]
- la version de jeedom (si c'est une beta la date de dernière mise à jour) : derniere
- la liste des plugins ainsi que leur date de mise à jour : derniere

Depuis maj en 1.0.2 sur iPhone 6 iOS 10, des commandes ne fonctionnent plus. En 1.0.1 pas de soucis.

J'ai 3 prises( avec commandes on/off/état) dans un virtuel.

Lorsque je clique sur le 1ère de la liste c'est le dernier qui s'active... pareil si je clique sur le deuxième. C'est simple je ne peux pas activer ou désactiver BASSIN POMPE ou BASSIN UV..

Ci dessous capture d'écran quand je clique sur BASSIN POMPE, c'est BASSIN BULLEUR qui s'allume.

[http://uploads.tapatalk-cdn.com/20160927/191b813427fa561788abbcbdf455e1ea.jpg](url)

**Comment by rocket13011** [comment]
Mise en place dans la roadmap avec issues > #106
