### ISSUE TITLE
[APP][1.2] possibilité d'avoir un heating (fil pilote) avec moins de 6 cmds

### ISSUE THREAD

**Issue by rocket13011** [jeedom/issues#105]

**Comment by phifi92** [comment]
App 1.1.0 BETA
Module :  FGS-221 Double charge 
Conf du module : fibaro_271/271.512.4106_fgs221.fil.pilote.json

Le toggle ne fonctionne pas (ON /OFF). Toutefois, ok avec les petits boutons

Dans ma conf :+1: 
ON = confort
OFF = off

Images ici : 
https://jeedom.slack.com/files/phifi/F2NGQLV26/fullsizerender.jpg
https://jeedom.slack.com/files/phifi/F2NG3RA6Q/mobile_chauff.png

**Comment by phifi92** [comment]
APP 1.1.0 BETA
Module :  ZMNHBA2 Double Charge 1 

Erreur sur l'apps Mobile : [DISPLAY] undefined is not an object (evaluating 'e.ernergy.off')

Config generic type : 
Confort : Chauffage fil pilote Bouton ON
Off : Chauffage fil pilote Bouton OFF
Etat : Chauffage fil pilote Etat

**Comment by rocket13011** [comment]
Pouvez-vous tester ?

**Comment by phifi92** [comment]
Une amélioration avec cette version, un module sur 2 : OK

 Module : FGS-221 Double charge --> tjrs KO
 Module : ZMNHBA2 Double Charge 1 --> OK à 100%

Pour le FGS-221, config dispo ici pendant 30j : http://ovh.to/qZ8ip5
J'ai aussi mis ma conf du ZMNHBA2 pour info, vu qu'il est fonctionnel maintenant.

**Comment by rocket13011** [comment]
phifi tu peux me donner les screens (generic_type + screen de l'erreur)
