### ISSUE TITLE
[APP][1.0.2] - Probleme sur generic type Heating

### ISSUE THREAD

**Issue by apages2** [jeedom/issues#107]
Lorsque j'associe un HEATING_STATE a une cmd info + HEATING_OFF et HEATING_ON a deux autres commandes d'un meme eqLogic (toutes les autres commandes sont en ne pas remonté a l'application)

Sur l'appli mobile (dans Piece/Eqlogic), j'ai l'erreur [DISPLAY] undefined is not an object (evaulating 'E.energy.off')

L'eqlogic est de type Boxio

Les logs de l'appli lors de la dernière synchro sont (pas de generic_type energy dans les logs) : 

"cmds":[{"id":"69","logicalId":"status1","eqType":"boxio","name":"Status Zone 1 : ","order":"0","type":"info","subType":"string","eqLogic_id":"14","value":"","isVisible":"1","generic_type":"HEATING_STATE","currentValue":"Confort","configuration":{"maxValue":""},"display":{"generic_type":"HEATING_STATE","invertBinary":"0"}},{"id":"70","logicalId":"*#WHO#*51#4*#WHERE###IDUNIT##MEDIA###","eqType":"boxio","name":"Zone 1 - HG","order":"1","type":"action","subType":"other","eqLogic_id":"14","value":"","isVisible":"1","generic_type":"HEATING_OFF","configuration":{"maxValue":""},"display":{"generic_type":"HEATING_OFF","invertBinary":"0"}},{"id":"74","logicalId":"*#WHO#*51#0*#WHERE###IDUNIT##MEDIA###","eqType":"boxio","name":"Zone 1 - Confort","order":"5","type":"action","subType":"other","eqLogic_id":"14","value":"","isVisible":"1","generic_type":"HEATING_ON","configuration":{"maxValue":""},"display":{"generic_type":"HEATING_ON","invertBinary":"0"}}

**Comment by rocket13011** [comment]
sera réglé avec la #105
