### ISSUE TITLE
[CORE] idée > avoir la possibilité de trier les équipements de la page santé (avec un bouton pour rafraîchir)

### ISSUE THREAD

**Issue by rocket13011** [jeedom/issues#109]
Demande d'un utilisateur :
Pourriez vous prévoir la possibilité de trier ou de filtrer les équipements Zwave dans l"écran de santé. Actuellement, les modules sont triés par numéro d'ID, mais après une utilisation de plus d'un an avec une quarantaine de device (avec ajouts et suppressions dans le temps), c'est un peu compliqué à faire un état des lieux rapidement, voir de retrouver un module rapidement. Il faut obligatoirement faire un ctrl F qui nous donne aussi des résultats d'une page en arrière plan.

**Comment by zoic21** [comment]
Ajout du bouton rafraîchir, par contre le filtre est un peu trop complexe ou alors il faut supprimer pas mal de point de présentation.
