### ISSUE TITLE
[CORE][STABLE] Modal cmd configure mauvais listing de "utilisé par scénario" 

### ISSUE THREAD

**Issue by spyjo** [jeedom/issues#11]
Bonjour,

En version stable 2.2.6, quand on est sur la modal d'une commande, en l'occurence ici un script type action, le listing "Utilisé par" sur la ligne des scénarios est invalide. Cela affiche un scénario dont la commande n'est pas utilisé dedans (et ne l'a jamais été auparavant).

Loïc je ne sais pas si tu as éventuellement déjà réglé ce soucis dans la beta 2.3. Si oui, tu peux cloturer :)

Si ce n'est pas le cas, j'ai commencé à fouiller un peu de mon coté, et le soucis se situe sur la ligne suivante, dans la fonction byUsedCommand():
https://github.com/jeedom/core/blob/stable/core/class/scenario.class.php#L480
`$scenarios[] = $expression->getSubElement()->getElement()->getScenario();`

(je n'ai pas creusé plus en profondeur après dans les sous fonctions getElement etc)

Quand je fais un var_dump() de la variable $expressions juste avant ce foreach, l'array contient bien une valeur d'une expression et ça correspond bien à la commande affichée dans la modal.
Ensuite dans ce fameux foreach ligne 479 sur $expressions, et à ce remplissage de l'array $scenarios ligne 480, le var_dump() de $scenarios montre que le scénario récupéré ne correspond pas du tout à l'expression. Donc c'est bien à ce moment là que le scénario récupéré à partir de l'expression devient faux.

Voila l'état de l'array $expressions:

`array(1) {
  [0]=>
  object(scenarioExpression)#24 (7) {
    ["id":"scenarioExpression":private]=>
    string(2) "50"
    ["scenarioSubElement_id":"scenarioExpression":private]=>
    string(1) "4"
    ["type":"scenarioExpression":private]=>
    string(6) "action"
    ["subtype":"scenarioExpression":private]=>
    NULL
    ["expression":"scenarioExpression":private]=>
    string(5) "#383#"
    ["options":"scenarioExpression":private]=>
    string(58) "{"enable":"1","title":"Alerte","message":"détecteur C O"}"
    ["order":"scenarioExpression":private]=>
    string(1) "4"
  }
}`

=> l'expression "Alerte détecteur C O" correspond bien à ma commande.

Et voila l'état de l'array $scenarios : 

`array(1) {
  [0]=>
  object(scenario)#33 (22) {
    ["id":"scenario":private]=>
    string(2) "12"
    ["name":"scenario":private]=>
    string(24) "Reboot Modem pause 30sec"
    ["isActive":"scenario":private]=>
    string(1) "1"
    ["group":"scenario":private]=>
    string(0) ""
    ["state":"scenario":private]=>
    string(4) "stop"
    ["lastLaunch":"scenario":private]=>
    string(19) "0000-00-00 00:00:00"
    ["mode":"scenario":private]=>
    string(7) "provoke"
    ["schedule":"scenario":private]=>
    string(2) "[]"
    ["pid":"scenario":private]=>
    NULL
    ["scenarioElement":"scenario":private]=>
    string(6) "["21"]"
    ["trigger":"scenario":private]=>
    string(2) "[]"
    ["_log":"scenario":private]=>
    NULL
    ["timeout":"scenario":private]=>
    string(1) "0"
    ["object_id":"scenario":private]=>
    string(2) "15"
    ["isVisible":"scenario":private]=>
    string(1) "0"
    ["display":"scenario":private]=>
    string(11) "{"name":""}"
    ["description":"scenario":private]=>
    string(0) ""
    ["configuration":"scenario":private]=>
    string(68) "{"speedPriority":"0","noLog":"0","cmdNoWait":"0","timeDependency":0}"
    ["type":"scenario":private]=>
    string(6) "expert"
    ["_elements":"scenario":private]=>
    array(0) {
    }
    ["_changeState":"scenario":private]=>
    bool(false)
    ["_realTrigger":"scenario":private]=>
    string(0) ""
  }
}`

Le scénario "reboot modem" n'a donc bien rien à voir avec le scénario d'alerte détecteur de CO dans lequel est l'expression "alerte détecteur c o".

Et donc dans la modal, c'est bien le mauvais scénario "reboot modem" qui est affiché sur la commande.

Voila, si tu veux creuser +, dis le moi :)

**Comment by zoic21** [comment]
Je pense que ca corrigera le soucis. Merci pour le retour.

**Comment by spyjo** [comment]
J'ai appliqué le fix, de mon coté c'est ok je vois le bon scénario maintenant :)
merci
