### ISSUE TITLE
[AGENDA][BETA] Evènements disparus lors de la desactivation/re-activation du plugin agenda

### ISSUE THREAD

**Issue by Ssshafi** [jeedom/issues#115]
Tout à jour au 12/10/2016 (Ca le fait aussi sur la dernière stable)
Lors de la réactivation du plugin agenda, tous les évènements des différents agendas ont disparus.
Les agendas sont bien présents mais sans les évènements qui étaient contenus dans ceux-ci.

C'est peut-être normal le ménage lors de la désactivation, mais à ce moment pourquoi les agendas sont encore présents ?

Rien de spécial dans les logs

**Comment by zoic21** [comment]
Bonjour,
C'est en faite normal lors de la désactivation le plugin se désinstalle (pour ne pas laisser des erreurs d’exécution)
