### ISSUE TITLE
[CORE][BETA]  Impossibilité de mettre a jours jeedom et de poussé de nouvel beta de me plugin

### ISSUE THREAD

**Issue by mika-nt28** [jeedom/issues#118]
Jeedom V3.0.0
Un message d'erreur tournant en boucle empêche le fonctionnement de jeedom après un mise a jours du core.
[Fri Oct 14 10:18:47.127762 2016] [:error] [pid 6924] [client 10.9.0.1:49869] PHP Notice:  Undefined index: id in /var/www/html/core/repo/market.repo.php on line 98, referer: https://xxxx.dns1.jeedom.com/index.php?v=d&p=update
Pour retrouver un fonctionnement nominal de mon serveur, je suis obligé de le rebooter

Je n'arrive plus a pousser de nouvelle beta de mes plugin depuis (mise a jours de la suppression du bootstrap)

**Comment by Ssshafi** [comment]
loic vient de corriger ce matin (10h) le soucis pour le message "Undefined index...."

**Comment by mika-nt28** [comment]
Je relance une mise a jours pour voir si cela ce passe mieux

**Comment by mika-nt28** [comment]
La mise a jours c'est bien passée.
Lorsque je pousse une beta sur le market, j'ai bien le message "Votre objet a été envoyé avec succès sur le market" par contre il ne m'a pas demandé le changeLog

**Comment by zoic21** [comment]
C'est tout a fait normal sur la branche beta de jeedom, c'est la mise en place du nouveau systeme décris dans l'article sur le blog
