### ISSUE TITLE
[CORE][BETA] Plantage sur tous les plugins a cause du bootstrapswitch

### ISSUE THREAD

**Issue by mika-nt28** [jeedom/issues#119]
Jeedom V3.0.0
Problème récurent a tous les plugin.
Le bootstrapswich plante le js

getResource.php?file=3rdparty/jquery.utils/jquery.utils.js&md5=1f6c2c2…&lan…:378 Uncaught TypeError: $(...).bootstrapSwitch is not a function$.fn.value @ getResource.php?file=3rdparty/jquery.utils/jquery.utils.js&md5=1f6c2c2…&lan…:378$.fn.setValues @ getResource.php?file=3rdparty/jquery.utils/jquery.utils.js&md5=1f6c2c2…&lan…:558success @ getResource.php?file=desktop/js/plugin.js&md5=79b5e5f…&lang=fr_FR:247success @ getResource.php?file=core/js/private.class.js&md5=b8db850…&lang=fr_FR:117i @ getResource.php?file=3rdparty/jquery/jquery.min.js&md5=ac5017a…&lang=fr_FR:2fireWith @ getResource.php?file=3rdparty/jquery/jquery.min.js&md5=ac5017a…&lang=fr_FR:2A @ getResource.php?file=3rdparty/jquery/jquery.min.js&md5=ac5017a…&lang=fr_FR:4(anonymous function) @ getResource.php?file=3rdparty/jquery/jquery.min.js&md5=ac5017a…&lang=fr_FR:4
getResource.php?file=3rdparty/jquery/jquery.min.js&md5=ac5017a…&lang=fr_FR:4 XHR finished loading: POST "https://xxxx.dns1.jeedom.com/core/ajax/event.ajax.php".send @ getResource.php?file=3rdparty/jquery/jquery.min.js&md5=ac5017a…&lang=fr_FR:4ajax @ getResource.php?file=3rdparty/jquery/jquery.min.js&md5=ac5017a…&lang=fr_FR:4jeedom.changes @ getResource.php?file=core/js/jeedom.class.js&md5=ca94b7a…&lang=fr_FR:83

**Comment by zoic21** [comment]
Bonjour,
Le bootstrapswitch est retiré en 3.0 il est donc normal que les plugins qui s'en servent plantes, il faut mettre à jour les plugins

**Comment by mika-nt28** [comment]
Oui ça je me doute bien et c'est bien dommage car estetiquement je preferai le bootstrap
J'ai mis a jours mes plugins, mais c'est un peux genant d'etre bloqué de devoir attendre que les plugin soit mise a jours pour pouvoir faire un retouche

**Comment by zoic21** [comment]
Pas compris une retouche de quoi ? Et bloqué par quoi ?

**Comment by mika-nt28** [comment]
Tous les plugins doivent supprimer le bootstrapswich sinon on est bloqué par le message d'erreur que j'ai mis plus haut.

Si on a besoin de mettre a jours la configuration d'un plugin on ne peux donc pas

**Comment by zoic21** [comment]
Oui c'est normal c'est pour jeedom 3.0 dans 6 ou 8 mois donc ça laisse le temps pour que les devs mettent à jour je pense non ? De plus tu es sur la branche beta donc c'est sur que ca marche pas avec tous les plugins. Enfin je vois vraiment rien d'anormal ou de choquant la dedans c'est le cycle de vie normal d'un logiciel.

**Comment by mika-nt28** [comment]
Ok, je comprend ce que tu veux dir.
Je me demerde en attendant que tous les plugins se mette a jours
