### ISSUE TITLE
[CORE][STABLE 2.4] Bug sur l'onglet Résumé des objets

### ISSUE THREAD

**Issue by spyjo** [jeedom/issues#121]
Bonjour,

Suite au passage à la dernière stable, ci-joint capture d'écran et log pour l'onget Résumé des objets qui semble poser soucis, peu importe l'objet:

![image](https://cloud.githubusercontent.com/assets/4271747/19479852/eb4b231c-9548-11e6-84aa-40b61400939c.png)

`2016/10/18 15:31:44 [error] 14914#0: *9351076 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 238
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/core/class/object.class.php on line 514
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/desktop/php/object.php on line 132
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/www/jeedom/desktop/php/object.php on line 143`

Merci

**Comment by zoic21** [comment]
Bonjour,
Il faut d'abord créer des résumés pour pouvoir les affecter. Pour cela il faut aller dans l'administration de jeedom

**Comment by spyjo** [comment]
Suite à la nouvelle maj cela semble ok maintenant, merci
