### ISSUE TITLE
[CORE][STABLE 2.4] Bug d'affichage sur le listing des objets

### ISSUE THREAD

**Issue by spyjo** [jeedom/issues#122]
Suite à la mise en place du résumé global, sur la page des objets les informations résumées sont cachées par la rangée du dessous, il n'y a pas assez d'espace entre les rangées.

Exemple:
<img width="171" alt="capture d ecran 2016-10-18 a 22 24 52" src="https://cloud.githubusercontent.com/assets/4271747/19495035/fcfb9644-9581-11e6-8eb8-7b680c79af11.png">

A savoir que sur certains objets j'ai même 2 lignes de résumé, donc l'écart nécessaire est d'autant plus important.

Merci

**Comment by zoic21** [comment]
Bonjour,
C'est corrigé
