### ISSUE TITLE
[CORE][STABLE 2.4] Problème affichage changelog sur le market

### ISSUE THREAD

**Issue by spyjo** [jeedom/issues#123]
Quand on est dans le centre des MAJ sur Jeedom, et qu'on clique sur un bouton Changelog, admettons pour le plugin Alarme:
on ouvre donc le lien https://market.jeedom.fr/index.php?v=d&p=market&type=plugin&plugin_id=alarm
qui redirige sur
https://www.jeedom.com/market/index.php?v=d&p=market&type=plugin&plugin_id=alarm
et qui ouvre une modal, sauf que cette dernière reste blanche.
La console de Chrome indique l'erreur "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" sur l'url d'ajax de la modal.

Screenshot:

<img width="750" alt="capture d ecran 2016-10-18 a 22 43 35" src="https://cloud.githubusercontent.com/assets/4271747/19495618/67b0e82a-9584-11e6-9c6d-202ab147480f.png">

**Comment by zoic21** [comment]
Bonjour,
C'est corrigé. Merci pour le retour
