### ISSUE TITLE
[CORE][STABLE 2.4] Suggestion d'amélioration du listing "Utilisé par" d'une commande

### ISSUE THREAD

**Issue by spyjo** [jeedom/issues#124]
Actuellement quand on ouvre la modal d'une commande, dans la partie "Utilisé par", il y a Equipement , Commandes , et Scénario.

Je propose de rajouter "Intéractions", en effet par exemple on peut supprimer une commande sans se rendre compte qu'elle était encore utilisée dans une intéraction en action (oui c'est du vécu.. à l'instant ^^)

Merci

**Comment by zoic21** [comment]
Bonjour,
Malheureusement ce n'est plus si simple, en 2.4 c'est valable en 3.0 ça ne le sera plus car nous avons introduit la notion d'auto-interaction qui permet a jeedom de comprendre la demande même si l'interaction n'existe pas donc toute les commandes sont utilisées dans les interactions.

**Comment by spyjo** [comment]
En effet j'ai vu cette prochaine nouveauté, c'est une bonne idée :)

Cependant il ne sera plus possible de choisir manuellement des actions ? Car évidemment en mode auto toutes les commandes seront potentiellement une action, mais je pense que pour les actions choisies manuellement ça peut toujours être utile de les lister dans "Utilisé par" :)

**Comment by zoic21** [comment]
Si si possible mais le utilisé par ne marcherait pas car il dirait que c'est tous le temps utilisé par les interactions.

**Comment by spyjo** [comment]
Ah oki je comprends techniquement tu vas pré-attribuer toute action possible dans les intéractions pour ne pas les chercher à la volée à chaque fois ?

**Comment by zoic21** [comment]
Non non c'est fait a la volé mais d'un point de vue fonctionnel toute les commandes sont au moins utilisée dans une interaction, celle qui est automatique
