### ISSUE TITLE
[CORE] Optimisation

### ISSUE THREAD

**Issue by colas31** [jeedom/issues#125]
hello,

J'ai regardé les perf de Jeedom (2.4.4) car sur Mobile, l'affichage du design en plein écran est un peu lent à mon gout à se générer. 

- L'appel à la fonction jeedom::isCapable('sudo') prend le plus de temps. Est ce qu'il n'est pas possible de mettre le retour du shell_exec dans un fichier qui ne se mettrait à jour que via une tâche ? et l'appel à cette fonction irait lire ce fichier ?

- je vois également qu'il y a beaucoup de md5_file de fait. 
Pour certain, (dont la valeur n'est pas utilisé pour l'Etag), on pourrait utiliser jeedom::version() à la place. 
Je pense que même pour générer l'Etag, le jeedom::version() pourrait être utilisé.
Et ne faire l'appler à md5_file que pour les deux fichiers custom (css / js) que dont l'utilisateur peut changer via la configuration.

Qu'en penses tu ?

**Comment by zoic21** [comment]
Bonjour,
Alors : 
1) J'ai fait une optimisation a ce niveau avec une mise en cache du résultat, cela sera disponible en 3.0
2) Pas possible car pour les betatesteurs ou même moi j'ai besoin de vraiment le calcul sur le md5 du fichier car on incrémente pas la version de jeedom à chaque changement

**Comment by colas31** [comment]
Merci :)
2) il y a pas du code plus rapide qu'un md5_file ? genre faire un md5(filemtime()) ? 

Désolé du dérangement mais c'est vrai qu'en tant que dev aussi on cherche toujours les perfs ;)

**Comment by zoic21** [comment]
Je pense pas que ca soit plus rapide, j'ai fait pas mal de test la dessus avant d'avoir un truc fiable, normalement le serveur devrait le gérer de lui même en envoyant justement le mtime au navigateur mais ca n'a jamais trop marché....

**Comment by colas31** [comment]
D'ailleur remarque con, tu pouvais même optimiser ta ligne par : 
$result = (shell_exec('sudo -l > /dev/null 2>&1; echo $?') == 0);

**Comment by colas31** [comment]
Oui c'est un peu compliqué cette gestion des header et cache. 
Est ce que tu avais tenté avec un 
Cache-Control:public, s-maxage=xxxx, must-revalidate

**Comment by zoic21** [comment]
Oui oui c'est le cas mais ca marche pas dans 100% des cas alors que le md5 jamais eu de soucis

**Comment by colas31** [comment]
Bon si tu as trouvé la solution idéal, alors faut pas y toucher ;)
