### ISSUE TITLE
[Weather] Heure de lever et coucher de soleil erronée

### ISSUE THREAD

**Issue by colas31** [jeedom/issues#126]
Version du core : 2.4.5
Version du plugin Weather : 2016-10-11 01:05:38

L'heure du lever du soleil vaut toujours 500
et l'heure du coucher du soleil vaut toujours 1600

Sur le site Web de l'API aucun soucis. 

Cet appel $weather->sun->rise->setTimezone(new \DateTimezone('Europe/Berlin'))->format('Gi') semble retourner la bonne valeur.

Par contre sur le dashboard et dans la configuration de l'équipement les heures retournées sont erronées.

J'ai forcé la réinstallation du plugin rien n'a changé. La problème semble venir plus du core qui a été mis à jour récemment

Merci

**Comment by zoic21** [comment]
Corrigé, le plugin sera disponible demain en stable, attention il faudra absolument jeedom 2.4.6

**Comment by colas31** [comment]
merci, 
Du coup il y a aura une maj du core aussi en même temps ?

**Comment by zoic21** [comment]
La maj du core est déja disponible depuis ce matin

**Comment by colas31** [comment]
Parfait :)
par curiosité c'était quoi le soucis ? 
j'ai regardé ton commit mais c'est très flou pour moi :D

**Comment by zoic21** [comment]
Une nouvelle gestion au niveau du core sur la répétition des valeur d’événement, tout est expliqué dans l'article du blog.

**Comment by colas31** [comment]
merci Loic pour ta rapidité. Je vais lire tout ça.
