### ISSUE TITLE
[CORE][SCENARIO] Bouton Partager sur Market

### ISSUE THREAD

**Issue by PuNiSHeR374** [jeedom/issues#127]
Version : 2.4.6

Bonjour,

C'est un problème que j'avais déjà exposé dans un post du Forum, resté sans réponse, mais même avec les dernières mises à jour, le problème persiste.

Quand je veux partager ou mettre à jour un scénario sur le Market des scénarios, je clique sur le bouton "Partager sur Market", mais il n'y a plus la fenêtre modal qui s'ouvre pour modifier le changelog et uploader le fichier.

Le problème est confirmé par un autre membre pour le moment.

![market](https://cloud.githubusercontent.com/assets/17704870/19836498/8678a71c-9ea2-11e6-9248-b9855367c418.jpg)

D'avance, merci et merci également pour ses dernières mises à jour 2.4.x qui sont top et très stable.

Bon courage. ;)

**Comment by zoic21** [comment]
Bonjour,

Merci pour le retour j'ai fait la correction (il faut forcer la mise à jour car j'ai pas encore incrémenté le numéro de version)

**Comment by PuNiSHeR374** [comment]
Super, Merci.
