### ISSUE TITLE
Idée : Langue de plugin sur le market

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#128]
Bonjour,

Lorsque l'on publie un plugin sur le market, il faut identifié les langues dans lequel il est traduit.
Il me semble que cette partie pourrait être paramétré en fonction des fichiers présent dans le plugin ?

A+
Thomas

**Comment by zoic21** [comment]
Bonjour,
Non car un fichier de langue peut être la mais pas être traduit à l’intérieure.

**Comment by guenneguezt** [comment]
Effectivement.
Idée : Comparer le pourcentage de ligne qui diffère.
Par exemple si 80% est différent, c'est que tu as de fortes chances que ce soit traduit...
