### ISSUE TITLE
[CORE] Proposition : gérer des dates dans la page batterie

### ISSUE THREAD

**Issue by abarrau** [jeedom/issues#129]
(Bjr,)

Dans la configuration des équipements sur l'onglet "batterie", avoir la possibilité de saisir une date. 
Cela permettrait de suivre la date à laquelle la batterie a été changée. 

Puis depuis le "panel" des batteries, avoir cette date apparaître en bas de tuile.
Cf. des maquettes de mise en oeuvre. (avec un "datepicker" sur le champs date).

Page équipement :
![pile_equipement](https://cloud.githubusercontent.com/assets/13674762/20028459/6b025b10-a332-11e6-8a08-786895f90b4f.PNG)
Tuile batterie : 
![pile_tuile](https://cloud.githubusercontent.com/assets/13674762/20028458/6afbe096-a332-11e6-9d74-6b0f2c15b836.PNG)

(proposition déjà faite en début d'année via le forum, mais peut-être pas "vue").
Merci, Aurélien

**Comment by zoic21** [comment]
Bonjour,
L'idée est bonne mais nous n'avons pas le temps ni les ressources pour le faire, nous avons mis en place un champs commentaire sur tous les équipements en 3.0 vous pourrez mettre l'information à cette endroits la.

**Comment by abarrau** [comment]
Ok je me doute que le temps manque.
Oui j'ai vu le nouveau champs "commentaire".
Si je vous propose l'évolution, c'est intégrable ?
