### ISSUE TITLE
[Agenda] Pertes des évènements lors de la dératisation/activation du plugin

### ISSUE THREAD

**Issue by mamatdv** [jeedom/issues#130]
Sur la dernière beta du core et du plug lors de la deactivation et de l'activation du plugin agenda, tous les évènements de tous les agenda ont disparu.

**Comment by zoic21** [comment]
Bonjour,
Le soucis à été identifié et il est normal pour moi car la désactivation fait jouer la désinstallation du plugin (obligé sinon il y a des erreurs sur les crons qui vont apparaître).
