### ISSUE TITLE
[CORE] Erreur update jeedom raspi

### ISSUE THREAD

**Issue by ifma** [jeedom/issues#131]
Details : 1[END UPDATE ERROR]
![jeedom](https://cloud.githubusercontent.com/assets/13037313/20057628/d7b9e5d2-a4ec-11e6-8876-24d1c5596b01.JPG)

PHP Fatal error:  Uncaught exception 'Exception' with message '[MySQL] Error code : 42000 (1091). Can't DROP 'cache'; check that column/key exists' in /var/www/html/core/class/DB.class.php:101
Stack trace:
#0 /var/www/html/install/install.php(292): DB::Prepare('ALTER TABLE `cm...', Array, 0)
#1 {main}
thrown in /var/www/html/core/class/DB.class.php on line 101

**Comment by zoic21** [comment]
Bonjour,
Cela semble etre un soucis particulier sur votre installation, il faut donc ouvrir un ticket à l'équipe jeedom
