### ISSUE TITLE
[CORE] [IMAGE RPI] unable to resolve host

### ISSUE THREAD

**Issue by Ssshafi** [jeedom/issues#132]
Suite à l'installation sur un Pi3 avec la dernière image en netinstall des erreurs apparaissent dans le http.error ainsi que dans le log de mise à jour lorsque l'on lance celle ci :
> erreur : sudo: unable to resolve host jeedom

Une modif du /etc/hosts pour remplacer la ligne 127.0.0.1   raspberrypi
par : 127.0.0.1   jeedom
a solutionné le problème.

Image utilisée : raspberrypi3_Debian_jessie_4.4_jeedom_netinstall_20160924_alpha1.img dans le fichier Raspberrypi_Debian_jessie_4.4_jeedom_netinstall_20160924_rc1.rar disponible sur le drive amazon.

**Comment by zoic21** [comment]
Corrigé

**Comment by iquid** [comment]
J'ai viens d'avoir le même bug avec une installation franchement réalisée avec l'image Raspberrypi_Debian_jessie_4.4_jeedom_netinstall_20160924_rc1
il n'y a pas d'image plus récente ?

**Comment by magicgg91** [comment]
C'est corrigé dans le script d'installation en bêta, il faut donc attendre la prochaine version stable.
L'image est bien la bonne.

**Comment by dertione** [comment]
C'est toujours d'actualité avec la version que j'ai téléchargé aujourd'hui. Quelle est l'alternative s'il vous plaît ? (erreur avec démons du plugin xiaomi home entre autre)

**Comment by magicgg91** [comment]
Oui normal, il n'y a pas eu de nouvelle version stable de Jeedom. C'est corrigé dans la prochaine version stable de Jeedom comme déjà mentionné, et donc du script d'installation.

**Comment by magicgg91** [comment]
Et rien à voir avec des problèmes rencontrés avec un plugin, cela n'a aucune incidence.

**Comment by dertione** [comment]
Oui merci j'ai bien lu, je demandais si il n'y avait pas d'alternative, genre récupérer le nouveau script d'installation et lancer une réinstallation ou prendre une version beta ? Ou bidouiller ?
Bah moi mon plugin ne fonctionne pas correctement car j'ai cette erreur, je l'ai trouvé grâce au problème d'installation de celui-ci donc ok ce n'est pas dû au plugin mais le fonctionnement de ce plugin est impacté avec cette erreur

**Comment by magicgg91** [comment]
Il suffit de faire la modif manuellement comme décrit dans l'issue. Ne surtout pas relancer 1 installation sue 1 Jeedom existant. Et les bêta sont réservées aux bêtas-testeurs ou utilisateurs avertis qui savent l'installer sans devoir demander.
Et non, ce n'est pas cette "erreur" (qui n'en est pas une) qui fait que ton plugin Xiaomi Home ne fonctionne pas, ça c'est sûr !
