### ISSUE TITLE
[CORE][BETA][3.0.0][DESIGN] cmd qui disparaissent en mode édition à l'ajout d'une nouvelle même cmd

### ISSUE THREAD

**Issue by skyline-ch** [jeedom/issues#133]
version de jeedom : 3.0.0 du 08.11.16

Résumer du bug : 
si on ajoute plusieurs fois la même commande sur un design, a l'ajout du nouveau le/les précédant disparaissent du mode édition, si ont sauve et quitte le mode édition puis actualise la page ont retrouve toutes les commandes (les même ajoutées plusieurs fois).

Comment reproduire:
Ouvrir un design, ajouter une commande, la placer, sauver, ajouter à nouveau cette même commande (la précédente disparait), sauver, quitter le mode édition, actualiser la page, la commande apparait bien 2 fois comme placé, si ont édite les 2 sont bien la, ont ajoute a nouveau la même commande, les 2 précédente disparaissent , on sauve quitte le mode et actualise ont à 3 fois la commande.

Le fait de pouvoir avoir plusieurs fois la même commande peut-être pratique dans certain cas, tout fois la disparition de ses commande dans le mode édition peux être troublant.

3 fois la même commande
![capture023](https://cloud.githubusercontent.com/assets/13089438/20120767/6e1f337a-a60e-11e6-8781-5cdf02cf65b8.png)

En mode édition
![capture024](https://cloud.githubusercontent.com/assets/13089438/20120764/6e1c5588-a60e-11e6-9b96-38ddb70721bc.png)

Après ajout de la même commande pour la 4ème fois
![capture025](https://cloud.githubusercontent.com/assets/13089438/20120765/6e1cf204-a60e-11e6-9ffb-9d8ceaa933e6.png)

après sauve de l'ajout de la 4ième, quitter mode édition et actualisation de la page
![capture026](https://cloud.githubusercontent.com/assets/13089438/20120766/6e1e2066-a60e-11e6-827b-f45c76a19f7c.png)

**Comment by stephaneSBO** [comment]
Pour Loic, je reproduis le bug. Rien de bloquant, mais effectivement déroutant

**Comment by zoic21** [comment]
Bonjour,
Je viens de faire la correction dans la derniere beta, les doublons existant ne seront pas supprimé mais il ne devrait plus etre possible d'en faire de nouveau.
