### ISSUE TITLE
[CORE][BETA][3.0.0][DESIGN] cmd déplacée hors zone design (2 cas)

### ISSUE THREAD

**Issue by skyline-ch** [jeedom/issues#134]
version de jeedom : 3.0.0 du 09.11.16 14h30

Résumer du bug :
2 cas identifier où cela se produit, cas 1 avec le widget par défaut des variateurs, cas 2 widget perso qui na pas la fonction update, les commandes en question sont placée hors de la zone du design a l'actualisation de la valeur

Comment reproduire:
cas 1 : tester avec un module zwave bouton variateur, ajouter la commande seul sur le design, sauver et quitter le mode édition, faire varier le bouton pour provoquer le changement de valeur, a se moment la le widget sorte de la zone du design (tester aussi avec la puissance sur wall plug, idem)

Cas 2 : constater avec des valeur de sonde de température, pour tester j'ai créer un virtuel avec 2 info numéric pour imiter les valeurs de température, j'ai aussi mis 2 curseurs lier à chacune de ses info num pour facilité le changement de valeur.
sur une des info num appliquer le widget title du core, sur l'autre un widget perso très proche du title (ex version du core).
Si ont ne met que les 2 cmd seul sans l'équipement, la valeur du widget perso ne s'actualise pas, si ont ajoute sur le design l'équipement a se moment la valeur du widget perso s’actualise mais sort de la zone du design.

J'ai comparer les class et para html, ajouter un à un ceux qui étais différant sans succès, en revanche l'ajout de la fonction js update, et la class "state" au span qui contiens la valeur a permis de résoudre le problème pour le widget perso.
Pour le widget du core j'ai pas tester si l'ajout d'une fonction update résous le problème.

il semble donc que la fonction update soie obligatoire pour pouvoir fonctionner correctement dans le design, si telle est le cas ils faudra bien le communiquer

Avant actualisation des valeurs
![capture027](https://cloud.githubusercontent.com/assets/13089438/20142892/eb3fd0c0-a696-11e6-821c-545ffa1f775c.png)

Maj de la valeur widget perso
![capture028](https://cloud.githubusercontent.com/assets/13089438/20142891/eb3ad534-a696-11e6-941b-eff8e9fd9d44.png)

Maj de la valeur variateur
![capture029](https://cloud.githubusercontent.com/assets/13089438/20142890/eb3a5578-a696-11e6-98d9-976926ff111d.png)

**Comment by zoic21** [comment]
Cas 1 : ok chez moi je n'arrive pas a reproduire je pense ca vient du widget demi arc qui n'a pas encore la commande d'update
Cas 2 : les widgets sans valeurs d'update sont déprécié.
