### ISSUE TITLE
[CORE] Bug affichage checkbox avec differents themes dans onglet "commandes"

### ISSUE THREAD

**Issue by gui59169** [jeedom/issues#135]
Bonjour,

sur jeedom 2.4.6 il y a un soucis d'affichage des checkbox dans l'onglet "commandes" d'un plugin.
Je ne sais pas si le soucis etait present avant.

Avec le plugin par defaut , pas de probleme.
![capture](https://cloud.githubusercontent.com/assets/22484524/20195544/584c85d6-a797-11e6-80be-294fd47c8c50.JPG)

**Comment by zoic21** [comment]
Bonjour,
Officiellement seul le thème par défaut et le dark sont supporté. Les autres thèmes peuvent donc être buguer, nous réfléchissons d'ailleurs à ne laisser que celui par défaut et le dark car nous n'avons pas le temps de supporter les autres.
