### ISSUE TITLE
[RFXCOM] Ajout support poêle MCZ

### ISSUE THREAD

**Issue by PuNiSHeR374** [jeedom/issues#136]
Bonjour,

Suite à un sujet concernant le support des Poêles de marque MCZ sur le forum "toute la domotique" : 

http://www.touteladomotique.com/forum/viewtopic.php?f=6&t=8706&start=336#p144790

Bert a fait une mise à jour du firmware passant en version 1009 pour justement avoir ce support.

Du coup, plusieurs membres sur le forum en on fait la demande de support avec le plugin.

https://www.jeedom.com/forum/viewtopic.php?f=36&t=22366

Est ce que l'intégration est prévue au planning, à court ou long terme ?

D'avance, merci pour eux.

**Comment by zoic21** [comment]
Bonjour,

L’intégration est bien prévu et nous allons la commencer dès que le bug qui pose soucis chez plusieurs utilisateurs sera résolue. Pour la branche beta c'est donc plutôt prévu à cours terme en revanche pour la version stable ça sera à long terme, en effet vu que beaucoup d'utilisateurs se sont plains du manque de tests de notre coté nous allons petit à petit passer sur des tests de plusieurs mois au lieu de semaines.

**Comment by PuNiSHeR374** [comment]
Merci Loïc, je fais passer l'info.

Bon Dimanche. ;)

**Comment by zoic21** [comment]
Bonjour,
J'ai voulu regarder mais la doc rfxcom n'est pas très clair, est-ce un nouveau protocole  ? Donc le 26 ? Ou est ce un ajout à un protocole ? Dans ce cas le plugin est déjà compatible.

**Comment by PuNiSHeR374** [comment]
Bonjour Loïc,

Ben en fait, Bert à du à du l'intégrer dans le firmware et moi, j'ai trouvé ça dans la doc anglais si ça peut t'aider.

![rfx](https://cloud.githubusercontent.com/assets/17704870/20272233/9b58be5a-aa8d-11e6-9ad1-d01aab15fa44.jpg)

Est ce que ce protocole thermostat4 est intégré au plugin ?

Sur le tableau de la doc, je ne vois pas de protocole supplémentaire.

**Comment by zoic21** [comment]
J'avais vu cette doc mais je ne trouve aucune info sur le protocole thermostat4.... Si tu as la commande brute en hexadecimal envoyé par le rfxcom ca pourrait m'aider.

**Comment by PuNiSHeR374** [comment]
Bon, j'ai cherché pas mal sur le net, même sur les posts de homesser où Bert est très actif, mais pas moyen de trouver quoi que ce soit, ni en trame brut, ni en protocoles.

J'ai demandé à kerber29 qui est actif sur le forum "toute la domotique" et qui est venu sur notre forum de venir participer à cette conversation pour t'expliquer, parce qu'il a contribué à l’intégration du poêle MCZ dans le firmware RFXCom.

Voici son message avant que je l'invite à venir : 

> Bonjour à tous,

En résumé, Il s'agit du code C que j'ai développé pour reproduire le protocole de communication entre la télécommande MCZ et le poêle/insert. Le hacking du protocole a été effectué par moi et d'autres membres de l'excellent forum touteladomotique.com, Samwise, nestof , cazadeis, et bien sûr Thorgalf ;) .
Ce code C est fonctionnel sur RPI (ou autres) et Bert l'a adapté pour l'intégrer dans le firmware du RFXcom.
Actuellement, je pilote mon MCZ par RFXcom et Jeedom, mais avec l'aide du plug-in script, en attendant une éventuelle MAJ du plug-in RFXCom.

**Comment by zoic21** [comment]
Ok de ce que je vois je pense que jeedom est déjà compatible (pas sur à 100%), je pense qu'il suffit dans jeedom de creer un équipement puis une commande et de mettre : 0C430003112233010101010000 par exemple. A tester si ca marche je verrais pour faire une implementation

**Comment by PuNiSHeR374** [comment]
Ok, je demande sur le forum si quelqu'un veut bien tester avec la commande que tu donnes, il y a plusieurs membres intéressé.

Elle permet quoi cette commande, un Of, ou un Off sur un ventilateur du poêle ??

**Comment by KerberRF** [comment]
Bonjour,
J'utilise ces commandes hexa actuellement. C'est Bert qui me les envoyées, par contre, c'est à diffusion restreinte. Il faudrait lui demander son avis à ce sujet.

**Comment by PuNiSHeR374** [comment]
Loïc, c'est bon, la commande fonctionne chez au moins 2 personnes et me disent que çette commande a éteint leurs poêles.

Voilà pour les retours.

**Comment by zoic21** [comment]
Ok nickel bon je vais attendre le retour de Bert pour savoir si les codes peuvent etre diffusé car si c'est pas le cas aucune intégration possible....

**Comment by KerberRF** [comment]
Message de Bert, il souhaiterait que zoic21 le contacte sur son @ mail : support@rfxcom.com
Merci d'avance.

**Comment by PuNiSHeR374** [comment]
Salut Loïc,

Alors, cela raconte quoi avec Bert ??

As tu pu avoir un échange et as tu réussi à négocier quelque chose ??

Merci.

**Comment by zoic21** [comment]
Oui c'est tout bon faut juste maintenant que je trouve le temps de bosser dessus car il y a pas mal de truc au final vu qu'une trame doit contenir toute les informations

**Comment by PuNiSHeR374** [comment]
C'est super, c'est une bonne nouvelle.
C'est vrai qu'il n'y a jamais eu de réel problème avec Bert, il est relativement bien ouvert aux demandes.
Maintenant, oui, c'est sure vu le boulot, prends ton temps, le plus important pour les membres est de savoir que ce sera intégré.
Merci pour eux, merci à toi pour ce que tu fais, ainsi que le reste de l'équipe et bon courage.

**Comment by zoic21** [comment]
Bonjour,
Le support vient d'etre ajouter dans la beta du plugin

**Comment by PuNiSHeR374** [comment]
Merci à toi Loïc, pour les membres demandeurs. Et mes meilleurs voeux à l'équipe pour 2017, que Jeedom continue à grandir comme vous le faites si bien.

**Comment by Gis70** [comment]
Bonjour,

Disposant de Jeedom Beta 3.0.8 et du Plugin RFXCOM Beta, je ne trouve pas l'équipement MCZ dans la liste alors que je le trouve dans le dossier "devices", C'est comme s'il était masqué... comment puis je le voir apparaître ? (le pilotage du poêle fonctionne directement depuis le soft du rfxcom, j'ai pu l'essayer. Si quelqu'un peut m'aider... Merci.

**Comment by zoic21** [comment]
Bonjour,
j'ai poussé une correction elle sera disponible demain matin.

**Comment by Gis70** [comment]
Bonjour,

Merci j'ai bien les 2 types de poêles dans le menu déroulant, problème, RFXmanager me détecte le poêle comme ayant 3 ventilos (du moins dans la trame envoyée car ce n'est qu'un modèle avec 2 ventilos) du coup cela ne fonctionne pas à cause de ça je pense. L'ID à renseigner c'est l'ID détecté par rfxmanager sur 6char hexa c'est bien ça ?

**Comment by zoic21** [comment]
Pour l'id je ne sais pas, soit c'est celui du rfxmanager soit un nouveau et faire l'association.
Pour le ventilos je ne sais pas non j'ai juste appliqué les spécifications de rfscom

**Comment by Gis70** [comment]
Salut,

J'ai testé par le rfxmanager le poêle 2 ventilos, cela a bien commandé mon poêle aussi, donc que ce soit 2-3 ventilos avec le rfxmanager ça marche. Par contre par le plugin 2 ventilos sous Jeedom ça ne marche pas, rien n'est reçu par le poêle malgré que j'ai rentré l'ID. J'ai testé 0xA20702 ou A20702 qui est l'ID découvert par le rfxmanager. Rien ne se passe.

J'ai un message dans le Debug : [error] Invalid message from socket

Que faire ?

Qui utilise le plugin jeedom avec poêle MCZ ?

**Comment by zoic21** [comment]
Il me faudrait la log en debug du démon lors de l'envoi d'un message, la log aussi du rfxmanager pour voir le message que lui envoi.

Personne utilise pour l'instant le plugin avec un poele mcz

**Comment by Gis70** [comment]
Dans le debug rfxcom jeedom j'ai ça :  
[2017-04-24 21:34:46][DEBUG] : Special function execCmd143 return  : 0C4302020xA207020103010200
[2017-04-24 21:34:46][ERROR] : Invalid message from socket.
[2017-04-24 21:35:02][DEBUG] : Special function execCmd143 return  : 0C4302020xA207020103010000
[2017-04-24 21:35:02][ERROR] : Invalid message from socket.
[2017-04-24 21:46:08][DEBUG] : Special function execCmd143 return  : 0C430202A207020102010000
[2017-04-24 21:46:09][ERROR] : Invalid message from socket.
[2017-04-24 21:46:09][DEBUG] : Special function execCmd143 return  : 0C430202A207020102010000
[2017-04-24 21:46:10][ERROR] : Invalid message from socket.
[2017-04-24 21:46:10][DEBUG] : Special function execCmd143 return  : 0C430202A207020101010000
[2017-04-24 21:46:10][ERROR] : Invalid message from socket.
[2017-04-24 21:51:40][DEBUG] : Special function execCmd143 return  : 0C430202A207020101010200
[2017-04-24 21:51:40][ERROR] : Invalid message from socket.
[2017-04-24 21:57:43][DEBUG] : Special function execCmd143 return  : 0C4302020xA207020101010200
[2017-04-24 21:57:43][ERROR] : Invalid message from socket.

![capture_mcz_2ventilos_ok](https://cloud.githubusercontent.com/assets/16589132/25405647/2d923a58-2a04-11e7-96db-12ea2941ff0e.JPG)

N'hésite pas à me solliciter pour quoi que ce soit, j'ai hâte de pouvoir commander ce poêle !

**Comment by Gis70** [comment]
Suite à l'update du plugin rfxcom j'ai un debug plus verbeux : 

[2017-04-26 14:17:47][DEBUG] : Special function execCmd143 return  : 0C430202A207020102020200
[2017-04-26 14:17:47][DEBUG] : Client connected to [127.0.0.1:39394]
[2017-04-26 14:17:47][DEBUG] : Message read from socket: {"apikey":"RH9XgQCIVrL1TwnnEXiUKU9hIHxjDvU3","cmd":"send","data":["0C430202A207020102020200"]}
[2017-04-26 14:17:47][DEBUG] : Client disconnected from [127.0.0.1:39394]
[2017-04-26 14:17:47][DEBUG] : Message received in socket JEEDOM_SOCKET_MESSAGE
[2017-04-26 14:17:47][DEBUG] : Test message: 0C430202A207020102020200
[2017-04-26 14:17:47][DEBUG] : Error: Packet length is not valid
[2017-04-26 14:17:47][ERROR] : Invalid message from socket.

**Comment by zoic21** [comment]
Bonjour,
J'ai envoyé une correction elle sera disponible demain donc a voir si ca corrige.

**Comment by Gis70** [comment]
En reprenant la trame de test  0C430003**A20702**010101010000 plus haut dans le post qui servait à éteindre le poêle et en y mettant mon **ID** ça éteint le poêle. La longueur des trames envoyées et celle de test est différente, je pense que c'est ça le pb. Donc si ta correction modifie la longueur de la trame ça devrait le faire :-) merci pour le support.

**Comment by zoic21** [comment]
Non elle sera pas bonne peux tu detailler plus la tram en question le soucis vient de la effectivement

**Comment by zoic21** [comment]
Ok je pense avoir trouvé il manque le fan 2 qui est obligatoire en faire, demain ca devrait etre bon normalement (enfin j'espere)

**Comment by Gis70** [comment]
Ok, sinon pour tester plus rapidement envoie moi le zip du plugin (où juste les fichiers modifiés)

**Comment by zoic21** [comment]
Je viens de pousser sur le market la correction en beta

**Comment by Gis70** [comment]
It's working !!! Génial. Cette fois on va vraiment rentrer dans une phase de Beta Test :-)

**Comment by zoic21** [comment]
Cool ben test bien et dis moi si ya des problèmes.

**Comment by Gis70** [comment]
Serait il possible d'implémenter la commande du FAN2 (j'ai 2 ventilos et du coup le Fan2 reste toujours au mini à priori), secundo peux tu faire en sorte que l'on puisse envoyer 0 en vitesse de ventilo sur Fan1 & Fan2, tercio est ce possible d' implémenter la fonction noAir (flamme 1 & fan1 = 0 & fan2 =0) Je ne sais pas ce que tu as comme info concernant le fonctionnement du pilotage du poêle mais j'en ai pas mal en ma possession si tu en as besoin. Merci @+

**Comment by zoic21** [comment]
Bonjour,
Alors pour le fan2 il faut supprimer et refaire l'équipement je l'ai ajouté hier.
Pour le 0 je vais regarder sur les fan pour le noAir ça sera possible de le faire une fois le 0 la mais je ne ferais pas une commande pour ca.

**Comment by Gis70** [comment]
Bonjour, pas de soucis je gererai moi même le noAir. Ok je supprimerai l'équipement pour le remettre. Thx

**Comment by zoic21** [comment]
Voila j'ai poussé la correction pour les ventilos mais je suis pas sur que ca marche car d'après la doc la valeur pour les Fan va de 1 à 6 donc pas de 0

**Comment by Gis70** [comment]
Bonjour,

Effectivement, la commande 0 ne fonctionne pas et si la commande est sur 0 et que je demande un AUTO alors le poêle ne démarre non plus, j'imagine que les 0 rendent la trame invalide. Cependant j'ai un mode silence (SF) qui correspond au NOAIR mais à priori ça ne marche pas en mettant 0 sur les fans. Je vais tenter de me renseigner pour savoir si c'est une "trame" spéciale. Sinon serait il possible d'implémenter le choix ou non d'émettre les BIP à chaque commande ? Un bip pour le démarrage et l'arrêt c'est bien mais pour la gestion des ventilos et flammes c'est pénible. Cependant si on pouvait le mettre tout le temps dans un mode "debug" pour vérifier que le poêle acquitte bien les trames émisent... D'autre part, je n'ai plus rien dans le log RFXCOM en mode debug, normal ? Merci A+

**Comment by zoic21** [comment]
Bonjour,
J'ai remis de 1 à 6 pour les ventilo et ajouter les commandes pour activer ou non les bips (il faut comme pour la dernière fois supprimer et recréer l'équipement)
Pour la log non ce n'est pas normal j'ai testé chez moi et je l'ai bien donc je ne sais pas. Attention quand meme a chaque changement de niveau il faut relancer le démon.

**Comment by Gis70** [comment]
Super merci pour la réactivité. Bon c'est à cause du démon je ne l'ai
relancé.

**Comment by Gis70** [comment]
J'ai l'impression que mon log debug est aléatoire, j'ai réussi à l'avoir un moment et puis tout a été effacé et depuis je n'ai plus rien dedans malgré plusieurs relances du deamon. Le log réapparait en debug après un changement de protocoles à écouter (donc une relance auto du deamon) mais pas lorsque je le relance via le bouton play (le mode auto est activé).

Pour les commandes du poêle concernant les BIP ça ne marche pas. D'une manière générale la commande AUTO qui sert à démarrer le poêle fonctionne de façon aléatoire, je m'explique suivant ce qui a été laissé dans les ventilos ou flammes lors de la dernière fois qu'une action a été faite, la trame envoyée n'est pas valide (le poêle acquitte par un bip mais ne réagit pas => pas de démarrage, ça faisait ça quand 0 était en consigne des ventilos aussi) Je crois savoir que 6 sur les ventilos correspond à gestion AUTO, je pense que dans la trame envoyée pour le mode AUTO il faut absolument mettre le champ qui correspond aux ventilo à 6 (ou du moins différents de 0 ou 1) et envoyer la puissance de flamme à 1 (mini comme ça pas de pb de surchauffe lors de la sortie de la stratégie de démarrage du poêle)

Il y a un truc dérangeant aussi, c'est que si le poêle est en OFF et que je bouge les paramètres de la flamme ou des fans cela envoi une trame complète qui me fait démarrer le poêle, j'aimerais bien que ça ne soit pas possible lorsque le poêle est en OFF mais que éventuellement la valeur du paramètre soit prise en compte si je démarre en auto par la suite.

Pour les BIP, serait il possible de mettre un "check" pour pouvoir les activer ou pas (comme la fonction historiser par exemple) dans le champ BIP de la trame complète du mode - Auto - Off  / de la commande des fans / de la flamme ainsi on pourrait vraiment pouvoir gérer le BIP en fonction de l'action.

Je ne sais pas si j'ai été clair... N'hésites pas et si jamais il faut faire un point téléphonique pas de soucis... 
Je pense qu'on est pas loin de qqch de bien. Merci.

**Comment by zoic21** [comment]
Bonjour,
Pour le log je sais pas ya pas mal de gens qui me le remonte mais j'ai jamais eu le soucis donc pour l'instant pas d'investigation la dessus.
J'ai poussé une correction de bug après la j'ai vérifier la plupart des cas et les trames son conforme a la doc rfxcom donc si ca marche pas faut voir avec eux....
Pour le BIP par exemple la trame est bonne donc je ne sais pas si ca marche pas
Pour le soucis du cas off qui rallume le poêle en cas de demande c'est normal je ne peux rien y faire
Pour la coche ce n'est pas possible non plus c'est beaucoup trop de temps de dev pour le nombre d'utilisateurs réel et le besoin désolé.

**Comment by wilfrid76** [comment]
bonjour,
je cherche également a commander mon poêle MCZ avec raspberry pi3 sous jeedom avec un rfxtrx433e. Pour le moment j'arrive a commander le poêle avec le petit logiciel rfxmngr et j'ai réussi a capter ID de la télécommande ( 0x1C2302).
Sous jeedom, j'ai créé un équipement poêle mcz 2 fans a partir du plugin RFX ( version stable car en version beta mon rex n'est pas reconnu ), Que dois je renseigné comme ID et sous quelle forme ?( j'ai essayé 0x1C2302 ou 1C2302 comme plus haut dans le forum mais rien ne se passe
Quelle sont les ID de commande pour les commande on/off/auto/flamme.....
Merci pour vos éclairages

wilfrid

**Comment by Gis70** [comment]
Salut, pour ma part les poêles n'apparaissaient pas en stable et de toute façon si les évols n'ont pas été intégrées à la version stable ça ne marchera pas. Il faut que tu passes en Beta. J'ai un RFX433e comme toi et ça marche bien. L'ID doit être juste 1C2302 que tu dois renseigner dans ID sur la page principale de l'équipement. Ensuite tu dois juste cliquer sur les commandes du widget Auto ou OFF et régler les fans et flamme... Passe en MP sur le forum si tu as besoin d'aide (GiDOm) pour ne pas "polluer" l'issue.

**Comment by wilfrid76** [comment]
bonjour, je reviens vers vous suite à des difficultés pour commander mon poêle MCZ
les éléments pour comprendre:
- raspberry pi 3 sous jeedom en 2.4.6
- plugin RFX en version beta
création d'un équipement poêle mcz (version 2 fans )
lorsque j'exécute une commande via le widget, rien ne se passe. Par contre je vois bien dans le log du plugin la trame [2017-05-10 11:34:45][DEBUG] : Special function execCmd143 return  : 0C4302021C2302010505040000
Par rapport a la version du plugin que j avais avant la beta (version stable) je m interroge de voir aucune mention au niveau du démon, comme ci le celui ne tourner pas, est ce normal?
Et seconde observation, lorsque j'ai décodé le ID de la savonnette sous rfxmngr, celui ci m'a détecté le poêle en version 3 ventilos et l'équipement est en version 2 ventillos, donc est ce que la trame envoyée par jeedom est peut être different ( plus longue ) ?

merci de vos lumières

wilfrid

**Comment by Gis70** [comment]
Bonjour Loïc, Alcor_fr sur le forum a trouvé pourquoi les commandes sur les BIP ne fonctionnnaient pas, il faut les déplacer cf le code OK ci -après : 

`<?php
function execCmd143($_cmd, $_options) {


$eqLogic = $_cmd->getEqLogic();
$device_type = explode('::', $eqLogic->getConfiguration('device'));

$return = '0C43';
$return .= isset($device_type[1]) ? $device_type[1] : '00';
$return .= '02';
$return .= $eqLogic->getLogicalId();

if ($_cmd->getLogicalId() == 'bipon') {
$eqLogic->setCache('previousValueBip', '01');
return null;
}
if ($_cmd->getLogicalId() == 'bipoff') {
$eqLogic->setCache('previousValueBip', '00');
return null;
}

$return .= $eqLogic->getCache('previousValueBip', '01');
if ($_cmd->getLogicalId() == 'fan') {
$eqLogic->setCache('previousValueFan', '0' . $_options['slider']);
}
$return .= $eqLogic->getCache('previousValueFan', '01');

if ($_cmd->getLogicalId() == 'fan2') {
$eqLogic->setCache('previousValueFan2', '0' . $_options['slider']);
}
$return .= $eqLogic->getCache('previousValueFan2', '01');

if ($_cmd->getLogicalId() == 'flame') {
$eqLogic->setCache('previousValueFlame', '0' . $_options['slider']);
}
$return .= $eqLogic->getCache('previousValueFlame', '01');

if ($_cmd->getLogicalId() == 'off') {
$eqLogic->setCache('previousValueCommand', '00');
} else if ($_cmd->getLogicalId() == 'manual') {
$eqLogic->setCache('previousValueCommand', '01');
} else if ($_cmd->getLogicalId() == 'auto') {
$eqLogic->setCache('previousValueCommand', '02');
} else if ($_cmd->getLogicalId() == 'eco') {
$eqLogic->setCache('previousValueCommand', '03');
}
$return .= $eqLogic->getCache('previousValueCommand', '00');
$return .= '00';
return $return;
}
?>`

**Comment by zoic21** [comment]
Effectivement il y avait un petit bug, j'ai poussé la correction en stable, elle devrait etre dispo demain

**Comment by Gis70** [comment]
Merci

**Comment by Gis70** [comment]
Bonjour, serait il possible d'implémenter dans le menu déroulant les poêles à 3 ventilos ? Ils sont pilotables depuis le rfxmanager. Merci

**Comment by zoic21** [comment]
Bonjour,
Oui sans soucis il me faut juste une explication sur la construction de la trame pour 3 ventilos.
