### ISSUE TITLE
[WEATHER][UPDATE] Mode Images

### ISSUE THREAD

**Issue by PuNiSHeR374** [jeedom/issues#137]
Bonjour Loïc,

Je viens de faire un Pull Request d'une mise à jour pour la gestion du Mode Image pour le plugin.
Nous étions plusieurs à vouloir que cette option revienne, donc, il y a à peu près 2 semaines, j'ai commencer les modifs.

Le sujet du Forum avec la demande : 

https://www.jeedom.com/forum/viewtopic.php?f=60&t=736&hilit=plugin+m%C3%A9t%C3%A9o&start=1200#p391642

Le plugin fonctionne sans problème chez moi depuis 2 semaines, que ce soit sur Dashboard ou Mobile.

![weather](https://cloud.githubusercontent.com/assets/17704870/20268373/1eb3f558-aa7f-11e6-83f6-375adf16b597.png)

![weather2](https://cloud.githubusercontent.com/assets/17704870/20271040/aca98d46-aa89-11e6-8c6e-7b458c8b66b1.png)

Ce que j'ai fait : 

- Correction de la gestion du mode Images
- Ajout de PNG haute qualité
- Ajout de conditions météo pour plus de précision
- Ajout de template pour gestion du mode Image sur Dashboard et Mobile
- Refonte de la boussole

Quand tu auras l'occasion et si tu acceptes ma mise à jour, voudrais tu bien la pousser directement en mise à jour pour que les membres du forum puissent l'avoir ??

D'avance, Merci à toi.

**Comment by bbreton09** [comment]
La mise à jour du GIT d'aujourd'hui provoque une erreur 500 sur le plugin weather.
Le dashboard s’arrête de charger avec le bandeau "500 : Internal Server Error"
Coté log j'ai ça dans http.erreur. (Je précise que je suis en beta)

[Tue Nov 15 20:35:31.402625 2016] [:error] [pid 29262] [client 192.168.1.85:49467] PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC) in /var/www/html/plugins/weather/core/class/weather.class.php on line 158, referer: http://192.168.1.71/index.php?v=d&p=dashboard
[15-Nov-2016 20:36:12 Europe/Brussels] PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC) in /var/www/html/plugins/weather/core/class/weather.class.php on line 158
[Tue Nov 15 20:36:23.489082 2016] [:error] [pid 351] [client 192.168.1.85:49483] PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC) in /var/www/html/plugins/weather/core/class/weather.class.php on line 158, referer: http://192.168.1.71/index.php?v=d&p=dashboard

**Comment by PuNiSHeR374** [comment]
Ca fait 15 jours qu'il fonctionne chez moi, donc, ça va être dure de savoir d'où vient le problème.

**Comment by bbreton09** [comment]
Au vue du message il dit qu'il manque un truc autour de la ligne 158.
Je voudrais pas dire de connerie mais manquerais pas un } ligne 122  de weather.class.php ?

**Comment by PuNiSHeR374** [comment]
Je viens de regarder mon fichier de class et c'est bon, par contre sur mon github que je met à jour avec github desktop, lui à également l'erreur.

Je fais la correction directement et je lance un pull request.

Ben, merci, même si je ne sais pas vraiment d'où cela peut venir.
