### ISSUE TITLE
[APP MOBILE][BETA 1.1 (10)] Bug affichage écran favoris

### ISSUE THREAD

**Issue by magicgg91** [jeedom/issues#138]
Jeedom Core 3.0 maj 2016-11-15 11:00:00
Plugin App Mobile : 2016-10-26 01:05:08
Application version 1.1 (10)

Sur l'écran des favoris, pour les infos affichées, si je fais 1 appui dessus, j'ai de nouveau la proposition de configuration de l'emplacement, comme quand on clique sur 1 emplacement vide.

**Comment by rocket13011** [comment]
1.1.0 (13)

**Comment by magicgg91** [comment]
Correction confirmée
