### ISSUE TITLE
[APP][1.2] proposition d'amélioration appuis long favoris

### ISSUE THREAD

**Issue by phifi92** [jeedom/issues#139]
Jeedom Core : 3.0
Plugin App Mobile : 2016-10-26 01:05:08
Application version 1.1 BETA
Smartphone : iPhone 7 plus iOS 10.1.1

Lors d'un appuis long sur un favoris, et le choix modifier, je m'attendais à autre chose que de remplacer mon favoris (en choisissant le même choix, ou un autre choix. D'ailleurs, autant fait le choix supprimer). Ma vision, au moment du choix modidier, était plutôt d'arriver sur la page : personnalisation -> permettant de renommer, voir même de changer la couleur

**Comment by magicgg91** [comment]
Donc dans l'idéal, on aurait les choix Modifier (tel que décrit par phifi), Remplacer et Supprimer

**Comment by rocket13011** [comment]
A voir, mais oui ça serai plus rapide ;)

**Comment by Zouritte** [comment]
Peut être ajouter une option dans r menu pour déplacer le widget. Un peu comme on déplace une app sur le menu iPhone.

**Comment by rocket13011** [comment]
on part sur issue-app
