### ISSUE TITLE
[CORE][STABLE][2.4.6][SCENARIO] scéanario en erreur 

### ISSUE THREAD

**Issue by skyline-ch** [jeedom/issues#140]
Dans un scénario je vérifie la présence ou non d'un événement dans un calendrier google (plugin iCalandar)

j'utilise la fonction not, qui semble poser problème, comme ont peux le voir dans la capture la commande de l'agenda ne semble pas être replacée par la valeur, ont vois le #1007#

Hors comme ont peux le voir sur la capture 2 avec le testeur d'expression j'ai bien les bonnes valeur et le résultat attendu.

![capture du 2016-11-15 20-18-01](https://cloud.githubusercontent.com/assets/13089438/20323005/072c4648-ab73-11e6-8666-47489b1d931d.png)
![capture du 2016-11-15 20-17-45](https://cloud.githubusercontent.com/assets/13089438/20323020/167a782c-ab73-11e6-92bc-bc68b319ab10.png)

export du scénario : 

> 
- Nom du scénario : Mode Maison
- Mode du scénario : provoke
    - Evènement : #[Maison][Mode Maison][Statu]#
    - Evènement : #[Technique][Calandrier Travail][Michael]#

    SI #[Maison][Mode Maison][Statu]# !=  variable(Mode_maison_actif, 0)
    ALORS
     (sleep) Pause de  : 15
         
        SI #[Maison][Mode Maison][Statu]# !=  variable(Mode_maison_actif, 0)
        ALORS
             
            SI #[Maison][Mode Maison][Statu]# == "Présence"  
            ALORS
             #[Salon][Écran PC][On]# - Options : Array
            (
                [enable] => 1
            )
            
            SINON
                 
                SI (#[Maison][Mode Maison][Statu]# == "Dodo"  OU #[Maison][Mode Maison][Statu]# == "Autonome" OU #[Maison][Mode Maison][Statu]# == "Vacance" )  &&  not(#[Technique][Calandrier Travail][Michael]# matches "/A;Vacance-congé-indisponible/")
                ALORS
                     
                    ACTION
                         
                        SI #[Maison][Mode Maison][Statu]# == "Autonome"
                        ALORS
                             
                            SI #[Salle de bain][Wall Plug][Etat]# == 0  
                            ALORS
                             (scenario) deactivate de [Sécurité][Présence Maison (En Vacance)]
                             #[Salle de bain][Wall Plug][On]# - Options : Array
                            (
                                [enable] => 1
                            )
                            
                            SINON
                        SINON
                         
                        SI #[Maison][Mode Maison][Statu]# == "Dodo"
                        ALORS
                        SINON
                         
                        comment
                             
                            SI #[Maison][Mode Maison][Statu]# == "Vacance"  
                            ALORS
                            SINON
                     #[Salon][Harmony hub][PowerOff]# - Options : Array
                    (
                        [enable] => 1
                    )
                    
                     #[Maison][Toutes les lumière Maison][Off]# - Options : Array
                    (
                        [enable] => 1
                    )
                    
                     #[Salon][Écran PC][Off]# - Options : Array
                    (
                        [enable] => 1
                    )
                SINON
                     
                    SI #[Maison][Mode Maison][Statu]# == "Vacance" ET #[Technique][Calandrier Travail][Michael]# matches "/A;Vacance-congé-indisponible/"
                    ALORS
                     #[Salle de bain][Wall Plug][Off]# - Options : Array
                    (
                        [enable] => 1
                    )
                    
                     (scenario) activate de [Sécurité][Présence Maison (En Vacance)]
                    SINON
                     #[Maison][Mode Maison][Vacance]# - Options : Array
                    (
                        [enable] => 1
                    )
                    
                     (scenario) stop de [Automatisation][Mode Maison]
             
            comment
         #[Technique][Pushbullet Prod][OnePlus 3]# - Options : Array
        (
            [enable] => 1
            [title] => Mode maison
            [message] => Maison en mode #[Maison][Mode Maison][Statu]# #heure#h#minute#
        )
        
         #[Technique][Pushbullet Prod][HTC HTC One]# - Options : Array
        (
            [enable] => 0
            [title] => Mode maison
            [message] => Maison en mode #[Maison][Mode Maison][Statu]# #heure#h#minute#
        )
        
         (variable) Affectation de la variable : Mode_maison_actif à #66#
         #[Technique][Jeedom Dev][Mode Maison]# - Options : Array
        (
            [enable] => 1
        )
        
        SINON
    SINON

**Comment by zoic21** [comment]
Bonjour,
Je n'arrive pas a reproduire pour moi le soucis ne vient pas de jeedom sans pour autant que je puisse dire d'ou ca vient.

**Comment by skyline-ch** [comment]
OK,  il semblerait que le même scénario sur la bêta pose pas se problème.
