### ISSUE TITLE
[APP][1.1]Impossible changer une couleur sur un RGB

### ISSUE THREAD

**Issue by mamatdv** [jeedom/issues#141]
IOS 10.1.1 sur iPhone 6S Plus
Je viens de constater un bug  
quand tu essai de changer une couleur sur un rgb (fgrgb101 zwave par exemple) ca tourne sur changement de la couleur ... et rien ne se passe finalement
J'avais constaté le même problème sur milight et je croyais que le problème venait du plugin wifilight mais finalement non
 Autre bug : J'ai remarquer aussi que quand t'appui sur l'ampoule pas de on/off, par contre en baissant le slide a fond c'est ok
bref c'est le meme bug que le slider sur les lampes classique

**Comment by rocket13011** [comment]
et quand tu fait juste un clique sur la couleur sans la faire Slider ? ça donne quoi ?

**Comment by rocket13011** [comment]
Fonctionne ou pas ?

**Comment by rocket13011** [comment]
Résolu
