### ISSUE TITLE
[APP MOBILE][BETA] problème Light invertbinary 

### ISSUE THREAD

**Issue by magicgg91** [jeedom/issues#142]
- Jeedom bêta 18/11/2016 18h
- Plugin App Mobile bêta 2016-10-26 01:05:08

Virtuel ON/OFF/STATUS
ON 0
OFF 1
STATUT INVERSER à oui
Tous les widgets en version core
![invert](https://cloud.githubusercontent.com/assets/16479933/20456113/ce0610b2-ae6d-11e6-8da2-28c4957b21ee.JPG)

dans l'application, le invert n'est pas pris en compte.

ON sur dashboard (état normal) => apparait en OFF sur l'appli

**Comment by cedric222** [comment]
Pour information il n'y a pas le même probleme avec le type generique "fenetre", par exemple le status INVERSER est bien pris en compte.

**Comment by rocket13011** [comment]
a tester sur la 1.1.0 (15)

**Comment by magicgg91** [comment]
OK pour moi

**Comment by magicgg91** [comment]
Alors OK mais l'info est fausse dans le résumé domotique de la pièce et global dans l'application

J'ai 2 lampes dans la pièce, si les 2 sont éteintes, elle apparaissent bien éteintes, mais j'ai 1/2 dans le résumé de la pièce. Si j'allume celle avec le inverse binary, j'ai 0/2.
