### ISSUE TITLE
[CORE] données en cache avant écriture en db toutes les 5 minutes

### ISSUE THREAD

**Issue by LoloVTS** [jeedom/issues#143]
Bonjour,

Je ne sais pas si le sujet à déjà été abordé, mais serait-il envisageable et faisable de stocker les données dans le cache avant de les stocker en base de données. Avec le cache en tmpfs et en regroupant les requêtes dans une transaction toutes les 5 minutes cela optimiserait les écritures (surtout pour les stockages à base de NAND) et limiterait la perte éventuelle de donnée aux 5 dernières minutes.

Cordialement

**Comment by zoic21** [comment]
Bonjour,
Cela est trop compliqué et amènerai beaucoup d'instabilité, la version 2.4 et encore plus la 3.0 sont de plus en plus accès sur les cache pour les données non vital (perte accepté de 30min).
