### ISSUE TITLE
[code][deprecated] mot clé réservé object

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#144]
Le mot clé object est réservé pour **php 7** et ne peux pas être utilisé pour nommer une class core/core/class/object.class.php. Je suggère d'utiliser ObjectCore à la place comme nom.

**Comment by zoic21** [comment]
Salut,
Ok j'en prends note mais pour avoir testé en php7 pas de soucis de fonctionnement. La modification étant très lourde et touchant tous les plugins...
