### ISSUE TITLE
[PLUGIN-GEOLOC] Ajout option trajet mode de déplacement

### ISSUE THREAD

**Issue by coolweb** [jeedom/issues#145]
Il serait interressant d'ajouter l'option pour les trajets pour choisir le mode de déplacement par exemple en train.

Merci.

**Comment by zoic21** [comment]
Bonjour,
C'est a dire ? Le plugin ne calcul pas de trajet ou autre juste la distance entre 2 points....

**Comment by coolweb** [comment]
Il y a l'option pour avoir la distance à la volée mais également le trajet qui par défaut se fait en voiture (il y a même l'option pour ignorer les autoroutes). Il y a les commandes temps de trajet et distance de trajet.

**Comment by zoic21** [comment]
A oui ca utilise google mais j'ai pas d'option pour avoir autrement que en voiture malheureusement, la sncf n'a pas d'api je ne peux donc rien faire.

**Comment by coolweb** [comment]
Il y a l'option sur google maps pour les trajets au dessus voiture, à train, à pied, vélo. Google maps tient compte automatiquement de la sncf en france et sncb en belgique....

**Comment by magicgg91** [comment]
Je dirais qu'il y a le plugin Google Maps Direction pour ça

**Comment by zoic21** [comment]
Si dans l'api il y a ce qu'il faut hésites pas a faire un fork et proposer un pull request nous verrons pour l’intégrer officiellement dans le plugin

**Comment by coolweb** [comment]
Je viens de regarder dans le plugin Google Maps Direction, il n'y pas non plus l'option pour le mode de déplacement, sinon il s'agit juste d'un flag à ajouter dans l'Api Google Maps.
