### ISSUE TITLE
Qualité du code

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#146]
Salut,
J'ai passé le dépot du core de jeedom sur sensiolab insight https://insight.sensiolabs.com. C'est un analyseur statique de code gratuit quand le code est open source.
le résultat montre des problèmes mais rien de rédhibitoire.
Peut-être serait il possible de faire une pause dans le dev de fonctionnalité pour se concentrer sur la qualité du code et le respect des standards de dev.

j’attends votre avis. 

ps : voici les résultat pour le core :

Severity
41 Critical
218 Major
602 Minor
133 Info
Attention la majorité des criticals concerne le script d’installation de jeedom et ce script n'est utilisé qu'une fois.

**Comment by zoic21** [comment]
Bonjour,
Je suis au courant malheureusement nous n'avons pas le temps ni les ressources pour corrigé cela. De plus personnellement je ne suis pas trop pour ce genre de correction c'est plus un faire valoir qu'un réel plus pour le code. En plus ca apporte des modifications qui apporterons leur lots de bugs.
