### ISSUE TITLE
[CORE][BETA] methode empty

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#147]
`public static function deleteObjet($_update) 
{
	
}
`
This method is empty in  core/core/repo/github.repo.php
if it's deprecated add this: 

trigger_error("Deprecated function called.", E_USER_NOTICE);

**Comment by zoic21** [comment]
Si si c'est normal car pour github ya rien a faire la c'est pas le cas pour tous les dépôts.
