### ISSUE TITLE
[APP] raccourcis vers certaines pièces dans l'accueil de l'app mobile

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#149]
Ce serait super pratique dans l'application mobile de mettre sur l'accueil des raccourcis vers certaines pièces (surtout lorsque l'on en a beaucoup).

Merci
Thomas
PS : Non je n'habite pas un château.

**Comment by rocket13011** [comment]
A voir, car les pieces sont déjà pas mal prêt, mais je vais voir ça ^^

**Comment by rocket13011** [comment]
Pris en compte dans une prochaine Roadmap (interne) je clos
