### ISSUE TITLE
 [CORE][BETA 2016-06-22 12:18:28] Problème lors de la création d'un virtuel.   

### ISSUE THREAD

**Issue by ZitouneOlivier** [jeedom/issues#15]
je sais pas si c'est normal, mais lors que l'on ajoute un Vituel, celui-ci remonte seul sur le design par défaut

**Comment by ZitouneOlivier** [comment]
Explication : 
- Je créé un nouveau Virtuel. Je le sauvegarde.
- J'affiche mon design par défaut, et hop mon nouveau Virtuel est sur ce design, sans rien faire :-)

**Comment by zoic21** [comment]
Non ce n'est pas normal et je vois même pas comment c'est possible, le probleme est-il présent sur tout les design ? Ce design est-il vieux ? Si ce design est supprimé puis recréer le probleme se reproduit-il ?

**Comment by ZitouneOlivier** [comment]
Present uniquement sur le design par defaut de l'utilisateur.
Design qui doit avoir un mois.
Pour la suppression je vais tenter...

**Comment by ZitouneOlivier** [comment]
Avant je met a jour, car je vois que la version du core est d'hier...

**Comment by ZitouneOlivier** [comment]
En fait pour avoir le cas il faut avoir un onglet ouvert sur le design, puis ouvrir un autre onglet et allez dans les virtuels et en créer un, une fois enregistrer celui-ci arrive ds le design tous seul comme un grand :-)

**Comment by ZitouneOlivier** [comment]
Suite à Maj en [BETA 2016-06-23 12:03:54], et fermeture chrome et réouverture, je n'arrive plus a reproduire le cas....
Donc je sais pas si ça viens de la version ou du navigateur... Je vais tester sur la production qui en [Beta 2016-06-22 14:31:16 ] donc version pas très lointaine..

**Comment by ZitouneOlivier** [comment]
Je n'arrive pas a reproduire, donc je sais pas... un problème du navigateur ou une version intermédiaire, pourtant ce matin, j'ai réussi a reproduire le truc 5 ou 6 fois en recréant a chaque fois des nouveaux virtuel, ils arrivaient tous au fur et a mesure sur mon design. Et chose encore plus surprenante, ils arrivaient en gris de base (sans mise en forme) et étaient pas systématiquement au même endroits sur le design... Je vais surveiller ça

**Comment by zoic21** [comment]
La je vais avoir du mal a trouver, je ferme et si ca revient je reouvrirais
