### ISSUE TITLE
[virtual] Perte de la valeur après un reboot

### ISSUE THREAD

**Issue by colas31** [jeedom/issues#150]
Bonjour, 

Jeedom : v2.4.6
Virtual : 2016-10-14 01:05:40

Actuellement la valeur d'un cmd de type Info (binaire) d'un virtual  peut être changé via un cmd de type action.
Sauf qu'après un reboot du serveur par exemple, la valeur de cette cmd n'est pas conservé et reprends une valeur de 0.
Le top serait qu'après un reboot du serveur cette ancienne valeur soit conservée.

Merci ;)

**Comment by zoic21** [comment]
Bonjour,
Suite a un reboot il faut attendre 5min avant de retrouver les valeurs des commandes (restoration du cache).
Si ca n'a marche pas c'est qu'il y a un soucis avec votre jeedom et la sauvegarde/restauration du cache.

**Comment by colas31** [comment]
En effet, mon user www-data, ne semble pas avoir assez de droit sudo. Suite à une ancienne conversation ensemble j'avais adapté les droit sudo pour cet user.
Est ce que si je fais une passe sur le code pour supprimer toutes les commande sudo dans le "core" pour le pusher te convient ou pas ? Je demande avant pour pas bosser pour rien ;)

Merci

**Comment by zoic21** [comment]
Non ce n'est pas possible je sais que ca gene beaucoup de monde ces droits sudo mais je n'accepterais aucun changement a ce niveau c'est vraiment un point essentiel dans jeedom et il ne fonctionne pas sans.

**Comment by colas31** [comment]
Entendu, merci pour le retour
