### ISSUE TITLE
[APP MOBILE] gestion centralisation du paramétrage de l'app

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#152]
Bonjour,

Lorsque je dois modifier le paramétrage de l'app mobile de ma femme, ce n'est pas waf, je dois lui emprunter, modifier, vérifier, ...
Ce serait bien. De pouvoir modifier le paramétrage sur jeedom et l'envoyer sur un mobile.
Pareil, j'ai une téléphone et une tablette donc 2 paramétrage identique que je dois maintenir a la main. Pas très pratique.

À+
Thomas

**Comment by rocket13011** [comment]
ça arrivera, mais pour le moment pas dans les plans les plus proche de l'app ;)

**Comment by rocket13011** [comment]
je ferme car arrivera dans la roadmap
