### ISSUE TITLE
[CORE][BETA][3.0.1][DESIGN] Pb de grille

### ISSUE THREAD

**Issue by stephaneSBO** [jeedom/issues#153]
Le problème est reproduit par plusieurs BT. 

A la création d'un nouveau design ou à l'édition d'un design existant, la grille est fixe à 500x500 quelle que soit la taille définie du design cible. Cela ne pose pas de problème pour un design inférieur à cette résolution. Par contre pour des designs de tailles supérieurs (c'est souvent le cas des résolutions tablettes, PC et même smartphone), le positionnement au dela de la grille est impossible avec le glissé/déplacé de la souris. 

Pour reproduire : "Creer un design", "Configurer le design", "Taille (LxH) : 1024 x 1024", "Edition", "Affichage 20x20", "Ajouter une zone", "Etendre la zone à la taille de la grille", "constater que la zone est de 500x500".
En ajoutant un équipement, le glissé ne permet pas de descendre en dessous de la grille. Avec "Paramètre d'affichage", "Position X (%)" et/ou "Position Y (%)" il est possible de positionner en dehors de la grille, mais le positionnement en % ne semble pas être correct.

Est'il possible de : 
- adapter la grille à la taille du design ?
- si ce n'est pas le cas, avoir une grille beaucoup plus grande 2048 x 2048 ce qui permettrait de débloquer la situation.
- harmoniser les largeur/hauteur. Dans la configuration du design c'est LxH et dans les équipements c'est HxL. Il serait plus logique d'avoir LxH partout, car cela perturbe. :) 
- Le positionnement en pixel plus qu'en % serait plus pratique.

<img width="1027" alt="capture d ecran 2" src="https://cloud.githubusercontent.com/assets/10259991/21455064/a0ebc246-c91d-11e6-9e37-497640e0e990.png">

Rien d'urgent.

**Comment by stephaneSBO** [comment]
La configuration dans le fichier planHeader.class.php d'une valeur 1024 par ex dans les variables desktopSizeX et desktopSizeY permet d'obtenir une grille adaptée. Par contre l'augmentation au dela de cette valeur peut engendrer le besoin de dézoomer fortement pour récupérer le menu clic droit qui doit être fait en dehors de cette grille.

Cette valeur à 500 est positionnée, car le getConfiguration('desktopSizeX) retourne toujours 'néant'.

Loïc, si le clic droit est envisageable sur la grille et pas forcement en dehors cela permettrait de mettre une grille de taille importante sans impact.

```
public function preInsert() {
		if ($this->getConfiguration('desktopSizeX') == '') {
			$this->setConfiguration('desktopSizeX', 1024);
		}
		if ($this->getConfiguration('desktopSizeY') == '') {
			$this->setConfiguration('desktopSizeY', 1024);
		}
	}

```

**Comment by stephaneSBO** [comment]
Un complément, la table planHeader : 
<img width="848" alt="capture d ecran 9" src="https://cloud.githubusercontent.com/assets/10259991/21545022/5f57e632-cdd4-11e6-9662-8a576f58cb3d.png">

**Comment by zoic21** [comment]
Bonjour,
Je viens de tester et je ne vois pas de soucis, j'ai créer un design vide, puis en mode édition ajouter une grille celle-ci a bien la taille attendu de 500x500 c'est à dire la taille par défaut d'un design vide, la grille remplis donc bien tous le design.

J'ai corrigé l'inversion LxH

**Comment by stephaneSBO** [comment]
Loic
Avec la taille par défaut à 500x500 effectivement pas de pb, c'est justement pour une taille différente
