### ISSUE TITLE
[PLUGIN][MOBILE] Pièce avec apostrophe

### ISSUE THREAD

**Issue by hrenaud** [jeedom/issues#154]
Bonjour,

Lorsqu'une pièce est créé avec un apostrophe " ' ", dans le plugin Mobile, on ne peut cliquer dessus pour ouvrir sa configuration, supprimer l'apostrophe résout le problème.

* Version du plugin App Mobile (mobile) - stable : 2016-12-23 14:15:33
* Version Jeedom : 2.3

**Comment by rocket13011** [comment]
réglé dans la prochaine beta du plugin
