### ISSUE TITLE
[APP][1.2] Bugs affichages dans les paramètres

### ISSUE THREAD

**Issue by mrzac** [jeedom/issues#155]
Android 6.0.1 / One Plus 3

Dans la pages des paramètres : 
- le mot "Confirmer" dans le bouton en face de "Confirmer les liens" et "Nettoyer le cache" est sur 2 lignes ;
- la ligne version du plugin n'apparait pas. Uniquement une date;

![photo531798822367635466](https://cloud.githubusercontent.com/assets/393649/21525366/2f2809e0-cd1d-11e6-978d-f7b08d29d3f8.jpg)

**Comment by rocket13011** [comment]
Normalement Résolu
