### ISSUE TITLE
 [CORE][BETA][2.4.6][Update] Les notifications d'update

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#156]
Bonjour,

Dans les notifications d'uptate on retrouve quand même les plugins pour lesquels la case "Ne pas mettre à jour" est coché. C'est domage.

A+
Thomas

**Comment by zoic21** [comment]
Bonjour,
Je n'arrive pas a reproduire en 3.0 je considère donc cela resolu.

**Comment by guenneguezt** [comment]
Effective je ne suis pas en version 3.0
