### ISSUE TITLE
[plugin-mode] Pas de valeur de #state# dans les commandes

### ISSUE THREAD

**Issue by Tijojo** [jeedom/issues#157]
Version Jeedom : 2.4.6 (sur RPI3)
Version plugin-mode : 1.210

Je souhaite personnaliser les widgets sur le plugin mode.
Malheureusement, mon widget utilise la valeur #state# qui n'est pas renseigné (pas de lien vers l'info d'état si j'ai bien compris).

![capture](https://cloud.githubusercontent.com/assets/3288135/21540695/4a256cb2-cdb1-11e6-8e7e-074b6f1c285d.PNG)

Je pense qu'il faudrait rajouter ce lien pour être cohérent avec les commandes produites par le plugin virtuel par exemple.

Merci d'avance.

**Comment by zoic21** [comment]
Bonjour,
Pas sur de comprendre mais une commande de type action n'a pas de state c'est tout à fait normal une commande de type action ne porte par définition aucune infos
