### ISSUE TITLE
[APP][1.2] IOS ToutchID empêche la synchro auto

### ISSUE THREAD

**Issue by stephaneSBO** [jeedom/issues#158]
L'activation de la fonction IOS ToutchID empêche de sauvegarder le mise synchronisation automatique. De mon coté j'ai constaté que la synchronisation n'était impactée qu'en URL externe, mais d'autres BT auraient le problème en url interne aussi.
La désactivation du ToutchID permet de mettre la synchronisation automatique sans problème.

**Comment by chrislam86** [comment]
Problème sur URL interne chez moi. 
ios 10.2.1

**Comment by stephaneSBO** [comment]
Testé en 1.2 beta, lors du passage en TouchID, la synchronisation auto est ok. Par contre en quittant l'application (kick) et la relancent la synchronisation repasse en manuel.

**Comment by phifi92** [comment]
En phase concernant le bug avec sbo. Et vu de ma fenêtre, on voit 2 synchros lancés en //, avec un petit décalage, et la 2ème synchro doit certainement tomber en échec, provoquant une bascule en manuel. Vu un iPhone et iPad mini

**Comment by stephaneSBO** [comment]
Pour complément 
![img_0536](https://cloud.githubusercontent.com/assets/10259991/22042271/ae4cd12c-dd0a-11e6-87e3-d896e6418ad1.PNG)

**Comment by phifi92** [comment]
Petit retour rapide.
Correction pas complète. Plus de lancement de plusieurs synchro en // provoquant une synchro KO. Mais un pb est encore d'actualité avec le touch ID, bascule systématiquement en manuel : manuel désactivé, activation de Touch ID, kill app, relance (pas de multi-synchro, mais bascule en manuel). Même en re-désactivant la synchro manuel, re-kill app, idem -> bascule en manuel. On voit bien que la synchro manuel est activé juste après le touch ID (avant/au moment des notifications synchro en cours etc...)

**Comment by phifi92** [comment]
Derrière version de ce jour : OK pour moi en Wi-Fi et 4G. Pour moi on peut clore le bug.
Malgré qu'il reste un petit défaut qui n'est pas suffisamment impactant pour une prise en compte. Si je fais un double clic bouton home (pour basculer sur une autre application : multi-tache), à ce moment là, l'app bascule en manuel. Et si on revient sur l'app mobile aussitôt, sans basculer sur une autre app, je reste en manuel.
Pas très grave je trouve, usage surement très rare.
