### ISSUE TITLE
[PLUGIN MOBILE] erreur php

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#159]
Bonjour,

Le plugin mobile sort des erreurs régulièrement dans la log.
[Sun Jan 01 19:18:20.358352 2017] [:error] [pid 104268] [client 192.168.1.10:47294] PHP Notice:  Undefined index: actionCodeAccess in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 291
[Sun Jan 01 19:18:20.358368 2017] [:error] [pid 104268] [client 192.168.1.10:47294] PHP Notice:  Undefined index: actionConfirm in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 292
[Sun Jan 01 19:18:20.358376 2017] [:error] [pid 104268] [client 192.168.1.10:47294] PHP Notice:  Undefined index: title_disable in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 296
[Sun Jan 01 19:18:20.358383 2017] [:error] [pid 104268] [client 192.168.1.10:47294] PHP Notice:  Undefined index: title_placeholder in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 297
[Sun Jan 01 19:18:20.358390 2017] [:error] [pid 104268] [client 192.168.1.10:47294] PHP Notice:  Undefined index: message_placeholder in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 298
Etant donné que les sources ne sont pas publiés, impossible de proposer de correction.

A+
Thomas

**Comment by rocket13011** [comment]
Maj effectué dans nouvelle Beta Du plugin. plus d'erreur dans les logs http ou nginx
