### ISSUE TITLE
[CORE][BETA] Ajout/suppression des "Paramètres optionnels widget" non fonctionnels depuis un PLAN

### ISSUE THREAD

**Issue by abarrau** [jeedom/issues#160]
Bonjour, 

Lors de l'édition du commande appelée depuis le mode plan, les boutons "ajouter" et "supprimer" des Paramètres optionnels widget au niveau d'une commande ne fonctionne pas (alors qu'ils sont fonctionnels lorsque l'on passage par la commande via l'écran de l'équipement). 

Procédure: 
- depuis un plan en édition, clic sur un équipement, et faire "configuration avancée"
- sur la fenêtre de l'équipement, choisir une commande (roue crantée)
- sur la fenêtre de configuration de la commande, aller sur "affichage avancée". 
-- les 2 boutons ne réagissent pas.

![capture d ecran 2017-01-02 a 09 26 23](https://cloud.githubusercontent.com/assets/13674762/21586250/0c86cb5a-d0cf-11e6-9d3c-e3ed0d23ce0f.png)

Les autres boutons de la fenêtre sont opérants. 

Version Jeedom : 3.0.1 ; dernier update le 29/12. 

Cdt,
Aurélien

**Comment by zoic21** [comment]
Bonjour,
Merci du retour c'est corrigé

**Comment by abarrau** [comment]
Bjr, Après test : 
- bouton "ajouté" : ok
- bouton "supprimé" : KO

En version 3.0.3 ; dernier update le 17/01.

Cdt,
Aurélien

**Comment by zoic21** [comment]
C'est corrigé

**Comment by abarrau** [comment]
ok, correction testée et validée. 
(version 3.0.3, update du 22/01/17)
