### ISSUE TITLE
[HUE][BETA] Bootstrap Switch restant dans le plugin

### ISSUE THREAD

**Issue by mamatdv** [jeedom/issues#161]
Suite à l'installation plugin hue en beta, lors du lancement du plugin on a droit à l'engrenage qui tourne en continu.
Je pense que c'est du à un bootstrapswitch qui reste dans le code.

Le F12 montre bien le message sur le bootstrapswitch.

**Comment by zoic21** [comment]
Bonjour,
Le plugin sera bientôt revu pour intégrer les nouveaux éléments hue, l'interface sera corrigé à ce moment la.
Merci pour le retour
