### ISSUE TITLE
Fautes de grammaire dans les conseils de soumission de bogue

### ISSUE THREAD

**Issue by eliovir** [jeedom/issues#162]
Bonjour,

Je voulais soumettre un [bogue](https://github.com/jeedom/issues/issues/164) sur le composant CORE, mais finalement je vais soumettre des corrections sur le texte des conseils de soumission de bogue ;)

(les corrections sont **en gras**)

> IMPORTANT : consigne pour que votre soumission ne soit pas refusé**e**. Si vous ne respecte**z** pas tous les points votre demande sera fermée immédiatement.
>
> TITRE : merci de le nommer comme cela [COMPOSANT] Titre. Exemple [RFXCOM] Mon titre, ou pour jeedom lui m**ê**me [CORE] Mon titre. ATTENTION si vous **ê**tes beta testeur merci de rajouter [BETA] dans le titre : [RFXCOM][BETA] Mon titre
>
> MESSAGE : merci de bien mettre toutes les informa**ti**ons suivantes :
> - la version de jeedom (si c'est une b**ê**ta la date de dernière mise à jour)
> - la liste des plugins ainsi que leur date de mise à jour
> - le log nginx.error ou http.error
> - une capture d'écran
> - si c'est un soucis sur l'interface faire F12 puis console et fournir le r**é**sultat

**Comment by zoic21** [comment]
Bonjour,
Ou se trouve ce texte ? je ne le trouve pas...

**Comment by zoic21** [comment]
J'ai trouvé c'est bon et corrigé
