### ISSUE TITLE
[CORE] « Ajout depuis le Mark »

### ISSUE THREAD

**Issue by eliovir** [jeedom/issues#163]
Lorsque l'on clique sur `Plugins`/`Gestion des plugins`, il y a un bouton `Ajout depuis le Market` qui s'affiche `Ajout depuis le Mark` - problème de longueur de texte - Cf. ![la capture d'écran](https://cloud.githubusercontent.com/assets/1446942/21610278/495a83e8-d1c7-11e6-9f75-34676ab051db.png).

**Comment by gui59169** [comment]
effectivement mais pas gênant franchement.... 👍

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour, ca sera corrigé en 3.0
