### ISSUE TITLE
[CORE] Market ou Store

### ISSUE THREAD

**Issue by eliovir** [jeedom/issues#164]
Lorsque l'on clique sur `Plugins`/`Gestion des plugins`, il y a un bouton `Ajout depuis le Market` (qui s'affiche d'ailleurs `Ajout depuis le Mark`, mais c'est une [autre histoire](https://github.com/jeedom/issues/issues/163)).

La boîte de dialogue modale qui s'ouvre s'intitule `Store`. Ce n'est pas cohérent.

Je me suis dit que je pourrais le corriger moi-même [ici](https://github.com/jeedom/core/blob/beta/desktop/js/plugin.js#L351) et [là](https://github.com/jeedom/core/blob/beta/core/i18n/fr_FR.json#L589) et soumettre une modif de code... mais Store semble être compris comme un synonyme de Volet dans les différentes traductions (ex. [en espagnol](https://github.com/jeedom/core/blob/beta/core/i18n/es_ES.json#L589) : `Persiana`).

Du coup, l'équipe Jeedom doit choisir quel terme utiliser et demander des corrections de traduction.

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour la correction sera disponible en Jeedom 3.0
