### ISSUE TITLE
[CORE] Erreurs d'orthographes corrigées mais qui apparaissent quand même

### ISSUE THREAD

**Issue by DenisPac** [jeedom/issues#165]
Bonjour cher support,

Je suis sur VM ESXi et Jeedom en version 2.4.6 avec un Jeedom mini déporté avec Razberry.
J'ai une belle liste de plugins dont certains sont encore en beta (depuis longtemps car il me semble les avoir tous passer en stable quand la beta est devenue fermée), mais là n'est pas le problème.

J'ai remonté le problème sur le forum (https://www.jeedom.com/forum/viewtopic.php?f=58&t=16102&view=unread#p419530) avec qui j'ai eu quelques échanges avec magicgg91 mais sans succès.
Ci-dessous ces échanges :
Re: Orthographe

**Message par DenisPac » Hier, 22:34**
Bon je ne sais pas trop où poster cette question mais comme elle est relative à l'orthographe, ce sujet me parait adapté :)
S'il y a un sujet plus adapté, merci aux modérateurs de déplacer mon message.

Après un long moment d'abstinence de participation active, notamment aux corrections orthographiques (je me débrouille mieux en français qu'en php !), j'ai voulu corriger des fautes trouvées notamment dans les logs. C'est le plus souvent des accents manquants.
Exemple :

Code : Tout sélectionner
    Start : Scenario execute automatiquement sur evenement venant de :

qui devrait être corrigé en

Code : Tout sélectionner
    Start : Scénario exécuté automatiquement sur évènement venant de :

Peu de chose certains penseront, mais bon ça pique les yeux de certains (dont moi).
Mais je ne veux pas critiquer gratuitement si je peux faire quelque chose.
J'ai donc récupéré une archive core-stable de Github puisque je suis sur la dernière stable 2.4.6 et j'ai cherché la chaine de caractères à corriger.
Et je n'ai rien trouvé.
Pour cause elle a déjà été corrigée (peut-être par moi :o).
J'ai trouvé des occurrences dans les fichiers suivants :
core-stable\core\class\scenario.class.php
core-stable\core\i18n\fr_FR.json
mais pas de trace de la chaine avant correction.
Comment ça se fait ?
J'ai loupé quelque chose dans l'utilisation de Github ?

**Message par DenisPac » Hier, 22:54**
Bon je suis allé voir ce que j'ai sur la VM Jeedom et en recherchant en ligne de commande la chaine erronée j'ai ceci :

Code : Tout sélectionner
    denis@Debian:/var/www/html$ grep -lR "Scenario execute automatiquement sur evenement" *
    log/scenarioLog/scenario50.log
    log/scenarioLog/scenario10.log
    log/scenarioLog/scenario34.log
    log/scenarioLog/scenario51.log
    log/scenarioLog/scenario53.log
    log/scenarioLog/scenario49.log
    log/scenarioLog/scenario47.log
    log/scenarioLog/scenario48.log
    log/scenarioLog/scenario33.log
    log/scenarioLog/scenario54.log
    log/scenarioLog/scenario40.log
    denis@Debian:/var/www/html$

Ca signifie qu'on la trouve uniquement dans les logs.
Je ne vois pas d'où elle peut bien venir...

**Message par magicgg91 » Hier, 23:02**
Hello,
Ca doit venir de l'encodage des fichiers quand ils sont enregistrés.
Enfin c'est 1 piste

**par DenisPac » Hier, 23:06**
Ça n'a pas l'air d'être ça.
Les fichiers sont encodés en UTF-8 et les caractères accentués apparaissent bien.

**Message par magicgg91 » Hier, 23:09**
Je pensais plus au moment de l'écriture des fichiers de log

**Message par DenisPac » Hier, 23:14**
Pas vraiment puisqu'on trouve des caractères accentués ailleurs dans le log :

Code : Tout sélectionner
    [2017-01-03 21:51:48][SCENARIO] Affectation de la variable b_piCorePlayer => 1 = 1
    [2017-01-03 21:51:48][SCENARIO] Exécution d'un bloc élément : 88
    [2017-01-03 21:51:49][SCENARIO] Tâche : 88 programmé à : 2017-01-03 22:16:00 (+ 25 min)
    [2017-01-03 21:51:49][SCENARIO] Fin correcte du scénario
    ------------------------------------
    [2017-01-03 21:53:03][SCENARIO] Start : Scenario execute automatiquement sur evenement venant de : [Salle de bain RDC][DS Kleenex][button]. Tags : Array
    (
    )
    [2017-01-03 21:53:03][SCENARIO] Exécution du sous-élément de type [condition] : if
    [2017-01-03 21:53:03][SCENARIO] Evaluation de la condition : [1] = 1
    [2017-01-03 21:53:03][SCENARIO] Exécution du sous-élément de type [action] : then
    [2017-01-03 21:53:03][SCENARIO] Exécution d'un bloc élément : 113
    [2017-01-03 21:53:03][SCENARIO] Exécution du sous-élément de type [condition] : if
    [2017-01-03 21:53:03][SCENARIO] Evaluation de la condition : [0 == 0] = Vrai
    [2017-01-03 21:53:03][SCENARIO] Exécution du sous-élément de type [action] : then

Merci pour votre aide !

Denis

**Comment by zoic21** [comment]
Bonjour,
Le soucis est plus compliqué que ça ici il n'est pas possible de corriger cette partie du à la banalisation des caractère lors de l'appels du sous process pour le scénario cela pour des raisons de sécurité...
