### ISSUE TITLE
[APP][1.2]Bug menu hamburger (clic transparent) uniquement IOS

### ISSUE THREAD

**Issue by gui59169** [jeedom/issues#166]
Bonjour,

sur dernière version jeedom sur iphone j'ai un soucis sur le bouton en haut a gauche pour sélectionner les plugins.

Sur mon ecran d'acceuil j'ai des boutons permettant d'ouvrir portail et porte de garage entre autre, ils se retrouvent cachés lorsque je clique pour selectionner le menu plugin

par exemple, Lorsque j'ouvre le menu plugin, je prend mode et je sélectionne mon mode, mais il arrive que ça clique sur le bouton qui se trouve positionné au même endroit derrière.

Du coup, je selectionne mon mode "Present" par exemple, et ça m'ouvre aussi ma porte de garage. 

Malheuresement je trouve toujours l'app trop lente.... sur iphone 6.

**Comment by magicgg91** [comment]
Je reproduis le problème de calque sur iPhone 7 avec iOS 10.2, appli v1.1.0

Le problème ne se pose qu'avec les pièces en mode carré, et quand l'appli a été relancée sans avoir été fermée complètement ou avec téléphone en veille sur l'appli avec les pièces/objets comme page ouverte

**Comment by gui59169** [comment]
Oui tout a fait ✅ !

**Comment by rocket13011** [comment]
Je prend note et le mets dans la prochaine version ;) Merci du retour.

**Comment by magicgg91** [comment]
Bug toujours présent

**Comment by magicgg91** [comment]
Toujours présent

**Comment by magicgg91** [comment]
OK avec la 1.2.0(13) et le nouveau système de notif
Issue à clore
