### ISSUE TITLE
[CORE] Boucle while inutile

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#167]
Dans le fichier market.repo.php en ligne 212 on vois ceci
```
while (True) {
	        try {
	            $backup = repo_market::uploadChunk($_path, $backup["chunk_start"], $backup["chunk_end"], $backup["id"], $fileSize);
	        } catch (Exception $e) {
	            echo $e->getMessage()."\n";
	            repo_market::sendBackupCloud($_path);
	            break;
	        }
	        if ($backup["completed_at"] && $backup["completed_at"] != ""){
	            log::add('backupCloud','info','le backup a fini l upload');
	            break;
	        }
	    }
```
Pour moi cette boucle while ne sert à rien car elle n'a comme paramètre que true. Si pour une raison que j'ignore on veux que cette boucle s'exécute au moins une fois il faut utiliser la forme "do while". Je persiste à penser que cette boucle ne sert à rien.

**Comment by tmartinez69009** [comment]
Merci, optimisé par le dernier commit. 
La boucle envoie des morceaux de fichier tant que le market ne lui répond pas que le fichier est terminé.
