### ISSUE TITLE
[MOBILE][Virtuel] v84 Après suppression de virtuel ils apparaissent encore dans la pièce

### ISSUE THREAD

**Issue by mamatdv** [jeedom/issues#17]
Après avoir supprimé des virtuels dans une pièce, ils apparaissent toujours dans la pièce concerné.
Refresh complet et de la pièce fait + kill de l'app fait

Ces virtuels étaient tous rattaché a la multiprise greenwave.
J'attend tes instructions avant de faire un reinit.

**Comment by rocket13011** [comment]
Ne réinit pas prochaine version demain (28 juin) pour avec petite correction qui devrait supprimer le bug !

**Comment by mamatdv** [comment]
Cool si tu l'a reproduit.

Je test ça demain alors :)
