### ISSUE TITLE
[PLUGIN MOBILE] eqLogic vide après découpage

### ISSUE THREAD

**Issue by DanoneKiD** [jeedom/issues#171]
Lors du découpage d'un eqLogic (ici ID = 37) qui comporte plusieurs cmds du même type en plusieurs eqLogic "virtuels", l'eqLogic de départ est quand même renvoyer par la méthode sync, mais sans aucune information (pas de cmds...).

Voir exemple en pj

[sync.txt](https://github.com/jeedom/issues/files/708839/sync.txt)

**Comment by rocket13011** [comment]
on part sur issue-app
