### ISSUE TITLE
[Core] Problème de CSS

### ISSUE THREAD

**Issue by colas31** [jeedom/issues#172]
Bonjour,

Sur la version 2.4.6, il y a un soucis d'affichage sur la page index.php?v=d&p=profils permettant d'éditer les paramètres d'un profil. 
Le bloc "Interface" est inutilisable. Voici le résultat.
![selection_009](https://cloud.githubusercontent.com/assets/1360459/22023398/47cddb4c-dcc6-11e6-9bb3-e891f7b6ebe1.png)

A savoir que je n'ai pas de css custom. ce bug se reproduit sur deux instances différentes de Jeedom

Merci

**Comment by zoic21** [comment]
Bonjour,
C'est un soucis connu du à une mise à jour de chrome. Malheureusement nous n'apporterons la correction qu'avec jeedom 3.0 (nous n'avons aucune date de sortie pour le moment)

**Comment by colas31** [comment]
Merci pour le retour, tant que le soucis est connu c'est le principal ;) j'attendrai pour pouvoir configurer le reste.
Petite question qui concerne les options de cette page. Il est possible d'indiquer en mode mobile, le type d'affichage souhaitée lors du démarrage.
J'ai mis le mode design avec full screen : en récupérant l'url j'ai un truc du genre : index.php?v=d&p=plan&paln_id=1

faut qu'à l'affichage il y a un glitch pour le passage en mode full screen. Y'a t'il une url qui permette d'afficher directement le fullscreen pour éviter ce glitch ou est ce plutot une feature /bug ?

**Comment by zoic21** [comment]
Pour ca il faut demander sur le forum ou ouvrir un ticket nous ne faisons pas de support sur github qui est juste la pour le suivi des bugs

**Comment by colas31** [comment]
Très bonne mémoire. Merci ;)
