### ISSUE TITLE
[APP][BETA 1.2][iOS] Qrcode ko post réinit complet 

### ISSUE THREAD

**Issue by phifi92** [jeedom/issues#173]
Vu à minima par 2 bêta-testeurs (avec sbo)
Reproduit avec l'ancien et un nouveau équipement plugin mobile pour iPhone
L'installation par Qrcode ne fonctionne pas (nous l'avons testé post mise à jour en 1.2, et post reinit complet de l'apps)
Nous obtenons systématiquement l'erreur : 
Titre : Jeedom connexion
Message : Connexion impossible merci de vérifier votre connexion internet (d'ailleurs, il manque un accent à vérifier, et j'aurais mis une virgule après impossible)
Capture : https://app-jeedom.slack.com/archives/general/p1484684540000400

Résolu temporairement par une saisie manuelle des URL

**Comment by phifi92** [comment]
Pb reproduit avec la version 1.2.0(5)

**Comment by rocket13011** [comment]
alors normalement pas tout a fait ;) car il doit avoir une suite derriere le message.

**Comment by phifi92** [comment]
Vu le résultat..., voici : 
Titre : Jeedom Connexion
Message : Connexion impossible merci de verifier votre connexion. > undefined

**Comment by rocket13011** [comment]
Normalement résolu en 1.2.0 beta 11

**Comment by phifi92** [comment]
résolu
