### ISSUE TITLE
[APP][1.1] Status fil pilote

### ISSUE THREAD

**Issue by ngranier** [jeedom/issues#174]
Le type générique "chauffage fil pilote état" ne remonte qu'un chiffre qui correspond bien à la valeur retourné par le module.
L'état 0 correspond bien à off avec affichage de l'icône ( uniquement dans pièce, , pas d'icône en raccourci)
Mais après aucune correspondance pour confort, eco, HG.
Exemple:
Les modules fils pilote Zwave ( les seuls que je connaisse) Quibino, retourne ça:
Confort : 99
Eco: 30
Off: 0
Hors Gel:20

**Comment by rocket13011** [comment]
on part sur issue-app
