### ISSUE TITLE
[APP][BETA 1.2] Barre d'état iOS absente après maj

### ISSUE THREAD

**Issue by magicgg91** [jeedom/issues#175]
Version Jeedom : 3.0.3
Version Plugin App Mobile : 2016-12-29 14:16:33
Téléphone : iPhone 7 iOS 10.2
Version application : 1.2.0 (3)

Ouverture de l'application, synchro en cours, synchro OK, mais barre d'état iOS ne s'affiche pas.
Si je vais dans la config, la barre d'état iOS s'affiche, mais dès que je reviens à l'accueil, elle disparaît.

Reproduit par plusieurs BT

https://files.slack.com/files-tmb/T3KNBLDLN-F3T35QK2N-f33867c9c6/image_uploaded_from_ios_480.jpg

**Comment by magicgg91** [comment]
Bon après fermeture complète de l'application, je ne reproduis plus.

**Comment by magicgg91** [comment]
Le problème se produit uniquement lors de la 1ère ouverture de l'application après la maj.

**Comment by magicgg91** [comment]
Ok avec la 1.2.0(5)

**Comment by magicgg91** [comment]
Alors en fait, OK après la maj, mais maintenant elle disparaît quand on met l'app en veille

**Comment by magicgg91** [comment]
Toujours pareil, barre d'état iOS absente après ouverture et synchronisation

**Comment by phifi92** [comment]
version : 1.2.0 (6)
Pour compléter, je reproduit très facilement quand on bascule l'app en multi-tâche, lors de la réouverture, et **juste avant** la 1ère notification de la synchro -> la barre d’état disparait et ne revient plus. Mais elle ré-apparaît si je vais dans "Configuration App Jeedom", puis disparaît lors du retour sur la page d’accueil.
Donc deux façon d'avoir le pb : 
1) app mobile ouverte, mettre le tél en veille. Sortie de veille -> barre iOS disparaît
2) app mobile ouverte, bascule multi-tâche sur l'accueil ou autre app, de retour sur l'app mobile --> barre iOS disparaît
3) suite mise à jour ? pas fait attention (pas taper :))

**Comment by rocket13011** [comment]
Normalement résolu en 1.2.0 beta 11

**Comment by magicgg91** [comment]
OK dans tous les cas avec la 1.2.0 (11)
