### ISSUE TITLE
[PLUGIN Officiel] - [Sonos controller] - Erreur UPnPError: 701 

### ISSUE THREAD

**Issue by BenAndNuts** [jeedom/issues#176]
Bonjour,

J'utilise sans soucis le plugin officiel sonos controller depuis quelque temps déjà pour lire des playlists / play / pause / volume etc..
Et ça fonctionne plutôt bien surtout que le widget est bien fait.

Je souhaite utiliser les sonos pour me faire des retours d'état via TTS et ça fonctionne (il faut bien suivre la doc d'install pour créer le share et donner les bons droits).

J'ai cependant un soucis très particulier et reproductible : lorsque la PLAYBAR est en mode "**TV**" la commande "**Dire**" ne fonctionne pas et renvoie l'erreur suivante : "**UPnPError: 701**".

```
Hardware : RPI3 + Zwave + Sonos Playbar et Play 1
Jeedom : DIY 2.4.6
Plugin Sonos controller : A jour
```

**Comment by zoic21** [comment]
Bonjour,
Malheureusement il n'y a pas d'api sonos officiel et aucune documentation, ce qui fait qu'ils nous aient impossible de corriger ce soucis connu.

**Comment by BenAndNuts** [comment]
Hello,

C'est vrai que ça à longtemps été le cas, mais ils ont changé récemment de politique et c'est maintenant dispo : http://musicpartners.sonos.com/?q=docs

**Comment by zoic21** [comment]
Oui mais tout n'est pas encore dedans

**Comment by BenAndNuts** [comment]
Je comprends pas évident lorsque ce n'est pas bien clair.

Cependant j'ai vu que le plugin utilisait la lib de duncan3dc (https://github.com/duncan3dc/sonos/) et que ce bug connu semble résolu (ex cette issue : https://github.com/duncan3dc/sonos/issues/13).

Peut-être suffirait-il de MAJ votre plugin avec la nouvelle version afin de corriger le soucis.

**Comment by zoic21** [comment]
Vu la date de la date et quand ca a été fermé c'est intégré dès les 1er version du plugin
