### ISSUE TITLE
[CORE][Scenario][BETA] La popup du bouton "commande" ne s'affiche pas sur action "variable"

### ISSUE THREAD

**Issue by abarrau** [jeedom/issues#178]
Bonjour, 

Sur la page de création d'un scénario (en mode avancé), le bouton permettant d'afficher la popup des commandes ne fonctionne pas lorsque l'action est de type "variable". 
(Les autres actions (wait, event, ...) semblent eux fonctionner). 

![variable_pas de popup](https://cloud.githubusercontent.com/assets/13674762/22165319/708d3658-df5b-11e6-88d4-d2d9e1f6dec2.png)

Version : 3.0.3 du 18/03
Déjà présent sur la version précédente. 

Cdt,
Aurélien

**Comment by zoic21** [comment]
Bonjour,
C'est corrigé dans la dernière beta.
Merci pour le retour.

**Comment by abarrau** [comment]
ok, testée et validée, merci. 
(v3.0.3, update du 24/01/17)
