### ISSUE TITLE
[CORE][Widget][BETA] Le widget "timeWindows" ne présente pas le temps passé

### ISSUE THREAD

**Issue by abarrau** [jeedom/issues#179]
Bonjour, 

Le widget "timeWindows" du core, ne présente pas le temps passé lorsqu'il est sur le dashboard (vue, design) ; mais fonctionne correctement sur mobile. 

Il semblerait qu'il manque la class "timeCmd" dans le span en complément de class="timeCmd#uid# ..."

Remarque: les autres widget de temps (présence, porte), sont ok. 

Question: [évolution] pourquoi ne pas généraliser cette fonction en standard par un choix paramétrable pour tous les widget (au même titre que l'affichage des statistiques par exemple).

Version 3.0.3; dernier update le 18/01

Cdt,
Aurélien

**Comment by zoic21** [comment]
Bonjour,
Le probleme est-il présent sur un widget core ? Je viens de tester chez moi et tout est ok avec les widgets core, pour les autres widgets ca je ne sais pas...
Pour la généralisation non c'est le widget qui gère ou non plus je mets des trucs comme ça plus jeedom est lent...

**Comment by abarrau** [comment]
Loic, oui c'est bien un widget du core, sinon je n'aurais pas ouvert. 
dans la liste des widgets sur le paramètre d'une commande, il s'appelle "timeWindow (core)".
chez moi ça fonctionne en mobile, mais pas en dashboard.
ok pour ton retour sur l'évol.
Cdt,

**Comment by zoic21** [comment]
Je viens d'envoyer la correction. Merci pour le retour

**Comment by abarrau** [comment]
OK, correction testée et validée.
(update du 3.0.3 du 22/01/17)
