### ISSUE TITLE
[CORE][BETA] Problème de mise en forme de widget

### ISSUE THREAD

**Issue by mamatdv** [jeedom/issues#18]
Sur certain widget d'état (température, fumée, inondation, luminosité, intensité ....) il est impossible d'enlever le nom du widget malgré le paramétrages de ceux ci

![widget2](https://cloud.githubusercontent.com/assets/11528172/16489150/78e90c46-3ed4-11e6-97e7-a9d82dadc263.PNG)

![widget1](https://cloud.githubusercontent.com/assets/11528172/16489155/7d99cdfc-3ed4-11e6-91ee-59ceeb87a9a6.PNG)

Par ailleurs sur certains widgets états, les noms ne sont plus positionné au dessus de l’icône.

![widget3](https://cloud.githubusercontent.com/assets/11528172/16489157/81c29800-3ed4-11e6-9411-5bdb503cbf7b.PNG)

**Comment by zoic21** [comment]
Salut,
J'avais mal vu mais si tu utilises un widget venant pas du core je ne fais rien dessus je ne corrige que pour les widgets inclus dans le core de jeedom, c'est les seuls officiels.
