### ISSUE TITLE
[APP][1.2]Ajout du mdp à touchId

### ISSUE THREAD

**Issue by Claude69** [jeedom/issues#180]
IMPORTANT : consigne pour que votre soumission ne soit pas refusée. Si vous ne respecter pas tous les points votre demande sera fermée immédiatement.

TITRE : merci de le nommer comme cela [COMPOSANT] Titre. Exemple [RFXCOM] Mon titre, ou pour jeedom lui meme [CORE] Mon titre. ATTENTION si vous etes beta testeur merci de rajouter [BETA] dans le titre : [RFXCOM][BETA] Mon titre

MESSAGE : merci de bien mettre toutes les informaitons suivantes :
- la version de jeedom (si c'est une bêta la date de dernière mise à jour)
- la liste des plugins ainsi que leur date de mise à jour
- le log nginx.error ou http.error
- une capture d'écran
- si c'est un soucis sur l'interface faire F12 puis console et fournir le resultat

**Comment by Claude69** [comment]
Sous iOS, (stable et bêta 5), si erreur d'authentification avec touchID, on a un message pour demande de mot de passe, avec code erreur -3 puis on bloque sur l'écran d'accueil avec le message "chargement de l'application "
Idem si on ne veut volontairement ne pas utiliser l'empreinte, mais entrer un code (code erreur -2)

**Comment by rocket13011** [comment]
on part sur issue-app
