### ISSUE TITLE
[PLUGIN MOBILE] Erreur lors du lancement du daemon

### ISSUE THREAD

**Issue by tocks53** [jeedom/issues#181]
Jeedom beta du : 24/01/2016
Plugin mobile en beta

Bonjour,

L'installation des dépendance ce passent bien. Mais je rencontre une erreur sur le lancement du daemon.

@rocket13011, avait commencé à regarder.

log installation dependance

`Lancement de l'installation/mise à jour des dépendances homebridge
Reading package lists...
Building dependency tree...
Reading state information...
avahi-daemon is already the newest version.
avahi-discover is already the newest version.
libavahi-compat-libdnssd-dev is already the newest version.
libnss-mdns is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
Version actuelle : v5.12.0
Ok, version suffisante
/usr/lib
`-- request@2.79.0
+-- har-validator@2.0.6
| `-- chalk@1.1.3
|   `-- has-ansi@2.0.0
|     `-- ansi-regex@2.1.1
+-- http-signature@1.1.1
| `-- sshpk@1.10.2
`-- mime-types@2.1.14
`-- mime-db@1.26.0
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge
/usr/lib
`-- homebridge@0.4.16
`-- chalk@1.1.3
`-- has-ansi@2.0.0
`-- ansi-regex@2.1.1
/usr/lib
`-- homebridge-jeedom@1.0.12  (git+https://github.com/jeedom/homebridge-jeedom.git#1b54b240d0f509645119a0421c8e5e1f15802719)
`-- request@2.79.0
+-- har-validator@2.0.6
| `-- chalk@1.1.3
|   `-- has-ansi@2.0.0
|     `-- ansi-regex@2.1.1
+-- http-signature@1.1.1
| `-- sshpk@1.10.2
`-- mime-types@2.1.14
`-- mime-db@1.26.0
Installation Homebridge OK`

log lancement daemon :

`[2017-01-19 11:16:55][INFO] : Lancement démon homebridge : homebridge -D -U /var/www/html/plugins/mobile/core/class/../../resources/homebridge
[2017-01-19 11:16:56][INFO] : Démon homebridge lancé
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
/usr/lib/node_modules/homebridge/node_modules/bindings/bindings.js:91
throw err
^
Error: Could not locate the bindings file. Tried:
→ /usr/lib/node_modules/homebridge/node_modules/ed25519/build/ed25519.node
→ /usr/lib/node_modules/homebridge/node_modules/ed25519/build/Debug/ed25519.node
→ /usr/lib/node_modules/homebridge/node_modules/ed25519/build/Release/ed25519.node
→ /usr/lib/node_modules/homebridge/node_modules/ed25519/out/Debug/ed25519.node
→ /usr/lib/node_modules/homebridge/node_modules/ed25519/Debug/ed25519.node
→ /usr/lib/node_modules/homebridge/node_modules/ed25519/out/Release/ed25519.node
→ /usr/lib/node_modules/homebridge/node_modules/ed25519/Release/ed25519.node
→ /usr/lib/node_modules/homebridge/node_modules/ed25519/build/default/ed25519.node
→ /usr/lib/node_modules/homebridge/node_modules/ed25519/compiled/5.12.0/linux/x64/ed25519.node
at bindings (/usr/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88:9)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/ed25519/index.js:1:99)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:6:15)
at Module._compile (module.js:413:34)
`

voila, je suis dispo si il y a des tests à réaliser

**Comment by rocket13011** [comment]
Je vais mettre un bouton pour supprimé Homebridge complètement lors de la reinit
