### ISSUE TITLE
[APP][BETA 1.2] Affichage plugin Mode dans l'écran d'accueil

### ISSUE THREAD

**Issue by bphoque** [jeedom/issues#182]
Sur la page d'accueil, lorsqu'on choisi le plugin mode, il n'est pas possible de choisir le mode à afficher. Par exemple, il n'affiche pas le mode "nuit" mais "autre mode".
![img_3058](https://cloud.githubusercontent.com/assets/24958395/22257975/113ae580-e260-11e6-9bdc-49e91e7e34e8.PNG)
![img_3059](https://cloud.githubusercontent.com/assets/24958395/22257977/1249d486-e260-11e6-8d0f-c837348ea5f8.PNG)

**Comment by rocket13011** [comment]
Tu peux me faire un screen de tes modes dans Jeedom ?
Je n'arrive pas a reproduire ?
