### ISSUE TITLE
[APP][BETA 1.2.0] Messages Jeedom

### ISSUE THREAD

**Issue by tocks53** [jeedom/issues#185]
J'utilise le même compte sur l' APP et Jeedom

-Il y a 3 message dans jeedom
-Jouvre l'app, je voie les 3 messages
- Je supprime les 3 messages dans jeedom
- L'app ne ce met pas a jours
- je ferme l'app
- je relance l'app, les messages sont encore présent dans l'app

**Comment by Claude69** [comment]
Je confirme, plus de message sur Jeedom, mais toujours présent sur l'App mobile
