### ISSUE TITLE
[Z-wave][Beta][Zipato Mini Keypad RFID] Erreur JS

### ISSUE THREAD

**Issue by skyline-ch** [jeedom/issues#186]
Jeedom Bêta 3.0.3
Z-wave du 2016-10-31 01:07:37 en attente de ok pour mise à jours avec la nouvelle version
Capture d'écran de l'erreur
![capture001](https://cloud.githubusercontent.com/assets/13089438/22356609/f829dff4-e432-11e6-9254-e51db0b97744.png)

Pour reproduire, dans la configuration du module, cliquer sur "assistant", dès l'ouverture de cette fenêtre l'erreur apparait dans la console, les action ajouter et supp d'un tag ne fonctionne donc pas.

J'ai tenter de chercher l'erreur dans les fichiers du plugin sans succès, en cliquant dans la console sur le lien cela nous mène à la capture si dessous :  
![capture002](https://cloud.githubusercontent.com/assets/13089438/22356930/174f1690-e435-11e6-8234-cf08892abee7.png)

A part la valeur à la ligne 15 qui peux vouloir une virgule plus tôt qu'un point je vois pas trop d'autre souci

**Comment by nechry** [comment]
Il faut retirer le mode master /slave de l'assistant.

**Comment by skyline-ch** [comment]
Le retirer de z-wave ? 

Et pour la nouvelle version du plugin ont en est où,  toujours conseiller de ne pas mettre à jour ?

**Comment by nechry** [comment]
Non le retirrer du UI de gestion des bages. Mais comme c'est pas prèt de toute façon il ne faut pas utiliser.

**Comment by skyline-ch** [comment]
OK,  donc tout sera bon pour la sorti de la jeedom 3.0, si c'est le cas et qu'il ni as pas de test particulier a faire la dessus alors ont peux clore l'issue

**Comment by nechry** [comment]
Non mieux la laisser ouvert et on la referme lorsqu'on fix le code, de cette façon on garde à l'esprit

**Comment by skyline-ch** [comment]
OK parfait, bonne soirée,  et encore merci pour tout le boulot

**Comment by clausdk** [comment]
Hope this will be fixed soon. This is the only thing that's needs to be fixed for me to use the beta version. I tried removing the master/slave code, but it seems some of the code behind in the z-wave scripts, is missing in the beta version.
