### ISSUE TITLE
[PLUGIN NETATMO WELCOME] Netatmo Welcome : proposition patch pour ajout support Netatmo Presence

### ISSUE THREAD

**Issue by atomusk** [jeedom/issues#187]
Bonjour, 

J'ai pas mal fouillé dans le code du plugin netatmo presence (avec le plugin developeur) et j'ai plus ou moins identifié ce qui manquait pour ajouter le support de la Netatmo Presence.
Ne pouvant faire de proposition de patch sur un plugin payant, voici donc les propositions de modification :

1) ajout dans le plugin camera d'une camera nommée presence avec son image et son fichier de configuration copié de welcome.

2) alignement du fichier :
netatmowelcome/3rdparty/Netatmo-API-PHP/Netatmo/Common/NAScopes.php avec l'api à jour de Netatmo:
https://github.com/Netatmo/Netatmo-API-PHP/blob/master/src/Netatmo/Common/NAScopes.php
Pour avoir les 3 nouvelles autorisations Read/write/access presence.

3) Modifications dans netatmoWelcome.class.php :
supprimer tous les appels à : $camera_array = $camera_array['object']; 
Je ne sais pas si c'est l'API netatmo qui a évolué, mais ce code n'est plus nécessaire, ce qui entraine des bugs (par exemple les camera qui se dupliquent quand on relance la synchronisation).

Puis on applique les nouvelles autorisations :
Netatmo\Common\NAScopes::SCOPE_READ_CAMERA 

devient : 
Netatmo\Common\NAScopes::SCOPE_READ_CAMERA . ' ' . Netatmo\Common\NAScopes::SCOPE_READ_PRESENCE 

et :

Netatmo\Common\NAScopes::SCOPE_ACCESS_CAMERA

devient :
Netatmo\Common\NAScopes::SCOPE_ACCESS_CAMERA . ' ' . Netatmo\Common\NAScopes::SCOPE_ACCESS_PRESENCE

J'ai aussi un bug qui fait que mes camera se créent avec une IP à vide (possible que ça soit une évolution de l'API encore). 
Du coup, je propose d'ajouter après :

$url .= '/live/snapshot_720.jpg';
$url_parse = parse_url($url);

if ($url_parse['host'] == ""){
	$url_parse = parse_url($camera->getVpnUrl() . '/live/snapshot_720.jpg');			
}

Pour que si la detection de l'IP locale échoue on puisse quand même récupérer l'IP "globale" (permettra aussi de gérer les cas où la camera est dans un autre sous reseau que la box Jeedom.

et enfin pour différencier la Welcome de la Presence, il faudrait au niveau de la detection de la camera :
$camera_jeedom->setConfiguration('device', 'welcome');

remplacer par 
if ($camera_array['type'] == 'NOC'){
	$camera_jeedom->setConfiguration('device', 'welcome');
}else{
	$camera_jeedom->setConfiguration('device', 'presence');
}

Ces modifications :
- permet d'ajouter la camera Presence
- permet de créer correctement les camera même si le code pour récupérer l'IP locale ne fonctionne pas 
- corrige le bug qui fait que chaque synchronisation duplique les camera

Reste à voir :
- Pourquoi je n'arrive pas à récupérer les ip locales avec la routine ping
- gérer les evenements spécifiques de la Presence pour les "evenement animal", "evenement voiture", "evenement humain".

**Comment by atomusk** [comment]
Concernant les evenement de la Netatmo Presence, il semble que l'API est légérement différente (et du coup je propose de remplacer la gestion des event dans refresh_info juste après :

$events = $home->getEvents();

par :

```
//vérification si on est dans le cas des listes d'evenements de la Presence
$eventList = $events[0]->getVar('event_list');
              	
               	if ($eventList != null){

                	foreach ($eventList as $event) {                                                	          
                 		if ($event[time] > (strtotime('now') - 60) && $event[type]== 'movement') {
                      		$cmd = $eqLogic->getCmd('info', 'movement' . $events[0]->getCameraId());
                        	if (is_object($cmd) && $cmd->execCmd() !== $cmd->formatValue(1)) {
	                            $cmd->event(1);
	                        }
						}

						$message = date('Y-m-d H:i:s', $event[time]) . ' - ' . $event[message];
                      	$cmd = $eqLogic->getCmd('info', 'lastOneEvent');
                      	if (is_object($cmd) && $cmd->execCmd() !== $cmd->formatValue($message)) {
							$cmd->event($message);
                      	}                      	                                                                                  
                    }
                }else{
                  if ($events[0]->getTime() > (strtotime('now') - 60) && $events[0]->getEventType() == 'movement') {
                      $cmd = $eqLogic->getCmd('info', 'movement' . $events[0]->getCameraId());
                      if (is_object($cmd) && $cmd->execCmd() !== $cmd->formatValue(1)) {
                          $cmd->event(1);
                      }
                  }

                  $message = date('Y-m-d H:i:s', $events[0]->getTime()) . ' - ' . $events[0]->getMessage();
                  $cmd = $eqLogic->getCmd('info', 'lastOneEvent');
                  if (is_object($cmd) && $cmd->execCmd() !== $cmd->formatValue($message)) {
                      $cmd->event($message);
                  }
                }
              
              //gestion de la liste des evenements avec les evenement de Welcome & présence mélangés
              	$message = '';
              	foreach ($events as $event) {
                    if ($event->getVar('event_list') != null)
                    	foreach ($eventList as $event) {
                        	$message .= date('Y-m-d H:i:s', $event['time']) . ' - ' . $event['message'] . '<br/>';
                        }
                    else{
    	            	$message .= date('Y-m-d H:i:s', $event->getTime()) . ' - ' . $event->getMessage() . '<br/>';
                    }
	            }

```

**Comment by zoic21** [comment]
Bonjour,

Merci pour le retour et le code, je viens de l’intégrer dans la version beta du plugin, je vais voir si on a des betatesteur équipé de la présence pour confirmer que tout est bon
