### ISSUE TITLE
[APP][MOBILE] Erreur dans les logs http

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#188]
Bonjour,

Je suis avec la dernière version du plugin mobile et mes logs http.error sont polluées d'erreur comme suit :
[Sun Jan 29 09:53:56.624179 2017] [:error] [pid 59151] [client 192.168.1.94:56178] PHP Notice:  Undefined index: minValue in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 293
[Sun Jan 29 09:53:56.624188 2017] [:error] [pid 59151] [client 192.168.1.94:56178] PHP Notice:  Undefined index: actionCodeAccess in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 294
[Sun Jan 29 09:53:56.624197 2017] [:error] [pid 59151] [client 192.168.1.94:56178] PHP Notice:  Undefined index: actionConfirm in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 295
[Sun Jan 29 09:53:56.624206 2017] [:error] [pid 59151] [client 192.168.1.94:56178] PHP Notice:  Undefined index: invertBinary in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 298
[Sun Jan 29 09:53:56.624215 2017] [:error] [pid 59151] [client 192.168.1.94:56178] PHP Notice:  Undefined index: title_disable in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 299
[Sun Jan 29 09:53:56.624224 2017] [:error] [pid 59151] [client 192.168.1.94:56178] PHP Notice:  Undefined index: title_placeholder in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 300
[Sun Jan 29 09:53:56.624233 2017] [:error] [pid 59151] [client 192.168.1.94:56178] PHP Notice:  Undefined index: message_placeholder in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 301
[Sun Jan 29 09:53:56.624823 2017] [:error] [pid 59151] [client 192.168.1.94:56178] PHP Notice:  Undefined index: maxValue in /var/www/html/plugins/mobile/core/class/mobile.class.php on line 292

Merci
Thomas

**Comment by rocket13011** [comment]
Doublon #159 que tu a aussi fait !

**Comment by guenneguezt** [comment]
Lol désolé j'ai beaucoup dormi depuis et là je retombe sur le problème car ces erreurs empèchent la lisibilité de toutes les autres ...
