### ISSUE TITLE
[Virtuel][BETA] Fonction Dupliquer ne copie pas tous les éléments

### ISSUE THREAD

**Issue by tocks53** [jeedom/issues#189]
Bonjour, Jeedom Beta derrière version à ce jour.

Il manque des liste déroulante a gauche qui ne sont pas copié lors d'un duplication.

Virtuel originel : 

![selection_763](https://cloud.githubusercontent.com/assets/7701808/22502434/1c2b9422-e86d-11e6-9a79-c87996df00d0.png)

Virtuel dupliqué : 

![selection_764](https://cloud.githubusercontent.com/assets/7701808/22502427/154e3538-e86d-11e6-8e45-8fc3c845f237.png)

Nous somme plusieurs à reproduire sur le slack.

**Comment by zoic21** [comment]
Bonjour,
Ce n'est simplement pas possible de le faire lors de la duplication.

**Comment by tocks53** [comment]
ha ok dommage, mais si on peux pas ba pas grave.

Merci pour le retour
