### ISSUE TITLE
[APP][1.2] Double clique sur un équipement l'ouvre 2 foisa

### ISSUE THREAD

**Issue by alexandreberton** [jeedom/issues#191]
Dernière beta android en date du 02/02/17

Lorsque l'on double clique sur un équipement (thermostat, caméra, ...) depuis la page d'une pièce, l'équipement s'ouvre 2 fois? 

Repro steps:
Ouvrir l'application
Cliquer sur "pièces" en bas
Ouvrir une pièce
Double clique sur un équipement qui ouvre une nouvelle page (caméra, thermostat, ...).
=> L'équipement s'ouvre 2 fois

**Comment by rocket13011** [comment]
Nouveau Moteur de page pour l'app en cours de creation

**Comment by rocket13011** [comment]
on part sur issue-app
