### ISSUE TITLE
[PLUGIN DYNDNS] Problème mise à jour no-ip - proposition correction

### ISSUE THREAD

**Issue by atomusk** [jeedom/issues#194]
Bonjour,

J'ai identifié une évolution dans l'API No-ip qui explique les souci de mise à jour de l'ip ainsi qu'un bug dans la vérification sur la version stable du plugin DYNDNS.

Dans dyndns.class.php au niveau du "case 'noipcom'" le passage en url du login / password semble ne plus être supporté, car en modifiant : 

```
//$url = 'https://' . $this->getConfiguration('username') . ':' . $this->getConfiguration('password') . '@dynupdate.no-ip.com/nic/update?hostname=' . $this->getConfiguration('hostname') . '&myip=' . $ip;
$url = 'https://' . '@dynupdate.no-ip.com/nic/update?hostname=' . $this->getConfiguration('hostname') . '&myip=' . $ip;
$request_http = new com_http($url,$this->getConfiguration('username'),$this->getConfiguration('password'));           	
```	

Je récupére à nouveau les good & nochg dans le $result.

Malgré tout j'ai remarqué je récupérait quand même une erreur : 
Erreur de mise à jour de noip.com : nochg [monIP]

Aussi en modifiant le "||" par "&&" dans le test (comme celui de OVH) et je n'ai plus l'erreur (ce qui est plus logique )

Merci

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour la correction est faite et sera disponible demain sur le market.
