### ISSUE TITLE
[PLUGIN MOBILE] Log : Connaitre le nom de l'équipement qui communique & analyse des logs

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#195]
Bonjour,

Dans les logs on ne sais pas que portable communique avec l'application mobile.
J'ai eu un souci avec une désactivation de l'alarme depuis l'application mobile.
Dans les logs de l'application mobile  sur le mobile, j'ai :
[error]2-7-2017 12:55 | Synchronisation Start | Connexion à votre Jeedom en cours ...
[error]2-7-2017 12:55 | Synchronisation Start | Récuperation des informations ...
[error]2-7-2017 12:55 | Synchronisation Start | Lancement de l'application.
Impossible de savoir si ça a eu un impact.

Je ne sais pas si l'application mobile a notifié mon jeedom. Comment le savoir ?
Dans les logs du plugin mobile, je n'ai pas vu de demande de changement d'état pour l'alarme.

A+
Thomas

**Comment by rocket13011** [comment]
Normal, il faut chercher dans les log de l'api de Jeedom c'est elle qui reçois l'ordre d'executer une commande. (on vas pas réinventer la roue.)
