### ISSUE TITLE
[APP][BETA] Info/Température tronquée si plus de 5 caractères

### ISSUE THREAD

**Issue by GuiPoM** [jeedom/issues#196]
Ma sonde de température de SDB (un détecteur d'inondation zwave remonte parfois la température avec une précision nécessitant l'utilisation de 5 caractères

Dans le plugin mobile, Type générique= "Température" 
et dans la plugin: 
"id":"1603","logicalId":"0.0x31","eqType":"openzwave","name":"Temp\u00e9rature","order":"1","type":"info","subType":"numeric","eqLogic_id":"195","unite":"\u00b0C","value":"","isVisible":"1","generic_type":"TEMPERATURE","currentValue":19.56,"configuration":{"maxValue":""},"display":{"generic_type":"TEMPERATURE","invertBinary":"0"}},

Résultat en image
https://files.slack.com/files-pri/T3KNBLDLN-F41DHQ8FN/screenshot_20170206-094529.png
![](https://files.slack.com/files-pri/T3KNBLDLN-F41DHQ8FN/screenshot_20170206-094529.png)

**Comment by rocket13011** [comment]
Dispo sur la Version 7 de la beta

**Comment by rocket13011** [comment]
a tester dans la dernière version

**Comment by magicgg91** [comment]
C'était déjà OK sur iOS, mais là c'est OK sur Android aussi pour moi

**Comment by GuiPoM** [comment]
@rocket13011 : Petit soucis 
Voilà la valeur courante remontée à l'app: "id":"1603","logicalId":"0.0x31","eqType":"openzwave","name":"Temp\u00e9rature","order":"1","type":"info","subType":"numeric","eqLogic_id":"195","unite":"\u00b0C","value":"","isVisible":"1","generic_type":"TEMPERATURE","currentValue":19.05,"configuration":{"maxValue":""},"display":{"generic_type":"TEMPERATURE","invertBinary":"0"}},

ca m'affiche : "19..°C"
