### ISSUE TITLE
[APP][BETA] Crash de l'application si on la quitte puis on la ré-ouvre

### ISSUE THREAD

**Issue by cokecorp** [jeedom/issues#197]
version de l'application 1.2.0. BETA V7

je quitte l'application, je la ré-ouvre aussitôt et j'ai le droit a un beau crash de l'application., j'ai déjà envoyer plusieurs rapports comme demandé lors du crash

Je suis sur un galaxy S7 edge

**Comment by Titof174** [comment]
C'est quand on sort de l'application avec la flèche dans la navbar du bas et qu'on revient soit par l'icône du launcher, soit par les recent app.
Quand on sort par le bouton home, pas de problèmes.

**Comment by cokecorp** [comment]
exact.. avec home pas de problème je vais re-tester au cas où

**Comment by Ssshafi** [comment]
Sur mon One+2, pas de gros crash (pas de rapport d'erreur proposé) dans ces cas là, mais on voit l'app se relancer : Ecran vers de lancement puis début d'affichage du dash, puis re-ecran vert de lancement, et enfin affichage définitif du dash. Pas d'erreurs dans le log.

**Comment by rocket13011** [comment]
Oui avec les mobiles sous Android 6 normalement ça reboot juste l'app ! mais je regarde a supprimé la touche retour ^^

**Comment by Ssshafi** [comment]
Euh t'es sûr là (supprimer la touche retour) ? Car beaucoup utilisé par les droidophiles...

**Comment by rocket13011** [comment]
Supprimé l'action de sortie de l'app via cette touche, mais par contre l'utiliser dans l'app pour faire du retour arrière ;)

**Comment by Ssshafi** [comment]
Pour l'utiliser dans l'app, je suis complètement convaincu que c'est une bonne chose, par contre la virer pour sortir de l'app c'est dommage... Normalement sous android, quand t'es sur l'accueil de l'app, si tu fais retour ça quitte l'app et partout ailleurs dans l'appli ça reviens en arrière...Enfin si pas le choix, je préfère le retour arrière dans l'app ;)
