### ISSUE TITLE
[APP][BETA] Bug Scroll en mode pièces carrées

### ISSUE THREAD

**Issue by mrzac** [jeedom/issues#198]
En mode "Pièces carrées" en fin de scroll, les 2 petits points masquent les infos des 2 dernières pièces.

![appbeta-bug-piecec](https://cloud.githubusercontent.com/assets/393649/22797780/e528dae0-eeff-11e6-9d57-48ac67579cb0.jpg)

**Comment by magicgg91** [comment]
OK dans la dernière bêta
