### ISSUE TITLE
[APP][BETA 1.2] Couleur de ligne dans les pièces

### ISSUE THREAD

**Issue by bphoque** [jeedom/issues#199]
Problème d'affichage des couleurs de ligne dans l'onglet pièce. Les pièces ne sont pas séparées par une couleur différente. Toutes les lignes sont blanches au lieu d'une alternance blanc/gris.
![img_3224](https://cloud.githubusercontent.com/assets/24958395/22800074/7327e5a4-ef08-11e6-957e-7f0016a0e2c0.PNG)

**Comment by magicgg91** [comment]
OK en Pièces carrés et en lignes
