### ISSUE TITLE
CORE 2.3.3 2016-06-06 11:36:46  Champs Message sur dashboard

### ISSUE THREAD

**Issue by mamatdv** [jeedom/issues#2]
J'avais fais un retour sur le plugin SMS et les plugins utilisant les champs message et je pense que t'as du le zapper :)

on a des noms de balises qui apparaissent #title_placeholder# et #message_placeholder#
![capture d ecran 2016-06-06 22 15 36](https://cloud.githubusercontent.com/assets/11528172/15836525/7adbfb46-2c35-11e6-8ecf-77049e01cee1.png)

et de mémoire pour sms on avait qu'un seul champs

Pas d'erreur dans nginx, http.error et la console

**Comment by zoic21** [comment]
Corrigé : jeedom/core@bf456d3
