### ISSUE TITLE
[DOC] Errors in the documentation on installation via docker

### ISSUE THREAD

**Issue by GreenSkol** [jeedom/issues#203]
Hello,

I am trying to install Jeedom via docker and discovered that the official documentation for this does not work because of several issues:

- the command to create the MySQL container should mention that "/my/own/datadir" should be replaced by the host folder where MySQL data should be stored (e.g. /opt/jeedom/mysql)

- wildcard is not supported in dev mapping so this should be removed or replaced by mapping of specific device

- there is no link between the MySQL container and the Jeedom container, so connection can't be established and if "localhost" is left, connection tries to be established through local file socket, which obviously does not work:

SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

The configuration should probably be much closer to what is done for the Synology docker installer (map mysql port to host port and connect to host IP in Jeedom UI)

Until a solution is found it is probably recommended to put a warning on this section of the doc to make explicit that currently these instructions do not work.

Thanks!

**Comment by GreenSkol** [comment]
Hi,

The right command to setup the MySQL container:

sudo docker run --name **jeedom-mysql** -v **/opt/jeedom/mysql**:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=**your-mysql-password** -d mysql:latest

With:
- jeedom-mysql : the name of the mysql container
- /opt/jeedom/mysql : the host folder where you want the mysql container to store its data
- your-mysql-password : the root password for the mysql instance

The right command to setup the jeedom container:

sudo docker run --name **jeedom-server** --link **jeedom-mysql**:mysql --privileged -v **/your/jeedom/path**:j:/var/www/html -e ROOT_PASSWORD=**your-root-password** -p 9080:80 -p 9022:22 jeedom/jeedom

With:
- jeedom-server: the name of the jeedom container
- jeedom-mysql: the name of the mysql container (so that the jeedom container can access it)
- /your/jeedom/path : host folder where jeedom will store its web files
- your-root-password : root password for the jeedom container (to connect to it via ssh)

And to finalise the installation of Jeedom, you have to use "jeedom-mysql" as hostname for the database instead of localhost.

I still ran into a permission issue on a cache folder later on when installing plugins (I corrected it directly in the container).

My Z-wave USB does not seem to be recognized properly, even if the /dev/ttyACM0 appears properly in the container, so there may still be some tweaking to do

**Comment by zoic21** [comment]
Hi,
Thank for your return, I fix doc.
