### ISSUE TITLE
[APP][1.2.0(22) BETA] Pièces vides remplies par du contenu fantome

### ISSUE THREAD

**Issue by hrenaud** [jeedom/issues#204]
Jeedom Core : 2.4.6
Plugin App Mobile : 2016-12-29 15:01:24
Application version 1.2.0(22) BETA
Smartphone : iPhone 6 plus iOS 10.2.1

Lorsqu'on ouvre une pièce sans éléments (ou non remontée dans l'application mobile), ceux de la pièce (remplie) précédemment visitée sont affichés au lieu que la pièce soit vide.

**Comment by rocket13011** [comment]
Maj BETA Plugin Mobile
