### ISSUE TITLE
[Plugin MODE] Ordre des commandes

### ISSUE THREAD

**Issue by diving91** [jeedom/issues#205]
- la version de jeedom: 2.4.6 Stable
- version du plugin Mode:  2016-07-11 15:36:35

Ce ticket pour vous signaler que le plugin mode:
- ne permet pas d'ordonner les commandes par glisser/déposer
- on peux modifier l'ordre avec le résumé domotique, mais ce n'est pas persistent et cela revient à l'ordre par défaut dès que l'on sauvegarde l'équipement

Cordialement
diving91

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour c'est corrigé dans la beta du plugin

**Comment by diving91** [comment]
Excellent - Merci
une idée de date de passage en stable ? (je ne suis pas beta testeur)

**Comment by zoic21** [comment]
Non désolé nous ne fournissons jamais de date.

**Comment by diving91** [comment]
Suggestion de mettre un tag sur ce correctif: bug (ou enhancement -:)) et la release de sortie (pour l'appli mobile je vois qu'il y a des tags pour - ce pourrait être core/plugin 3.0 par ex.

**Comment by zoic21** [comment]
Bonjour,
Oui l'idée est bonne mais j'ai la flemme de le faire ça me ferais plus de boulot et j'en ai déjà assez comme ca... Désolé.

**Comment by diving91** [comment]
Je comprend - merci du retour
