### ISSUE TITLE
[CORE] Backup inconsistant - doc/images/*.png manquantes

### ISSUE THREAD

**Issue by Shyrka973** [jeedom/issues#209]
Jeedom 2.4.6 - Tous les plugins à jours d'aujourd'hui.

Un grand nombre de plugin stocke leurs images dans leur sous répertoire doc/images.
Actuellement, seules les images se terminant pas "_icon.png" sont sauvegardées.

Dans l'ensemble des plugins installés chez moi, j'ai les plugins suivants dont les images ne sont pas restaurées car pas sauvegardées:
alarme, broadlink, delestage, ephemeride, ethalsurveillance, horoscope, jeelink, jeemon, mobile, Monitoring, orvibo, rfxcom, surveillanceStation, synoaudio, thermostat, virtual, xiaomihome

Pour vérifier mes dires, il suffit de comparer l'arborescence du plugin xiaomihome par exemple fraichement installé et sa sauvegarde dans la dernière sauvegarde de Jeedom.

**Comment by zoic21** [comment]
Bonjour,
Ce problème est identifié et sera corrigé plugin par plugin au fil des mises à jour.

**Comment by Shyrka973** [comment]
Je comprends donc que les images sont placées dans le mauvais répertoire. Il aurait dû être dans un répertoire "ressources" par exemple.
Si c'est le cas, un message à l'ensemble des développeurs serait le bienvenu pour éviter les "c'est pas mois, c'est le core" car une sauvegarde doit être complète.

Merci.

**Comment by zoic21** [comment]
Les développeurs doivent se refererer au plugin template et suivre les évolutions de celui-ci qui est mis à jour fréquemment.
