### ISSUE TITLE
[CAMERA] Template Wanscam HW0038

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#211]
Bonjour,

Voici la conf. Je n'ai pas réussi avec le model wanscam.hw00XX.
[wanscam_hw0038.pdf](https://github.com/jeedom/issues/files/801516/wanscam_hw0038.pdf)
Attention, c'est un zip et non un pdf, mais j'ai pas réussi a joindre de zip.

A+
Thomas

**Comment by zoic21** [comment]
Merci c'est ajouté en beta.

**Comment by guenneguezt** [comment]
Bonjour,

Je voulais faire le push direct, mais je trouve pas le dépot du plugin...
J'avais pas testé le fichier et je pense qu'il a des problèmes mais j'ai pas encore trouvé lesquels ;-)
Les / doivent être remplacé par \/.
Les + par des espace.
Mais j'ai l'impression qu'il y a encore un loup.

A+
Thomas
