### ISSUE TITLE
[PLUGIN SONOS][BETA] TTS Voxygen ne fonctionne plus : Will not follow more than 5 redirects

### ISSUE THREAD

**Issue by Masterfion** [jeedom/issues#212]
Bonjour, la génération d'un nouveau TTS est impossible à ce jour. Tandis que les anciens messages déjà générés (mp3 stockés) fonctionnent parfaitement, générer un nouveau TTS retourne systématiquement l'erreur : 
[ERROR] : Erreur execution de la commande [xxx][yyy][Dire] : Will not follow more than 5 redirects

Je pense que le problème est totalement lié à Voxygen (évolution ? restriction ?) mais dans le doute j'ouvre cette issue pour signaler officiellement le soucis.

- jeedom 3.0.4 du 28/02/2017 @21h
- http.error ne contient aucun événement lié
- aucun autre soucis rencontré sur le plugin

**Comment by zoic21** [comment]
Bonjour,
Je pense que le soucis vient de voxygen il faudra donc passer par picotts, le soucis de francais en picotts sera corrigé dans la prochaine version stable du plugin (sortira avec jeedom 3.0)
