### ISSUE TITLE
[PLUGIN CAMERA] Fichier de configuration pour Wanscam HW0021 et HW0045

### ISSUE THREAD

**Issue by virux54** [jeedom/issues#213]
Salut, 

Voici 2 templates a éventuellement ajouter au plugin camera pour les Wanscam HW0021 et HW0045
(j'ai ajouté .txt aux templates json pour pouvoir faire l'upload)

J'espère que je post au bon endroit, car je crois que le plugin camera est private donc pas de git.

Merci.

![wanscam hw0021](https://cloud.githubusercontent.com/assets/12999602/23705151/b12aed1e-0408-11e7-8f90-37863702ca59.jpg)
[wanscam.hw0021.json.txt](https://github.com/jeedom/issues/files/827659/wanscam.hw0021.json.txt)
![wanscam hw0045](https://cloud.githubusercontent.com/assets/12999602/23705152/b12c591a-0408-11e7-84d4-5a66acb80100.jpg)
[wanscam.hw0045.json.txt](https://github.com/jeedom/issues/files/827660/wanscam.hw0045.json.txt)

**Comment by zoic21** [comment]
Bonjour,
Merci pour les configurations elles seront disponible sur la prochaine version stable du plugin.
