### ISSUE TITLE
Utilisation de mots clés réservé

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#214]
Salut,
Le mot clé "Object" est utilisé pour désigner une class dans le corps de jeedom, par ailleurs elle n'a pas un nom très explicite sur sa fonction.
Voici ce que dit la doc de php:
[http://php.net/manual/fr/reserved.other-reserved-words.php](url)
 La liste des mots suivants ont une particularité. Bien qu'ils puissent être utilisés dans les noms de classe, d'interface, et de trait (mais aussi dans les espaces de noms), il convient d'éviter de les utiliser sachant qu'ils peuvent être utilisés dans les futures versions de PHP.

Soft reserved words resource (depuis PHP 7) 	object (depuis PHP 7) 	mixed (depuis PHP 7) 	numeric (depuis PHP 7)

**Comment by zoic21** [comment]
Bonjour,
Je suis au courant malheureusement object est trop utilisé pour qu'on puisse faire le changement. J'ai testé avec php7 pas de soucis Jeedom tourne dessus. Ceci n'est donc pas bloquant pour le moment.
