### ISSUE TITLE
[SCENARIO] Les modifications de nom de scénario ne sont pas prises automatiquement en compte

### ISSUE THREAD

**Issue by diving91** [jeedom/issues#215]
- la version de jeedom: 2.4.6
- Browser Firefox 51.0.1

Bonjour,

Lorsque l'on modifie le nom d'un scénario, le nouveau nom n'est pas pris en compte immédiatement.
Il faut désactiver et réactiver le scénario pour que le changement de nom ai lieu

Dans la liste des scénarios sur le dashboard '(liste a droite), l'ancien nom est affiché, même avec un refresh complet du dashboard - tant que l'on ne désactive pas et réactive le scénario

Diving91

**Comment by zoic21** [comment]
Bonjour,
Corrigé en 3.0.X

**Comment by diving91** [comment]
wahou .... Génial. Merci beaucoup.
