### ISSUE TITLE
[Plugin MODE] Changement de nom d'un mode non répercuté

### ISSUE THREAD

**Issue by diving91** [jeedom/issues#216]
- la version de jeedom: stable 2.4.6

Lorsque l'on change le nom d'un Mode, celui-ci ne se répercute pas par exemple dans un scénario qui utilise ce Mode et on trouve son ID à la place.

Exemple:
- Mode avec pour nom "Normal"
Commande visible dans un scénario
#[Personnes][Présence][Normal]#

- Modification du nom du Mode "Normal" en "Present"
Commande visible dans un scénario
#458# (cette commande ne se déclenche jamais bien sûr)

- Il faut recréer la commande dans le scénario pour avoir:
#[Personnes][Présence][Present]#

diving91

**Comment by zoic21** [comment]
Bonjour,
Oui c'est malheureusement quelques chose que je ne sais pas corriger.

**Comment by diving91** [comment]
Alors je me méfierai si jamais je change le nom d'un Mode. Ce n'est pas capital non plus, mais il faut le savoir
