### ISSUE TITLE
[BETA][CORE] Configuration du design : visualisation, modification taille impossible

### ISSUE THREAD

**Issue by phifi92** [jeedom/issues#217]
Souci confirmé par 3 bêta-testeurs

Lors de la création d'un nouveau, ou duplication ou modification d'un design existant. Il est impossible dans "Configuration du design"  : 
- de visualiser la taille déjà définie (les 2 input L et H sont vides)
- de modifier la taille d'un design : après avoir renseigné les tailles LxH, les valeurs ne sont pas prises en comptes.

Exemple suite duplication d'un design existant : 
- Configuration du design : les input LxH sont vide
- dans la BdD j'ai bien : {"desktopSizeX":"760","desktopSizeY":"1000","icon":"","enableOnMobile":"1","noReturnFullScreen":"1","tabletteProportion":"1","mobileProportion":"1"}
- si je modifie les valeurs LxH dans "Configuration du design"
- le design ne change pas de taille (visuellement)
- dans la BdD, aucun changement : {"desktopSizeX":"760","desktopSizeY":"1000","icon":"","enableOnMobile":"1","noReturnFullScreen":"1","tabletteProportion":"1","mobileProportion":"1"}

Toutefois, la modification direct dans la BdD est bien prise en compte.

**Comment by zoic21** [comment]
Bonjour,
Corrigé

**Comment by phifi92** [comment]
test concluant, merci
