### ISSUE TITLE
[CORE][SCENARIO]scenario programmé et bloc "A" qui génère une tâche programmée à la mauvaise heure

### ISSUE THREAD

**Issue by diving91** [jeedom/issues#219]
- la version de jeedom: 2.4.6 Stable
- une capture d'écran: [https://www.jeedom.com/forum/viewtopic.php?f=32&t=25430](url)
Le scénario de départ est documenté dans le post ci-dessus sur le forum.

A force d'essai pour isoler ce qui ne fonctionne pas, je pense que les conditions suivantes d'un scénario programmé et un Bloc "A" ne fonctionnent pas:
* scénario programmé "1 0 * * *" et un bloc "A" 1722 -> ça génère une tâche au 01/01/1970
* scénario programmé "1 16 * * *" et un bloc "A" 1722 -> ça génère la bonne tâche (visible dans moteur de tâche) mais elle ne s’exécute jamais (visible dans le log du scenario)

cas général:
* Un bloc "A" n'aime pas un scenario programmé par un cron "x y * * *" où x !=0
*  Un bloc "A" n'aime pas un scenario programmé par un cron où y==0

code du scénario pour le premier cas:

`
- Nom du scénario : test
- Objet parent : Jardin
- Mode du scénario : schedule
    - Programmation : 1 0 * * *

    SI 1 == 1
    ALORS
         
        A 1722
        FAIRE
         #[Système][Envoi Email][Email de la Maison]# - Options : Array
        (
            [enable] => 1
            [title] => Test cron A
            [message] => Poubelles
        )
    SINON`

**Comment by zoic21** [comment]
Bonjour,

Ya déjà un cas qu'on peu éliminer un bloc A dans un scénario lancer toute les minute ça ne marchera jamais c'est tout a fait normale.
Pour l'autre cas je regarderais a l'occasion.

**Comment by diving91** [comment]
ah oui, pas utile le cas toutes les minutes - j'ai du mal m'exprimer. mes cas qui ne fonctionnent pas:
cron tous les jours à 00h01 et bloc "A" 17h22-> produit une tache programmée au 01/01/1970 (c'est le code du scenario que j'ai mis dans le premier post ci-dessus)
cron tous les jours à 16h01 et bloc "A" 17h22 -> produit bien une tache programmée le jour même pour 17h22 mais qui ne s’exécute jamais
alors que cron tous les jours à 16h00 et bloc "A" 17h22-> OK

**Comment by zoic21** [comment]
Bonjour,
Je viens de tester chez moi pas de soucis ca semble tout ok, mais je suis en version 3.0 et il y a eu des changement sur le caclul des crons mises a jour de sous librairie. Je continu de faire des tests mais si il sont ok alors je fermerais l'issue.

**Comment by diving91** [comment]
Bonjour,
Merci - Si c'est corrigé en 3.0 alors nickel. je referai des tests quand la 3.0 sera dispo en stable
