### ISSUE TITLE
[INSTALLATION NETINSTALL] RPI3 et NetInstall : problème avec IPv6

### ISSUE THREAD

**Issue by petoulachi** [jeedom/issues#220]
Salut à vous,

remarqué hier en faisant une install neuve sur un RPI3 connecté en wifi, en utilisant la dernière image netinstall dispo ; dans la config jeedom, au niveau du réseau, il s'obstine à vouloir prendre l'IPv6 de l'interface eth0 qui n'a pas d'IPv4 assigné, et ignore l'IPv4 présente sur l'interface wlan0.
Même en mettant à la main l'IPv4, au reboot le paramètre est revenu sur l'IPv6. Dans l'absolu ce ne serait pas génant, mais des plugin comme MySensors plante lorsqu'il essaie d'utiliser l'IPv6 (je pense qu'il s'attend à une ipv4).

Rajouter ces 3 lignes :
`net.ipv6.conf.all.disable_ipv6 = 1`
`net.ipv6.conf.default.disable_ipv6 = 1`
`net.ipv6.conf.lo.disable_ipv6 = 1`

à la fin du fichier /etc/sysctl.conf m'a permis de désactiver totalement l'ipv6 et ne plus avoir de soucis.

A noter, j'ai pas eu le soucis si j'utilise la pi3 avec l'interface eth0. Dans ce cas, même si l'ipv6 est activé, jeedom se comporte normalement !

**Comment by zoic21** [comment]
Bonjour,
Jeedom doit supporter l'ipv6 je ne le désactiverais donc pas c'est a corriger dans les plugins donc.
