### ISSUE TITLE
 [BETA] [CORE]Erreur SQL Enregistrement d'une vue avec une zone tableau

### ISSUE THREAD

**Issue by Ethal** [jeedom/issues#223]
Bonjour,
Config : VM debian jessie, beta version 3.0.8 , fresh install fait ce jour en utilisant le script install.sh, uniquement plugin virtuel installé en stable,

Lorsque je souhaites enregistrer une vue contenant une zone tableau , j'ai le message suivant [MySQL] Error code : 23000 (1048). Column 'link_id' cannot be null 
(voir copie d'écran si dessous) 

![erreur sql vue tableau](https://cloud.githubusercontent.com/assets/15526508/24236859/05bdf2da-0fa4-11e7-8bb0-4a596458bda6.png)

**Comment by zoic21** [comment]
Bonjour,
Je viens de faire une correction sur le script d'installation de la bdd mais je doute que le soucis vienne de la. Vu que je reproduis pas je ferme et rouvrirais si d'autre reproduisent.

**Comment by Ethal** [comment]
Bonjour,
la modif a corrigé le problème chez moi.
