### ISSUE TITLE
Http2 support

### ISSUE THREAD

**Issue by EtienneDeneuve** [jeedom/issues#224]
Bonjour à tous,

J'ai tenté de passe jeedom en http2, visiblement les temps de chargements sont encore plus long qu'avant. 
Le support du http2 permettrais pas mal de chose...

**Comment by zoic21** [comment]
Bonjour,
Le http2 est surtout au niveau du serveur web (apache) et non de jeedom. Nous ne pouvons rien y faire surtout que nous ne testons pas encore cela on verra d'ici 1ans le temps que ca soit bien implémenté partout.

**Comment by EtienneDeneuve** [comment]
Salut Loïc,

C'est bien côté Apache, sauf que c'est pas vraiment Apache qui aime pas mais bien jeedom. Je vais continuer de creusé le sujet, ca correspond à une refonte de mon infra chez moi, je passe tout en http2 pour gérer l'ensemble de mes certificats via let's encrypt. Je vais tenter via un reverse proxy pour voir si j'ai toujours les mêmes dysfonctionnement.
Comment puis je te transmettre mes modification ? Dois je faire un fork ?

Etienne

Envoyé de mon iPhone

Le 27 mars 2017 à 11:32, Loïc <notifications@github.com<mailto:notifications@github.com>> a écrit :


Bonjour,
Le http2 est surtout au niveau du serveur web (apache) et non de jeedom. Nous ne pouvons rien y faire surtout que nous ne testons pas encore cela on verra d'ici 1ans le temps que ca soit bien implémenté partout.

**Comment by zoic21** [comment]
Il faut faire un fork effectivement puis un merge request mais je vois pas trop ce qui peut gêner dans Jeedom

**Comment by EtienneDeneuve** [comment]
Je vais éplucher mes logs et te faire une petite liste ;)

Envoyé de mon iPhone

Le 27 mars 2017 à 11:37, Loïc <notifications@github.com<mailto:notifications@github.com>> a écrit :


Il faut faire un fork effectivement puis un merge request mais je vois pas trop ce qui peut gêner dans Jeedom
