### ISSUE TITLE
[SCENARIO][SUGGESTION]

### ISSUE THREAD

**Issue by caplam** [jeedom/issues#225]
Les blocs code dans les scénarios permettent beaucoup de choses et je les utilise de plus en plus.
Cependant l'éditeur est plutôt limité.
Je lance donc une suggestion qui serait de rendre accessible le fichier des scenarios à un éditeur tiers via sftp pour pouvoir bénéficier de toutes les fonctionnalités d'éditeurs comme sublime text ou notepad++.
Une deuxième idée serait de donner la possibilité d'ecrire des scenarios comme des fonctions et de les appeler avec des arguments depuis un autre scenario

**Comment by zoic21** [comment]
Bonjour,
Il n'y a pas de fichier scenario tout est repartie dans 3 tables de la base je ne peux donc pas faire de fichier...
Pour l'autre demande c'est dans la 3.0

**Comment by caplam** [comment]
Bonjour,
merci de ta réponse.
Super pour la 3.0.
