### ISSUE TITLE
Les fichiers du dossier  sysinfodsqg89sd4fg231sd6f8gs6dfg21

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#227]
S'agit-il de bibliothèques externe ou on elle été développé pour jeedom.
En gros puis-je corriger des bugs ou loïc se charge des mettre à jours régulièrement ?

**Comment by zoic21** [comment]
C'est une lib externe je mets donc a jour de temps en temps celle-ci. Il ne faut rien toucher dedans.

**Comment by ColonelMoutarde** [comment]
Elle est disponible avec composer apparemment, tu devrais la mettre dans
les dépendances du projet.

Cordialement,
Luc SANCHEZ

2017-04-27 16:55 GMT+02:00 Loïc <notifications@github.com>:

**Comment by zoic21** [comment]
Oui ya un package composer mais je peux pas m'en servir car phpsysinfo n'a pas de mod embedded donc je fais une iframe pour l'afficher d'ou le nom de dossier complexe qui change a chaque mise a jour de jeedom pour eviter les failles de sécurité.
