### ISSUE TITLE
[MOBILE][BETA] Impossible de rentrer dans 1 pièce

### ISSUE THREAD

**Issue by magicgg91** [jeedom/issues#23]
Application Android 0.89
Core 2.3.5 à jour du 07/07/2016 + plugin mobile à jour

Sur la page des pièces, affichage en mode carré
Je rentre dans 1 pièce, OK
Je sors de la pièce et reviens à la page des pièces, OK
Je veux rentrer dans 1 autre pièce, KO

Le problème ne se produit pas systématiquement...

**Comment by rocket13011** [comment]
je m'en occupe pour la 1.1
