### ISSUE TITLE
[BETA] [CORE]Module en alerte

### ISSUE THREAD

**Issue by Ethal** [jeedom/issues#231]
Bonjour,
Config : VM debian jessie, beta version 3.0.9 ,chrome 58

Dans la page "Equipement (anciennement batterie)" , Onglet "Module en alerte" le widget n'est pas visible ou du moins étrangement , on voit les "actions", mais pas les "cmd" lors d'une alerte configurée , 

Pas de soucis sur le dashboard,le widget passe bien en Warning(orange) ou Danger(rouge)
j'ai fait le test à partir d'un équipement virtuel.

En regardant le code HTML de la page equipement, j'ai width et Height à 0px sur le div du widget (voir ci dessous)

`<div class="eqLogic eqLogic-widget allowResize allowReorderCmd jeedomAlreadyPosition" data-eqlogic_id="1" data-eqlogic_uid="eqLogic1____2052990501____" data-version="dashboard" style="border: none; border-radius: 4px; background-color: rgb(255, 171, 0); color: rgb(255, 255, 255); width: 0px; height: 0px; margin: 0px; padding: 0px; position: absolute; left: 0px; top: 0px;" data-category="automatism">`

j'ai regarder dans le code du Core, mais je ne maitrise pas tout ,
la difference que j'ai vu , c'est que pour la page dashboard on utilise pour l'affichage
echo '<script>getObjectHtml(' . $child->getId() . ')</script>';

pour l'onglet Module en alerte , on utilise
echo $eqLogic->toHtml('dashboard');

Cordialement.

**Comment by zoic21** [comment]
Bonjour,
Serait-il possible d'avoir une capture ?

**Comment by Ethal** [comment]
Bonjour,
Widget sur le dashboard,
![dasboard](https://cloud.githubusercontent.com/assets/15526508/25649884/42c0f380-2fd9-11e7-89ed-a478283911e1.png)

Widget sur l'onglet "module en alerte"
![module en alerte](https://cloud.githubusercontent.com/assets/15526508/25649913/679194d0-2fd9-11e7-8d49-59da5afa3acc.png)

**Comment by Ethal** [comment]
Bonjour,
un petit complément d'information, 
j'ai le même soucis avec FireFox 53, 
depuis chrome, 
Quand je fais "afficher le code source de la page"  width et height sont égale à auto
c'est quand je fais "inspecter l'élement" que j'ai width et height à 0px,

y aurait il pas un script js fautif ?

**Comment by zoic21** [comment]
Serait-il possible d'avoir un accès au jeedom ?

**Comment by Ethal** [comment]
oui pas de soucis , la VM également ou uniquement l'interface ? 
faudrait me donner un email pour que je vous envoie les données de connection.

**Comment by zoic21** [comment]
Le mieux est d'écrire au support. Je réceptionnerais la demande.

**Comment by Ethal** [comment]
j'ai envoyé un mail a s..@j.. car je n'ai pas acces a au ticket car j'ai un profil betatesteur

**Comment by zoic21** [comment]
Bonjour,
Je n'ai rien recu il faut l'envoyer a l’adresse de contact

**Comment by Ethal** [comment]
Bonjour,
je viens de vous envoyer un message à l'adresse indiquée
Cordialement,

**Comment by zoic21** [comment]
Toujours rien.... En mp sur le forum sinon.

**Comment by Ethal** [comment]
Bonjour,
message en MP sur le forum fait

**Comment by zoic21** [comment]
C'est bon j'ai corrigé il suffit de forcer la mise à jour de jeedom. Merci pour le retour.

**Comment by Ethal** [comment]
Bonjour,
La mise à jour forcé n'a pas reglé le soucis ,
j'ai verifié en local , j'ai bien les derniers commit (utils.js,eqlogic.class.php)
et j'ai vider les caches de mes navigateurs

Ton acces est tjrs ouvert

**Comment by zoic21** [comment]
Et la ?

**Comment by Ethal** [comment]
ça fonctionne nickel, voir ci-dessous, merci
![module en alerte resolu](https://cloud.githubusercontent.com/assets/15526508/25712094/f6a54e38-30f0-11e7-8731-f940d3183a16.png)
