### ISSUE TITLE
[BETA][CORE] Date hard codée

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#232]
En ligne 575 de la class jeedom.class.php il y a des dates hard codées, il sera plus judicideux les mettre en flottantes non ?

**Comment by zoic21** [comment]
Bonjour,
Non la c'est pour détecter si le systeme est pas l'heure lors d'un reboot. Comme les RPI qui quand il boot sont dans les années 70 (d'autre dans les année 90 ou même 2010).
