### ISSUE TITLE
[CORE] build error sur la branche stable v2.4

### ISSUE THREAD

**Issue by trinitrotoluene76** [jeedom/issues#233]
Bonjour,
pourquoi le readme.md de la branche stable v2.4 fait apparaître un "build error"?
([https://github.com/jeedom/core/tree/stable](https://github.com/jeedom/core/tree/stable))
C'est un peu perturbant pour une branche dite stable. 
Je suppose que c'est à cause du lien non conditionné vers travis? (car sur le page [https://travis-ci.org/jeedom/core/branches](url) on voit que la 2.4 passe le test ainsi que la branche "master").
Bien à vous,
Amaury.

**Comment by zoic21** [comment]
Bonjour,
Oui le lien était pour la branche master, j'ai changé mais vu que la stable est en failed et qu'il faut faire des corrections pour que travis passe ça restera en erreur jusqu'a la sortie de la 3.0
