### ISSUE TITLE
[CORE] Problème de sauvegarde

### ISSUE THREAD

**Issue by esseki** [jeedom/issues#236]
- la version de jeedom (si c'est une bêta la date de dernière mise à jour) : **Jeedom 2.4.6**
- la liste des plugins ainsi que leur date de mise à jour : le problème concerne le core et plus particulièrement la commande tar impliquée dans le script de sauvegarde,donc je ne pense pas que ce soit nécessaire
- le log nginx.error ou http.error : je fournis tous les logs nécessaires dans mon message ci dessous.

Bonjour,

je suis sur un Jeedom DIY. Et depuis plusieurs jours, les sauvegardes Jeedom ne fonctionnent plus . Voici un log pour illustrer mon problème : [log.txt](https://github.com/jeedom/issues/files/992289/log.txt)

J'ai donc mis les mains dans le cambouis et je suis allé voir ce qui se passe dans le fichier "/var/www/html/install/backup.php" pour expliquer ce message d'erreur trouvé dans le log :

_Erreur durant la sauvegarde : Echec lors de la compression de la sauvegarde. Sauvegarde introuvable : /var/www/html/core/php/../../backup/backup-Jeedom-2.4.6-2017-05-07-15h33.tar.gzDétails : Array
(
)_

Dans mon cas ce message d'erreur est dû au fait que la commande tar ne réussit pas à créer l'archive. Jusque là c'est logique me direz-vous.
Un premier problème avec le log tel qu'il est stocké, c'est qu'il ne remonte pas le retour d'erreur de la commande tar qui échoue (à cause de "_> /dev/null 2>&1_" dans le code source). Il suffirait de supprimer la redirection de la sortie d'erreur pour que l'erreur de la commande tar apparaisse dans le log de jeedom. C'est pas pratique il a fallu que j'aille modifier le code pour pouvoir mettre la main sur l'erreur. Bref, chez moi la commande tar échoue avec le message d'erreur suivant :

_Création de l'archive...tar: Conflicting compression options
Try 'tar --help' or 'tar --usage' for more information._

J'ai passé pas mal de temps à chercher la raison du message "Conflicting compression options" sans rien trouver qui corresponde à mon cas.
J'ai donc persévéré et je me suis dit : "on va y aller par étape". Je vais changer le code de Jeedom pour faire un tar sans compression :

`system('cd ' . $tmp . '; tar cf ' . $backup_dir . '/' . $bakcup_name . ' * > /dev/null 2>&1');`

Et là quelle ne fut pas ma surprise de constater que la commande continue à planter.
Pour mieux comprendre, je me suis amusé à lancer des commandes tar modifiées à la main. J'ai obtenu les résultats suivants : 

`tar cfz /var/www/html/core/php/../../backup/backup-Jeedom-2.4.6-2017-05-09-17h11.tar.gz *
tar: Conflicting compression options
Try 'tar --help' or 'tar --usage' for more information.`

`tar cf /var/www/html/core/php/../../backup/backup-Jeedom-2.4.6-2017-05-09-17h11.tar.gz *
tar (child): index.php: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now`

`tar cvf /var/www/html/core/php/../../backup/backup-Jeedom-2.4.6-2017-05-09-17h11.tar.gz *
tar (child): index.php: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
3rdparty/
3rdparty/jquery.unveil/
3rdparty/jquery.unveil/jquery.unveil.min.js
3rdparty/php.js/
3rdparty/php.js/php.min.js`

J'en suis arrivé à la conclusion qu'il y avait peut être un problème avec la syntaxe de la commande tar utilisée dans Jeedom. J'ai donc essayé la syntaxe suivante :

`tar cfz /var/www/html/core/php/../../backup/backup-Jeedom-2.4.6-2017-05-09-17h11.tar.gz ./*`

Et la commande est passée !

Du coup si je modifie le code du fichier "/var/www/html/install/backup.php" comme ci dessous les sauvegardes refonctionnent chez moi !

AVANT 
`echo __('Création de l\'archive...', __FILE__);
system('cd ' . $tmp . '; tar cfz ' . $backup_dir . '/' . $bakcup_name . ' * > /dev/null 2>&1');
echo __("OK", __FILE__) . "\n";`

APRES
`echo __('Création de l\'archive...', __FILE__);
system('cd ' . $tmp . '; tar cfz ' . $backup_dir . '/' . $bakcup_name . ' ./* > /dev/null 2>&1');
echo __("OK", __FILE__) . "\n";`

Le problème c'est qu'à la prochaine mise à jour de Jeedom, ma modification risque de disparaitre. Du coup je voulais demander leur avis à l'équipe de Devs, est ce qu'ils confirment le problème ci dessus ? Dans ce cas pourraient ils le corriger dans une prochaine version ?

Merci d'avance pour votre retrour :)

**Comment by zoic21** [comment]
Bonjour,
Qu'elle la version de tar ? Car je pense que ca vient de la je pense.

**Comment by esseki** [comment]
Bonjour,

voici ma version de tar 

`tar --version`
`tar (GNU tar) 1.27.1`

Pour info et comme je le craignais, je n'ai plus de backup depuis le passage en 3.0.6 étant donné que mes modifs dans le fichier "/var/www/html/install/backup.php" ont été écrasées par la mise à jour.

Les messages d'erreurs dans les logs sont un peu différents mais c'est surtout du à la nouvelle version du code. Le problème est le même. La commande tar qui échoue.

**Comment by zoic21** [comment]
Je pense le soucis vient de la, en 1.29 pas de soucis...
