### ISSUE TITLE
[BETA] [CORE]CheckCmdUpdate

### ISSUE THREAD

**Issue by Ethal** [jeedom/issues#237]
Bonjour ,
Pouvez vous regarder cette échange avec lunarock
[https://github.com/lunarok/jeedom_vigilancemeteo/pull/33](https://github.com/lunarok/jeedom_vigilancemeteo/pull/33)

il semble que lorsque l'on écrit 0(zéro) dans une commande avec la function cmdcheckandupdate de la class equipement, la "lecture" (ie cmdexecd) de la commande envoie null et non 0(zéro) 

Merci

**Comment by zoic21** [comment]
Bonjour,
C'est corrigé en version 3
