### ISSUE TITLE
[BETA][CORE]Design X Y

### ISSUE THREAD

**Issue by DanoneKiD** [jeedom/issues#238]
Bonjour,

Il y a apparemment un inversion entre **Position X** et **Position Y** dans la config d'un widget sur un design.

_D'ailleurs pourquoi la position n'est-elle pas exprimée en **px** ? Ce serait plus simple pour positionner précisément un objet, non ?._

![image](https://cloud.githubusercontent.com/assets/522809/25992202/24804aa4-3706-11e7-96eb-924aab108d11.png)

**Comment by zoic21** [comment]
Bonjour,
Effectivement ca sera corrigé en 3.1, pour le % c'est normal c'est stocké comme ca en base pour ne pas etre dépendant de la taille des écrans.
