### ISSUE TITLE
[BETA] [CORE]Interaction

### ISSUE THREAD

**Issue by Ethal** [jeedom/issues#239]
Bonjour ,

Config : VM debian jessie, beta version 3.0.9 ,chrome 58, mise a jour forcé fait le 16 Mai,

Lorsque l'on ajoute une action de type "scenario", pause,... (ie tout ce qui n'est pas d'un equipément) , lors de l'enregistrement, celle ci est "doublé".
voir screenshot ci dessous,

![action interaction](https://cloud.githubusercontent.com/assets/15526508/26145197/d406cafa-3aeb-11e7-93ce-c7559e98c3b6.png)

et lorsque l'on rappel l'interaction on a l'erreur PHP suivante dans le log htpp.error:
`Array to string conversion in /var/www/html/core/php/utils.inc.php on line 77`

**Comment by zoic21** [comment]
Bonjour,
Je n'arrive pas a reproduire.

**Comment by Ethal** [comment]
Bonjour,
c'est bizarre ;)  , et je ne suis pas le seul , il y a un sujet d'ouvert sur le forum, j'ai le meme soucis sur la 3.09 stable sortie récemment, et la 3.1 en beta 
c'est quand on click sur "Enregistrer" que le champs est doublé, 

Si vous souhaitez un acces à mon jeedom de test(ie 3.1 beta), faites le moi savoir, 

Cordialement,

**Comment by Lorenzo99999** [comment]
Bonjour je me permets de rebondir sur le bug. Avant la 3.0 j'avais chaque action qui étaient doublées à l'enregistrement. Apparemment, c'était lié à Firefox, mais là il s'agit de la partie de droite.

J'ai testé sous Firefox, chrome et Edge et le résultat est le même.
Cf mes copies.

![bug_interact](https://user-images.githubusercontent.com/22962254/27917296-eadf5efc-626b-11e7-9850-c5a51cbca562.png)

![bug_interact_exemple2](https://user-images.githubusercontent.com/22962254/27917302-ecfe8a82-626b-11e7-95a0-9cbe84c0f47b.png)
