### ISSUE TITLE
[PLUGIN][NETWORKS] WakeOnLan ne marche pas lorsqu'il y a plusieurs interfaces réseau

### ISSUE THREAD

**Issue by Turgon37** [jeedom/issues#240]
Bonjour,

Le WakeOnLan sur mon raspberry pi 3 ne fonctionne pas avec le plugins networks, le paquet WOL est refusé par le message suivant :

PHP Warning:  socket_sendto(): unable to write to socket [101]: Network is unreachable in /var/www/html/plugins/networks/vendor/tomnomnom/phpwol/Phpwol/Socket.php on line 8

J'ai trouvé la cause du souci, mon raspberry pi possède plusieurs interfaces réseau virtuelle et l'option de socket MSG_DONTROUTE dans la bibliothèque https://github.com/tomnomnom/phpwol/blob/0.1.0/Phpwol/Socket.php utilisé par le plugin pose problème. 

Même si la nouvelle version de bibliotheque intègre le correctif je vous propose une amélioration du plugin. Remplacer la bibliothèque PHPWol par la commande wakeonlan. Je constate que cette dernière est déjà installée via les dépendances, vous pourriez utiliser le code fournit dans le patch ci-joint pour l'utiliser.

Informations Jeedom
- Version : 2.4.6
- networks	2016-10-28 11:35:09

[networks.class.php.patch.txt](https://github.com/jeedom/issues/files/1069421/networks.class.php.patch.txt)

**Comment by magicgg91** [comment]
Bonjour,
Tu essayes de réveiller quel périphérique ?
Un Raspberry ne peut pas être réveillé en wol.
Et le plugin fonctionne très bien en l'état sur un RPi3.

**Comment by Turgon37** [comment]
Je chercher à reveiller un NAS Synology DS414. Effectivement le WOL marche bien sur un PI3 mais pas sur le mien car comme je l'ai dit j'ai plusieurs interfaces réseaux Ethernet dessus. Et visiblement le socket UDP ouvert par la bibliotheque PHP fournit avec le plugin ne fonctionne pas.
Chez moi je me suis contenté de mettre à jour la biblioteque car la derniere version corrige le probleme. Mais l'amélioration que je propose permettrait de se passer de cette lib car finalement la commande wakeonlan a toujours marché chez moi.

**Comment by zoic21** [comment]
J'ai mis a jour la lib, ca devrait etre bon dans la prochaine stable donc.
