### ISSUE TITLE
[MOBILE][BETA] Generic-type pour Store Banne

### ISSUE THREAD

**Issue by gunsails** [jeedom/issues#241]
Ajout d'un type générique type pour les stores bannes de terrasse afin d'avoir un truc plus sexy sur App mobile Jeedom

Prise en compte dans l'app mobile:
 Etat: Opened (255), Closed (0).
 Commandes: Open, Close et Stop. 

Pour les commandes je sais pas comment tu gères mais si on passe par un relay style Fibaro, une seule commande gère Open, Close et Stop. 

Merci !

**Comment by gunsails** [comment]
pour inspiration 

<div style="width:110px;min-height:60px;" class="cmd #history# tooltips cmd-widget" data-type="info" data-subtype="numeric" data-cmd_id="#id#" title="#collectDate#">
    <center><span id="iconCmd#id#"></span></center>
    <script>
		var state 	= parseFloat('#state#');
		var niveau 	= 0;
		if(state == 0) {
			niveau = 0;
		} else if(state > 0 && state <= 10 ) {
			niveau = 10;
		} else if(state > 10 && state <= 20 ) {
			niveau = 20;
		} else if(state > 20 && state <= 30 ) {
			niveau = 30;
		} else if(state > 30 && state <= 40 ) {
			niveau = 40;   
		} else if(state > 40 && state <= 50 ) {
			niveau = 50;
		} else if(state > 50 && state <= 60 ) {
			niveau = 60;
		} else if(state > 60 && state <= 70 ) {
			niveau = 70;
		} else if(state > 70 && state <= 80 ) {
			niveau = 80;
		} else if(state > 80 && state <= 90 ) {
			niveau = 90;
		} else if(state > 90) {
			niveau = 100;
		}
		$('#iconCmd#id#').append('<img src="plugins/widget/core/template/dashboard/cmd.info.numeric.StoreExt/StoreExt_'+niveau+'.png" />');
    </script>
</div>

**Comment by rocket13011** [comment]
on part sur issue-app
