### ISSUE TITLE
[MOBILE][BETA] PHP Deprecated 

### ISSUE THREAD

**Issue by ludomin** [jeedom/issues#242]
- Jeedom 3.09
- Mobile 2017-06-16 12:21:53
- http.error : 
[Fri Jun 16 17:10:22.556804 2017] [:error] [pid 4677] [client 80.12.27.234:53383] PHP Deprecated:  $_sendNodeJsEvent is deprecated in /var/www/html/core/class/cmd.class.php on line 773
[Fri Jun 16 17:10:45.986401 2017] [:error] [pid 32366] [client 80.12.27.234:53384] PHP Deprecated:  $_sendNodeJsEvent is deprecated in /var/www/html/core/class/cmd.class.php on line 773

Lors de l'ouverture de l'app mobile, des dizaines de lignes de ce genre sont générés au niveau log

**Comment by ColonelMoutarde** [comment]
Salut, c'est normal, si tu va voir dans le code, en ligne 780 tu verra que l'argument numéro 2 est déprécié et que donc tu as une ligne qui est ajouté dans tes logs à chaque fois qu'un argument autre que false est mis à cet emplacement.

**Comment by ColonelMoutarde** [comment]
PHP 7 ajoute le support des déclarations du type de retours. De façon similaire aux déclarations du type des arguments, les déclarations du type de retour spécifie le type de la valeur qui sera retournée par une fonction. Les mêmes types sont disponibles pour le typage du retour que pour le typage des arguments.

Le typage strict affecte aussi les déclarations du type de retour. Dans le mode faible par défaut, les valeurs retournées seront trans-typés vers le type demandé si elles ne sont pas déjà de celui ci. Dans le mode strict, la valeur retournée doit être du bon type sinon une exception TypeError sera levée.
