### ISSUE TITLE
[CORE]Php7 

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#243]
Comme php7.0 est le pré-requis minimum de Jeedom, il serait extrêmement avantageux de commencer à utiliser le typages des méthodes petit à petit. 
On va beaucoup gagner en perfs. 
Le principal avantage c'est qu'on peux le faire méthode par méthode ou fonction par fonction.
Le projet peux continuer à vivre avec les deux façons de faire. 
Je pense que gagner des perfs à moindre frais sera très bien accepté. En particulier pour les personnes qui sont sur raspi.

L'idée serai de ne modifier que les méthodes/fonctions qu'on débug, ainsi le projet migre petit à petit.
Un example:
`<?php
class Tutu{
public function foo(): array {
return [];
 }

 public function bar(): DateTime { 
return null; // incorrect
 }
}`
J'attend vos retours constructifs

**Comment by NebzHB** [comment]
Tu parles bien de la Déclaration des types de retour et aussi éventuellement du type des arguments ?

intéressant à faire en effet mais grosse gestion d'erreur à mettre en place à certains endroits, il me semble aussi que les types de retours peuvent parfois être de différents types... à corriger aussi donc..

référence doc : [http://php.net/manual/fr/functions.returning-values.php](url)

**Comment by ColonelMoutarde** [comment]
Ce que tu dit est pour le type "stricte" mais on peux déjà se contenter de faire du type hinting, on va  beaucoup y gagner.

ps: ton lien renvoie vers une page de lyrics... comprend pas

**Comment by ColonelMoutarde** [comment]
PHP 7 ajoute le support des déclarations du type de retours. De façon similaire aux déclarations du type des arguments, les déclarations du type de retour spécifie le type de la valeur qui sera retournée par une fonction. Les mêmes types sont disponibles pour le typage du retour que pour le typage des arguments.

Le typage strict affecte aussi les déclarations du type de retour. Dans le mode faible par défaut, les valeurs retournées seront trans-typés vers le type demandé si elles ne sont pas déjà de celui ci. Dans le mode strict, la valeur retournée doit être du bon type sinon une exception TypeError sera levée.

**Comment by zoic21** [comment]
Attention jeedom c'est php 5.6 et 7.0 et pas encore que 7.0 donc pour l'instant nous ne pouvons faire ce genre de changement.
