### ISSUE TITLE
[core][bug] dans cmd.class.php

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#244]
Dans la méthode ::humanReadableToCmd()
en ligne 405, la variable $matches n'est pas initialisée donc le code de la ligne 406 à la ligne 419 ne s'exécute jamais !!!

Loic peux tu corriger ou supprimer ce code ?

**Comment by zoic21** [comment]
Bonjour,
Idem issue precedente

**Comment by ColonelMoutarde** [comment]
ok merci pour cette réponse
