### ISSUE TITLE
[CORE] classe cmd.class.php  BUG

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#245]
Salut,
En ligne 455 la variable $matches est appelé sans être initialisé ce qui veux dire que le foreach suivant n'est pas utilisé.

**Comment by zoic21** [comment]
Bonjour,
La fonction preg_match_all est un peu particulière elle va elle même initialiser la variable donc on passe bien dans la suite (et encore heureux c'est une des fonctions les plus importantes de jeedom)
