### ISSUE TITLE
[Z-WAVE] Values not updated from the Z-wave devices

### ISSUE THREAD

**Issue by clausdk** [jeedom/issues#249]
Problem:
It seems the problem with the values from the z-wave devices still exists in the new version 3. This problem has been there for awhile.

Example:

Here you see the values from a z-wave device
http://i.imgur.com/gmviv9z.png

and in the dashboard
http://i.imgur.com/6dS12k4.png

it shows the wrong values. You have to manually click on them to force an update.

This is the case in the mobile app. It shows the wrong value also.

Information about the system:
Core: SVN 89959e6  
Z-wave plugin version: SVN 49ea368 
Platform: Raspberry PI 3

**Comment by nechry** [comment]
check your commands mapping, ensure the instance is 1 not 0

**Comment by clausdk** [comment]
You mean this? http://i.imgur.com/XQRBz1I.png

**Comment by clausdk** [comment]
It seems like it is all or most of the devices. If you check the value reported in z-wave module setup it updates the value pretty quickly. But the values in the dashboard only changes if you manually click on it.

This is the devices we have:
http://i.imgur.com/7VkZe6D.png

If if take a couple of Fibaro Wallplugs. Its the same for them:
z-wave module setup page
http://i.imgur.com/9kYRmm5.png
and dashboard:
http://i.imgur.com/KiwvBtT.png

**Comment by nechry** [comment]
Check you network Configuration, the heal page, reboot your jeedom. And also check the Openzwave log file for errors

**Comment by clausdk** [comment]
I should have been more specific ... I think it is only related to on/off values. Other values seems to update just fine.

I'll check that. Thanks.

**Comment by clausdk** [comment]
Checked the logs. 

```
> 2017-07-08 20:10:14.866 Always, OpenZwave Version 1.4.0 Starting Up
> 2017-07-08 20:11:16.270 Error, Node037, ERROR: Dropping command, expected response not received after 1 attempt(s)
```
Health.php  gave me an OK

Restarted .. still not working so yeah idk.

**Comment by nechry** [comment]
Do you use custom widgets ? Check the commands directly form commands tab and also check the status also with test button. If at this level is ok, I thing is related to your widgets

**Comment by clausdk** [comment]
Nope, no custom widgets. Only using ones it automatically generates. The On/Off button widgets on the dashboard works, but their status does not. So yeah.

**Comment by nechry** [comment]
can i see your mapping

**Comment by clausdk** [comment]
Here's a few tests I did:

1)  When you restart the server/raspberry pi and let it boot up and finish the z-wave initial commands, on/off and dimmmer status's is not updateed to the current values.

2) If you manually activate the device by pressing the psychical button - the dashboard status updates...

3) When pressing the button on the dashboard it sometimes shows the wrong value, even tho it reports the correct value on the module setup page > values

**Comment by sarakha63** [comment]
it is impossible to reproduce your behavior.

what module is it ?

**Comment by clausdk** [comment]
I double checked what modules that does not report the change. 

Here's a few:
fgs221 double relay switch 2x1 5kw
![fgs221 double relay switch 2x1 5kw](https://user-images.githubusercontent.com/14122023/27989730-aa2aacf6-643f-11e7-829c-300744763202.png)

Powernode 6 port( ALL ON)
![powernode 6 port](https://user-images.githubusercontent.com/14122023/27989729-aa282b5c-643f-11e7-9d54-6cadc53bdab4.png)

As far as I can see... the values on the widgets is not updated with the values you find on the z-wave module page. The values on the module page seems to always be updated...

**Comment by clausdk** [comment]
I can report that the problem no longer exists in the latest beta versions of the plugin-openzwave / Jeedom core on Github. Good job. I also noticed that it ACTUALLY updates all the dashboard status widgets in the dashboard when the system is booting up. Good work.
