### ISSUE TITLE
[CORE] idée d'optimisation des requêtes

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#250]
Bonjour,

Je me suis rendu compte que le core lance beaucoup de requête genre :
`configuration` LIKE '%#3737#%'
`event` LIKE '%#3737#%'
`trigger` LIKE '%#3737#%'
Ca concerne :
cmd/value
listener/event
scenario/trigger
Et peut-être objet/configuration

Il me semblerait judicieux de faire une table (ou plusieurs) indexant les références.
Je veux bien préparer cette évolution.
Par contre, il faut valider la forme.
Plusieurs solutions possibles au moins :
1) une table avec toutes les ref.
1 | 2 | 3 | 4 | 5
-- | -- | -- | -- | --
type | field | id | dependency | IsExact
cmd | value | 12 | 35 | 1
listener | event | 65 | 22 | 0
scenario | trigger | 56 | 22 | 0
Je ne sais pas si le champ field est nécessaire.

2) une table de dépendence par type d'objet sinon les champs seront identique.
listener_dependency
cmd_dependency
object_dependency
scenario_dependency
...

Ensuite, il y a la maintenance de cette table. Je vois 2 solutions :
1) Modifier la fonction postSave et preRemove de chaque objet.
2) Créer des triggers mysql.

A+
Thomas

**Comment by zoic21** [comment]
Bonjour,
En soit l'idée est bonne mais pour l'avoir tester le gain de perf est pas énorme car les tables ne sont pas très grosse et ca amene une grosse complexité dans jeedom donc pour moi le jeux en vaut pas la chandelle.

En tout cas tes soucis de perf ne viennent pas de la c'est sur c'est comme ca depuis la v1...
