### ISSUE TITLE
[CORE] separate each JeedomBoard system with jeedom::getHardwareName()

### ISSUE THREAD

**Issue by NebzHB** [jeedom/issues#251]
At the moment, that method return just "JeedomBoard" for the mini, the ProV1, the ProV2 and the Smart, could you please separate each system ?

The purpose of it is to make different code for different system (ie not restarting dbus on ProV1 because it crash, assuming 1 jan 1970 on Smart but not ProV2 cause it has RTC, etc)

i would have made a PR but i don't know the internal differences between Smart and ProV2

**Comment by zoic21** [comment]
Hi,
Unfortunately this is not so simple. After several tests it was not reliable so we remain like this
