### ISSUE TITLE
[CORE] Problème de calcul sur le résumé global des objets

### ISSUE THREAD

**Issue by sybri** [jeedom/issues#252]
Jeedom Version 3.0.11
Il y a une erreur de calcul sur le résumé total des objets. Si bien que la moyenne bogue Il m'additione bien la valeur de l'humidité deux fois mais la divise par 1 étant donné qu'il y a un seul capteur en réalité.

Capteur 1 présent dans le résumé salon
Capteur 1 présent dans le résumé cuisine.

Les résumés cuisine et salon sont ok mais pas le résumé global.
![image 1](https://user-images.githubusercontent.com/458109/28321917-deba3a08-6bd4-11e7-8e03-8b8619101c8c.png)

## Config
![image 2](https://user-images.githubusercontent.com/458109/28321973-0b687c18-6bd5-11e7-9b81-7f1ceb2f05c9.png)

**Comment by zoic21** [comment]
Bonjour,
Un capteur utilisé 2 fois effectivement ca risque de bugué je regarderais mais on sort un peu de l'utilisation normal...

**Comment by sybri** [comment]
veut tu que je fasse une pull request pour la correction de ce bug ?

**Comment by zoic21** [comment]
Si tu l'as oui je veux bien

**Comment by sybri** [comment]
Je viens de déboguer. Mais au final, il n’y avait rien à corriger, seulement une erreur de configuration.  J'ai pu vérifier le calcul,  le capteur est considéré plusieurs fois ce qui donne un coefficient au capteur tous fonctionnent selon un principe simple. Désolé pour le dérangement.
