### ISSUE TITLE
PLUGIN SMS: Stabilité du démon avec modem huawei E220

### ISSUE THREAD

**Issue by Dany21000** [jeedom/issues#253]
Salut, 

Je dispose de deux jeedom, un physique RPi2, un virtuel (proxmox) en version 309.
Les deux disposent du plugin SMS à jour et sont connectés à des huawei e220 chez bouygues pour l'un, chez free pour l'autre.

Pour informations ces deux jeedom sont distants de 35km environ, essais croisés de cartes SIM et modems  effectués. J'ai aussi essayé d'autres E220 simlockés SFR.

Depuis au moins Juin 2016 et les versions jeedom/plugin SMS de l'époque, je rencontrais des erreurs du démon SMS qui plantait parfois au bout de 5 minutes, parfois au bout de plusieurs heures  (device not searching network) et qui semblait mal fermer le device /dev/ttyUSB*, du coup impossible de redémarrer le démon.

J'ai constaté que sans rien faire (envoi/réception de sms), le log se remplissait toutes les secondes de ligne : 
[2017-07-18 23:07:16][DEBUG] : response: ['+CREG: 0,1', 'OK']
[2017-07-18 23:07:17][DEBUG] : write: AT+CSQ

Alors j'ai modifié sur mes deux plateformes le fichier smsd.py à la ligne 106 : time.sleep(1)
en mettant 15 au lieu de 1.
Ce qui évite de trop bombarder le modem de commandes AT, le log indique bien lancer une commande AT toutes les 15s. Je pense que 30 serai aussi très bien.

Depuis Octobre dernier, le RPI2 distant semble très stable, il répond parfaitement aux interactions et son log est propre, le démon ne plante plus.
Le jeedom virtualisé lui aussi ne plante plus.

L'autre action que j'ai aussi effectuée est un chmod 777 /dev/ttyUSB*... 

Voilà, en espérant que ma modification puisse aider à améliorer.

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour, effectivement une trop grosse sollicitation de la clef peut amener des instabilités, je viens de pousser en beta une correction.
Merci encore pour le retour.
