### ISSUE TITLE
[API] JSON RPC object full

### ISSUE THREAD

**Issue by JLecorre12** [jeedom/issues#254]
Version de Jeedom : 3.0.11
Liste des plugins : z-wave
Log http.error : [(https://pastebin.com/ZXxruP7b)]

J'utilise l'api JSON RPC avec l'appel sur le object full, je rencontre un soucis quand j'essaye de faire des appels je me retrouve une fois sur deux avec une mauvaise valeur.

Exemple : 

J'ajoute une nouveau capteur z-wave depuis l'interface Jeedom en allant dans 

Plugins > Protocole domotique > Z-wave > Mode Inclusion

Je l'ajoute a nouvel objet quand je l'affiche sur le dashboard je vois bien les changements ce faire de ce coté la aucun soucis.

Le soucis apparaît quand j'essaye d’appeler la commande object::full avec l'api json rpc.

Je réalise une requête après un certains temps pour vérifier la liste des capteurs avec l'état de leurs commandes, le souci c'est que l'état ne ce mets pas tout de suite a jour.

Si l'état est à 0 au début et que je passe a 1 pendant la minute l'état devrais être à 1 sur le retour de la requête mais malheureusement l'état reste à 0 c'est que la minute suivante (2 minutes) que je vais avoir le bon résultat.

J'ai essayé de réduire et d'augmenter le temps entre chaque appel mais c'est toujours le deuxième appel après le changement d'état que je récupère la bonne valeur. J'ai aussi essayé avec des capteurs différents, virtuels ...
 
Code : 

Voici un code pour faire des tests

`````js
// https://www.npmjs.com/package/jayson
// npm install jayson
var jayson = require('jayson')

var apiKey = "" // key de l'api

var server = jayson.client.http({
        port: 80,
        path: '/core/api/jeeApi.php'
 })
  
 function objectFull () {
 	server.request('object::full', {apikey: apiKey}, function(err, response) {
		console.log(response.result)
        	// console.log('id reponse -->', response.result[0].eqLogics[1].cmds[0].id) // id d'une commande
        	// console.log('state reponse -->', response.result[0].eqLogics[1].cmds[0].state) // etat d'une commande
	})
 }
 
// appel de object::full
setInterval(function () { objectFulll() }, 60000)
`````

**Comment by zoic21** [comment]
Bonjour,
C'est normal il y a un systeme de cache + refresh à 1 minute pour cette demande car elle monopolise trop Jeedom et entraîne de fort ralentissement, elle n'est normalement a utilisé que une fois au démarrage de l'application puis ensuite il faut écouter les événements pour avoir les mises à jour.
