### ISSUE TITLE
[CORE] Page profil user, ajouter image preview themes manquants

### ISSUE THREAD

**Issue by Dany21000** [jeedom/issues#255]
Salut, 

Pour finaliser le produit et un aspect qui peut gêner certain utilisateur débutant, pourriez vous rajouter les images de prévisualisations des thèmes listés ci-dessous.

Ceci est du détail avec priorité zéro.

Je peux fournir les fichiers manquants mais il ne ressembleront pas au contenu déjà présenté sur les autres preview.... peut-être qu'il est intéressant de fournir un contenu différent sur les preview.

preview.png:1 GET http://192.168.50.231/jeedom/core/themes/bootable/desktop/preview.png 404 (Not Found)
preview.png:1 GET http://192.168.50.231/jeedom/core/themes/darkly/desktop/preview.png 404 (Not Found)
preview.png:1 GET http://192.168.50.231/jeedom/core/themes/paper/desktop/preview.png 404 (Not Found)
preview.png:1 GET http://192.168.50.231/jeedom/core/themes/walam/desktop/preview.png 404 (Not Found)

**Comment by zoic21** [comment]
Bonjour,
Si tu as les images pourquoi pas, je peux les ajouter.

**Comment by zoic21** [comment]
Bonjour,
Pas besoin que ça soit la page ou le même contenu il suffit juste de faire les captures de bien les nommer et normalement ça marche tout seul

**Comment by Dany21000** [comment]
![darkly_preview](https://user-images.githubusercontent.com/12201081/29703859-b1edb7d2-8977-11e7-8267-116739549305.png)
![paper_preview](https://user-images.githubusercontent.com/12201081/29703861-b2156304-8977-11e7-94ed-b6abb3e7d6fe.png)
![bootable_preview](https://user-images.githubusercontent.com/12201081/29703866-b505bba4-8977-11e7-9f78-41a74a4bd853.png)


Le thème Walam semble bugger chez moi.

**Comment by zoic21** [comment]
Bonjour,
C'est bon pour la 3.1
