### ISSUE TITLE
[CORE] interactions, revoir la présentation des filtres

### ISSUE THREAD

**Issue by Dany21000** [jeedom/issues#256]
Salut, 

Est ce que sur la page de création d'une interactions vous pourriez revoir la présentation des filtres ?

J'ai environ 40 interactions à reprendre suite à un changement de plugin et de protocole domotique.
C'est imbuvable, j'ai les yeux qui se croise sur les cases des filtres.

Pourriez vous reproduire le même principe que la page de configuration générale de v3.1.0 commitée cette semaine en beta... utiliser des onglets !

Et au lieu d'avoir une liste méchante de case à cocher pour les plugins, objets, etc... 
avoir une liste verticale propre et bien lisible avec les cases et leurs noms, avec pourquoi pas les icônes des plugins, des objets, des catégories, etc...

Aussi, quand on limite aux commandes de type info, automatiquement supprimer les sous-types de commandes de type action. Avec la réciproque, bien entendu.

Idem, quand on limite sur un équipement, automatiquement décocher (et empêcher de cocher) ce qui n'est pas lié à celui-ci.

Voilà encore une idée qui va vous donner un boulot de dingue.

**Comment by sarakha63** [comment]
Idée pas inintéressante. Nous sommes justement en ce moment sur des évolutions accès amélioration expérience utilisateur

**Comment by Dany21000** [comment]
[idee-interact.pdf](https://github.com/jeedom/issues/files/1160623/idee-interact.pdf)

**Comment by Dany21000** [comment]
[idee-interact.pptx](https://github.com/jeedom/issues/files/1160625/idee-interact.pptx)

**Comment by zoic21** [comment]
Bonjour,
La dernière version de jeedom (en beta) intègre déjà les onglets sur cette page, ce qui donne plus de place a la partie filtre. Je pense donc que pour le moment c'est suffisant a voir si on fait une refonte plus importante plus tard.
