### ISSUE TITLE
[CORE] Utilisation de SASS pour la gestion des css

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#257]
Pour simplifier les css et favoriser la maintenance, je suggérè d'utiliser SASS. J'attend vos retours.

**Comment by zoic21** [comment]
Bonjour,
Oui l'idée est bonne mais je n'ai pas les competences et le temps pour le faire ou le maintenir, je le note quand meme.

**Comment by ColonelMoutarde** [comment]
Salut,
L’avantage de sass c’est que la syntaxe css est entièrement compatible, c’est juste l’extension du fichier qui change. Du coup tu peux migrer petit à petit… les fichiers *.sass sont ensuite compilé en css compressé par exemple.

Cordialement,
Luc SANCHEZ

De : Loïc
Envoyé le :vendredi 21 juillet 2017 15:10
À : jeedom/issues
Cc : ColonelMoutarde; Author
Objet :Re: [jeedom/issues] [CORE] Utilisation de SASS pour la gestion descss (#257)

Bonjour,
Oui l'idée est bonne mais je n'ai pas les competences et le temps pour le faire ou le maintenir, je le note quand meme.

**Comment by Ethal** [comment]
Bonsoir,
Ne devrions nous pas parler de SCSS , avec des fichier en .scss, pour une migration par palier
[http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax]

**Comment by ColonelMoutarde** [comment]
Oui c'est ce que je voulais dire... :p
