### ISSUE TITLE
[CORE] Scenario erreur graphique de lien

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#259]
Bonjour,

J'ai l'erreur suivante lorsque je vais sur graphique de lien sur un scenario :
Plugin introuvable : /var/www/html/core/class/../../plugins/ipx800_relai/plugin_info/info.xml
En fait la classe est une sous class du plugin ipx800.
J'aurai aimé trouver le bug mais je n'y arrive pas.
J'ai réussi à remonter jusqu'à la fonction addGraphLink, mais je ne comprends pas son fonctionnement...

A+
Thomas

**Comment by zoic21** [comment]
Bonjour,
Ca vient du plugin il  faut le corriger.

**Comment by guenneguezt** [comment]
Bonjour,

La classe d'équipement ipx800_relai est une sous classe du plugin ipx800.
Il faut donc aller chercher dans :
/var/www/html/core/class/../../plugins/ipx800/plugin_info/info.xml

A+
Thomas

**Comment by zoic21** [comment]
Comme déja dit le soucis vient du plugin, tu peux regarder sur le plugin blea je crois qu'il fait le meme genre de chose.

**Comment by guenneguezt** [comment]
Bonjour,

Je viens de regarder le plugin blea qui utilise une sous class, mais c'est ce n'est pas une sous classe d'equipement.

A+
Thomas

**Comment by zoic21** [comment]
Oui ben il faut faire comme le plugin blea

**Comment by guenneguezt** [comment]
Bonjour,

Tu veux donc dire que le core de jeedom ne sera plus compatible avec les plugins multiclass d'EqLogic ?

A+
Thomas

**Comment by zoic21** [comment]
Oui c'est ca.

**Comment by guenneguezt** [comment]
Bonjour,

Je regarde pour la bascule. Par contre je préfère confirmer que ce que je prépare est la bonne méthode. Exemple plugin ipx800v2 et sous class ipx800v2_bouton.

1) Mise à jour dans install.php
	foreach (eqLogic::byType('ipx800v2_bouton') as $SubeqLogic) {
		$SubeqLogic->setConfiguration('type', 'bouton');
		$SubeqLogic->setEqType_name('ipx800v2');
		$SubeqLogic->save();
	}
2) Pour récupérer tous les equipements ipx800v2 de type bouton je pensais utiliser :
		byTypeAndSearhConfiguration('ipx800v2', array('type'=>'bouton'))

Est-ce correcte ?
Ensuite, il faut que je fusionne mes classe et qu'elle se basent sur la variable ci dessous avec un case :
$this->getConfiguration('type');

A+
Thomas

**Comment by guenneguezt** [comment]
Bonjour,

J'ai implémenté la méthode, mais un point ne fonctionne pas. Les commandes ne changent pas de Eqtype.
J'ai donc tenté la methode de modification des equipements et des commandes associées :
```
	foreach (eqLogic::byType('wes_bouton') as $SubeqLogic) {
		$SubeqLogic->setConfiguration('type', 'bouton');
		$SubeqLogic->setEqType_name('wes');
		$SubeqLogic->save();
		foreach (cmd::byEqLogicId($SubeqLogic->getLogicalId()) as $cmd) {
			$cmd->setEqType('wes');
			$cmd->save();
		}
	}
```
Les equipements changent de type, mais pas les commandes. J'arrive pas à savoir pourquoi. j'ai mis des traces dans la class DB.class.php.
Je vois passer :
```
[2017-08-06 22:21:39][DEBUG] : UPDATE `cmd` SET `id` = :id, `logicalId` = :logicalId, `eqType` = :eqType, `name` = :name, `order` = :order, `type` = :type, `subType` = :subType, `eqLogic_id` = :eqLogic_id, `isHistorized` = :isHistorized, `unite` = :unite, `configuration` = :configuration, `template` = :template, `display` = :display, `html` = :html, `value` = :value, `isVisible` = :isVisible, `alert` = :alert WHERE id = :id
[2017-08-06 22:21:39][DEBUG] : Array (     [id] => 3830     [logicalId] => status     [eqType] => wes     [name] => Etat     [order] => 0     [type] => info     [subType] => binary     [eqLogic_id] => 737     [isHistorized] => 0     [unite] =>      [configuration] =>      [template] =>      [display] => {"invertBinary":"0"}     [html] =>      [value] =>      [isVisible] => 1     [alert] =>  )
```
Et lorsque je regarde dans la base, mes commandes ont encore les anciens types.

A+
Thomas
PS : Je continue a publier dans cet issue pour éviter que ce soit sur le Forum et que ce sujet ne parte en vrille.

**Comment by guenneguezt** [comment]
Bonjour,

Je viens de modifier le premier plugin (wes) pour qu'il redevienne compatible.
Ca donne du taf, mais c'est faisable.

Merci & A+
Thomas
