### ISSUE TITLE
[PLUGIN][VIRTUAL] Double quotes #sjour#

### ISSUE THREAD

**Issue by DanoneKiD** [jeedom/issues#260]
Bonjour,

Il y a un problème de parsing des variables prédéfinies de Jeedom dans un virtuel.
Je construis une variable pour mes design de cette manière et j'ai une < " > à la fin de **#sjour#**

![image](https://user-images.githubusercontent.com/522809/28453430-a7cfc9ca-6df7-11e7-944b-f70f26e09fad.png)

voir : https://www.jeedom.com/forum/viewtopic.php?f=23&t=24830&p=437805&hilit=sjour#p437805
https://www.jeedom.com/forum/viewtopic.php?f=30&t=14734&p=267539&hilit=formater+date#p267539

**Comment by zoic21** [comment]
Bonjour,
Effectivement il y a un soucis mais je doute de réussir a le corrigé malheureusement la gestion des tags est très complexe dans jeedom (car on essaye de gérer les " en automatique pour que même si l'utilisateur les oublie ca marche) et je ne pourrais pas corriger sans avoir de gros effets de bords. Désolé.
