### ISSUE TITLE
[CORE] isConnect & Token d'accès invalide

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#261]
Bonjour,

J'ai une page API qui est appelé soit par l'utilisateur, soit par un tier via API.
Si l'on test comme suit ça fonctionne :
	if (!isConnect()) {
		if ( ! jeedom::apiAccess(init('api'), 'ftpd') ) {
Si l'on test comme suit ça échoue :
	if ( ! jeedom::apiAccess(init('api'), 'ftpd') ) {
		if (!isConnect()) {
Je pense que la fonction apiAccess réinitilise des choses non souhaitées.

A+
Thomas

**Comment by zoic21** [comment]
Une page accessible par api et par utilisateur c'est pas top je ne gère pas ce genre de cas surtout que la c'est spécifique a ton plugin pas a jeedom

**Comment by guenneguezt** [comment]
Pas de souci, je comprends.
Après je ne sais pas quel est la règle. C'est de l'affichage d'image.
Les URL d'image sont via la page core/api/<plugin>.api.php
Je peux mettre le code dans une autre page, mais laquel est la plus adaptée ?

A+
Thomas
