### ISSUE TITLE
[CORE] [Z-WAVE] Champ commentaire disparu

### ISSUE THREAD

**Issue by synthol67** [jeedom/issues#262]
Il y avait un champ commentaire pour chaque objet z-wave où j'écrivais d’où venait le module et la date d'achat.
Maintenant il n'y est plus.
Quelqu'un sait ou il se trouve. J'ai vu qu'il y en a un qui est apparu dans les configurations avancées.
Par contre, mes anciens commentaires ne s'y trouve pas.
Quelqu'un aurait une solution ?
J'ai la version jeedom 3.0.11

**Comment by zoic21** [comment]
Bonjour,
Ils sont toujours dans la base mais il n'y a pas recuperation automatique car ils sont pas toujours au meme endroit en fonction du plugin. La seule solution faire une requete sql et les recuperer a la main

**Comment by nechry** [comment]
Tu cliques Configuration avancé via l'équipement, puis bouton informations, le commentaire est dans le champ json Configuration , tu le copis et colle dans l'onglet Commentaires

**Comment by synthol67** [comment]
Merci de votre aide. C'est trouvé
