### ISSUE TITLE
[core] Composer

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#263]
Serait-il possible  enlever le dossier vendor du projet, il l’alourdi pour rien. 
Il est possible de s’assurer du numéro de version des libs requises en mettant un numéro exacte.
Et on peux appeler composer en CLI pour faire l'installation des dépendances après l'install ou la mise à jour.

**Comment by zoic21** [comment]
Non c'est pas possible lors d'une installation offline de jeedom si il n'y a pas le dossier vendor impossible de l'installer, en plus je patch les libs de composer desfois si je fais l'installation a chaque fois je n'ai plus mon patch...

**Comment by ColonelMoutarde** [comment]
Il ne faut pas patcher les libs de composer, il faut redéfinir la méthode dans ton code.

**Comment by zoic21** [comment]
C'est plus compliqué et moins pratique

**Comment by ColonelMoutarde** [comment]
Oui mais c’est comme ça qu’on doit faire normalement pour que tes corrections soit persistantes et pour que la communauté puisse t’aider . 
Et ce n’est pas compliqué de faire un class toto extends tutu {…

Cordialement,
Luc SANCHEZ

De : Loïc
Envoyé le :mercredi 26 juillet 2017 10:17
À : jeedom/issues
Cc : ColonelMoutarde; Author
Objet :Re: [jeedom/issues] [core] Composer (#263)

C'est plus compliqué et moins pratique

**Comment by zoic21** [comment]
Oui enfin ca marche bien comme c'est mtn et ca résoud pas le soucis des installation offline.

**Comment by fensoft** [comment]
Effectivement, je m’incruste dans cette discution car je trouve choquant d'avoir le dossier vendor de commité. Plusieurs choses:

- j'ai envie d'avoir exactement le même environement à l'octet près
=> c'est le but du composer.lock qui, d'un simple composer install, remet tout à l'identique
pour info: "This file locks the dependencies of your project to a known state"
dans ton cas ce fichier peut donc être commité

- pb d'installation offline
=> tu dois publier un zip de release qui inclus vendor. c'est automatisable en 3 lignes via un .sh par exemple ou via jenkins

- j'ai modifié les libs dans vendor
=> sacrilège !!! tu dois fork ces libs et soit pull request soit les inclure en tant que VCS dans le composer.json. exemple: 
https://github.com/fensoft/plugin-datatransfert/blob/master/composer.json#L17
