### ISSUE TITLE
[CORE] [BETA] Ecran scénario

### ISSUE THREAD

**Issue by Claude69** [jeedom/issues#264]
![capture](https://user-images.githubusercontent.com/25276987/28612620-21686d0e-71f0-11e7-842f-8dbac80b3f2e.PNG)
Hello
Version 3.1.1
Juste un problème visuel
Ecrire : 1 groupe(s) comme pour scénario(s)

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour c'est corrigé
