### ISSUE TITLE
[CORE] la fonction min sur une durée ne retourne pas la valeur attendue (contrairement à max)

### ISSUE THREAD

**Issue by bricher** [jeedom/issues#265]
Bonjour

version de jeedom 3.0.11
- la liste des plugins ainsi que leur date de mise à jour
voir copie d'écran, ils sont tous à jour
![capture d ecran de 2017-07-28 08-44-15](https://user-images.githubusercontent.com/30506564/28705639-0a348014-7371-11e7-81a4-bbe40d8bea2d.png)

- le log nginx.error ou http.error
pas d'entrée ds les logs en date de l'erreur
- une capture d'écran

dans un virtuel, la fonction
max(#[exterieur][ température][temp ext]#,#jour#) retourne bien le maximum sur la journée
alors que min(#[exterieur][ température][temp ext]#,#jour#) retourne 27 qui est le quantième du jour (hier et 28 aujourd'hui)... et pas le résultat souhaité
Par ailleurs, avez vous une fonction moyenne sur le même modèle ?

cj-joint copie résultat avec max et du résultat avec min

Merci de votre réponse

Cdlt
Bruno Richer
![capture d ecran de 2017-07-28 08-39-09](https://user-images.githubusercontent.com/30506564/28705585-c1f5777c-7370-11e7-94f7-477746846920.png)
![capture d ecran de 2017-07-28 08-30-12](https://user-images.githubusercontent.com/30506564/28705591-c878ef16-7370-11e7-898b-d8f0f73541b6.png)

**Comment by zoic21** [comment]
Bonjour,
Pas de soucis chez moi et le code des 2 fonctions est le même... Etes vous sur de bien avoir rafraîchis la valeur ? En 2eme paramètre vous mettez #jour# c'est pas possible ça c'est une période qu'il faut indiquer (tout est dans la doc)...
Pour la moyenne c'est dans la doc aussi (doc scénario)
