### ISSUE TITLE
[Dash Button]Arrêt brutal du plugin avec impossibilité de le faire refonctionner

### ISSUE THREAD

**Issue by jlmaillard** [jeedom/issues#266]
Comme expliqué dans mon post https://www.jeedom.com/forum/viewtopic.php?f=141&t=18720&hilit=Dash+Button&start=900#p493573, le plugin a brutalement cessé de fonctionner après plus d'un mois de fonctionnement.
Ce post n'ayant pas attiré l'attention, je reposte ici après avoir continué mes essais et recherches, mais toujours sans succès.

**État du plugin:**
![plugindash](https://user-images.githubusercontent.com/29634297/28727649-e632a362-73c5-11e7-9b4a-81f29db588bf.PNG)

**Définition d'un bouton:**
![dedlor](https://user-images.githubusercontent.com/29634297/28727758-4aec2cba-73c6-11e7-95a5-5741dfd7a0c9.PNG)

**Scénario de test:**
![dash_scenartest](https://user-images.githubusercontent.com/29634297/28727774-5c7b73a0-73c6-11e7-9427-6ae72c920876.PNG)

Lorsque j'appuie sur un bouton, rien ne se passe au niveau de jeedom: **pas de log pour le scénario, pas de log dans le plugin**.
Par contre l'activité est bien vue par le routeur.
De plus, dans le scénario, il est impossible d'enregistrer un délai entre deux messages (mais ça, c'est depuis le début).

Ce que j'ai fait:
- relanceS des dépendances, sans succès
- redémarrageS du démon, sans succès
- désinstallationS du plugin et réinstallationS, sans succès
- apt-get update et upgrade, sans succès

Je ne vois plus quoi faire pour m'en sortir, et j'attends donc une aide.

Mon système:  jeedom 3.0.11

**Mes plugins:**
![mesplugins](https://user-images.githubusercontent.com/29634297/28729039-4b027c68-73cb-11e7-8909-3d1505f764d8.PNG)

**Comment by magicgg91** [comment]
Bonjour pour commencer :)

Pour info, tu n'auras pas de réponse ici ...
Il s'agit du github de Jeedom, hors le plugin est développé par une personne tierce.

Je vais aller voir ton post sur le forum.

Merci de clore ton issue.
