### ISSUE TITLE
[CAMERA] Affichage des captures impossible

### ISSUE THREAD

**Issue by TaGGoU91** [jeedom/issues#267]
Bonjour,

Je viens vers vous concernant un soucis d'affichage des captures faites par les caméras via le plugin caméra.

J'ai tout détaillé dans le sujet suivant : https://www.jeedom.com/forum/viewtopic.php?f=91&t=27779
Et plus précisément sur le topic suivant : https://www.jeedom.com/forum/viewtopic.php?f=91&t=27779#p490356

Je suis dans la dernière version stable : 
![image](https://user-images.githubusercontent.com/30494278/28736828-0337dbe6-73ec-11e7-9765-ed2b79b650e0.png)

La version du plugin camera est la suivante : 
![image](https://user-images.githubusercontent.com/30494278/28736848-2846ad68-73ec-11e7-8103-1d0261c97674.png)

![image](https://user-images.githubusercontent.com/30494278/28737162-804c4ba2-73ed-11e7-9699-d31ba539e6c9.png)

J'ai tenté à l'instant de réinstaller les dépendances et le plugin, sans résultat.

Le log http.error est complètement vide.

Je n'ai rien dans le F12 du navigateur.
J'ai testé avec Chrome et Firefox sans succès, mais vu que ça semble être un soucis de droit, je ne pense pas que le navigateur est un impact.

Merci d'avance pour votre aide,
TaG

IMPORTANT : consigne pour que votre soumission ne soit pas refusée. Si vous ne respectez pas tous les points votre demande sera fermée immédiatement.

TITRE : merci de le nommer comme cela [COMPOSANT] Titre. Exemple [RFXCOM] Mon titre, ou pour jeedom lui-même [CORE] Mon titre. ATTENTION si vous êtes bêta testeur merci de rajouter [BETA] dans le titre : [RFXCOM][BETA] Mon titre

MESSAGE : merci de bien mettre toutes les informations suivantes :
- la version de jeedom (si c'est une bêta la date de dernière mise à jour)
- la liste des plugins ainsi que leur date de mise à jour
- le log nginx.error ou http.error
- une capture d'écran
- si c'est un souci sur l'interface faire F12 puis console et fournir le résultat

**Comment by zoic21** [comment]
Bonjour,
Le soucis vient de votre configuration sinon nous aurions beaucoup plus d'utilisateur dans ce cas la... Je ferme donc.
