### ISSUE TITLE
[DOC] Lien vers point particulier de la doc

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#268]
Bonjour,

Dans les 2 doc suivantes, il y a des listes de point.
https://jeedom.github.io/documentation/core/fr_FR/depannage.html
https://jeedom.github.io/documentation/core/fr_FR/faq.html

Ce serait top que les questions apparaissent dans l'index à droite et que l'on puisse y faire référence par lien pour par exemple le Forum.
Ne serait-il pas judicieux de passer chaque question en titre ?
Qu'en pensez-vous ? Si vous avez une autre solution, n'hésitez pas à me le dire.

A+
Thomas

**Comment by zoic21** [comment]
Bonjour,
Ca sera dans la prochaine version de la doc
