### ISSUE TITLE
[ZWAVE] Ajout d'une route get pour avoir la valeur d'un paramètre 

### ISSUE THREAD

**Issue by zoic21** [jeedom/issues#27]
Il est possible de configurer des paramètres Z-Wave via un bouton sur widget et/ou un scénario en ajoutant une commande de type 0x70c data[0].Set(#param#,#valeur1#,#taille#).
- Existe t'il un équivalent pour interroger la valeur d'un paramètre ? (utile avec le Qubino SmartMeter par exemple).

**Comment by nechry** [comment]
Deja possible on va lire le contenue comme n'importequel etat

**Comment by zoic21** [comment]
Tu as la syntaxe exacte j'ai un ticket ou ils disent que ca semble pas marcher ?

**Comment by zoic21** [comment]
Voila comment faire ?

<img width="1387" alt="screen shot 2016-07-21 at 14 54 51" src="https://cloud.githubusercontent.com/assets/1536036/17024278/a4e1a004-4f57-11e6-8be4-039b1ec6a0c0.png">

**Comment by domotiquestore** [comment]
En fait, l'idée était d'afficher la valeur du paramètre sur le Widget ou la récupérer dans un scénario.
Cela est par exemple intéressent avec le Qubino Smart Meter qui propose un compteur intermédiaire avec fonction de remise à zéro mais dont la mise à zéro mais aussi la lecture se passe par paramètres.

Si je teste la méthode proposée (avec une commande de type action, donc), le paramètre est bien lu (vu dans les logs) mais rien ne peut être affiché sur le widget ni récupéré dans un scénario.

Après avoir fouillé openzwaved.py et jeeZwave.php je comprend mieux le fonctionnement de l'ensemble.
En fait, pour récupérer la valeur en mode info, il faut utiliser data[#numéro de paramètre#].val
Si on veux rafraichir la valeur avant on fait une action data[#numéro de paramètre#].ForceRefresh , comme indiqué par nechry.
Je vais vérifier si le Qubino SmartMeter pousse lui même la valeur du paramètre lorsque son compteur s'incrémente ou s'il faut l'interroger (plus probable).

Jérôme, domotique-store

**Comment by nechry** [comment]
@domotiquestore l'example ici avec l'index 45 est pour le garage door controller de Aeon-Labs. la mesure de la température est accessible via un le param index 45. Or le module ne rafraîchit jamais de lui même la valeur, le force refresh permet d'avoir une remonté et comme le module est sur secteur la valeur sera rapidement disponible.   

a voir sur le Qubino SmartMeter comme la valeur du paramètre se met a jour
