### ISSUE TITLE
[Z-WAVE] Bouton "Reprendre de.." / "Appliquer sur..." ne fonctionnent pas

### ISSUE THREAD

**Issue by colas31** [jeedom/issues#270]
Bonjour,

Sur Jeedom v3.0.9 et le plugin openzwave à jour.
Sur l'onglet des paramètres d'un noeud, les boutons "Reprendre de.." / "Appliquer sur..." ne fonctionnent pas.
Un clic sur ces derniers n'ouvre aucune popin comme expliqué dans la doc. 
J'ai cette erreur dans la console : 
`Uncaught Error: prompt with checkbox requires options => getResource.php?file=3rdparty/bootbox/bootbox.min.js&md5=8055e87f2396a627e93c85890189e625&lang=fr_FR:6 
 `

merci

**Comment by nechry** [comment]
Déjà corrigé en dans la version Beta.

**Comment by colas31** [comment]
Merci, j'attendrais la sortie de la nouvelle version pour en profiter ;)
