### ISSUE TITLE
[VIRTUAL] Référence à l'état manquante lors de la duplication

### ISSUE THREAD

**Issue by NebzHB** [jeedom/issues#271]
Bonjour,

Toute version du plugin (beta et stable)

J'ai remarqué un petit bug dans le plugin lors de la duplication d'un virtuel, la référence valeur à l'état (la select box de la première colonne) n'est pas dupliquée et repasse à Aucune. Ca a peut être déjà été signalé... (je peux comprendre côté programmation le problème d'un nouvel état vers lequel devoir refaire une liaison, surtout si plusieurs différents) mais cela peut causer pas mal de problèmes pour ceux qui ne le savent pas (si pas possible un petit message lors de la duplication serait le bienvenu)

Merci

Nebz

**Comment by zoic21** [comment]
J'ai réussi a corriger le bug ca sera bon en 3.1
