### ISSUE TITLE
[core] supression des méthodes marquées dépréciées

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#272]
Salut,
Sous quelle échéance ou version va on pouvoir supprimer les méthodes marquées dépréciées ?
trigger_error('This method is deprecated', E_USER_DEPRECATED);

**Comment by zoic21** [comment]
Bonjour,
En général je supprime directement sans passer par ce genre d'erreur donc pas d’échéance particulière, dès qu'on peut.
