### ISSUE TITLE
Projet Jeedom

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#273]
Je propose de suivre les recommandations du FIG http://www.php-fig.org en particulier les psr 1 et 2 pour les codings standards.
En effet, le projet Jeedom semble suivre son propre coding style mais le problème, c'est qu'il n'est écrit nul part ! Et je comprend car c'est vraiment long d'écrire ce genre de documentation et peux intéressant.

Donc si on part sur un codding largement accepté par la communauté PHP on gagne du temps et de clarté dans le code.
Et cerise sur le pièce monté :-) les IDE moderne (netbeans, sublim text, php storm, coda...) ont la possibilité de formater automatiquement le code, c'est juste une option à cocher dans l'éditeur.

J'attend vos propositions.

**Comment by zoic21** [comment]
Bonjour,

Pour moi c'est impossible de mettre ça en place faut tout reprendre tout revoir on va casser la compatibilité partout pour un gain quasi nulle.
Il ne faut pas oublier qu'il y a enormement de plugin tierce dans jeedom et on peut pas tout refaire comme ça car ça obligerai de revoir tous les plugins tierces.

**Comment by ColonelMoutarde** [comment]
Attention les psr 1 et 2 ne touchent pas à la logique du code seulement aux règles d'indentation et de nommage mais pour cette partie on peux le faire dans un second temps. de plus il existe un outil pour le faire de manière automatique. c'est très efficace.
[https://github.com/squizlabs/PHP_CodeSniffer](url)

**Comment by ColonelMoutarde** [comment]
Tu peux aussi le faire pour tous les nouveaux fichiers créé, comme ça les nouveaux aurons un vrais coding style standardisé

**Comment by zoic21** [comment]
Yen a quasiment plus de creer dans le core c'est meme pas 1 par ans...

**Comment by ColonelMoutarde** [comment]
Et les plugins ? Il y en a plusieurs par ans.

**Comment by zoic21** [comment]
Oui mais ils doivent tous etre identique pour simplifier la maintenance.

**Comment by ColonelMoutarde** [comment]
lit les psrs, tu verra c'est pas très compliqué. et je propose de commencer par le plugin-template.

**Comment by zoic21** [comment]
Attends avant faut qu'on en rediscute en interne, si jeedom a sont propre conding code c'est pas pour rien donc un changement plus que majeur comme ca on va bien y reflechir avant.

**Comment by ColonelMoutarde** [comment]
ok
