### ISSUE TITLE
Changement de nom de classe

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#276]
Bonjour,

Je suis en train de réécrire mes plugins multi classe pour ne plus être hors norme.
Pour la migration, je fais :
	foreach (eqLogic::byType('wes_bouton') as $SubeqLogic) {
		$SubeqLogic->setConfiguration('type', 'bouton');
		$SubeqLogic->setEqType_name('wes');
		$SubeqLogic->save();
		foreach (cmd::byEqLogicId($SubeqLogic->getLogicalId()) as $cmd) {
			$cmd->setEqType('wes');
			$cmd->save();
		}
	}
Mes équipements wes_bouton sont bien basculé en class wes, mais les commandes associées non.
Comment puis-je faire ?

Merci
Thomas

**Comment by zoic21** [comment]
Bonjour,
Sur la commande il faut changer la proprieté eqType_name

**Comment by guenneguezt** [comment]
BonjourC'est ce que je pensais faire avec les deux commandes suivantes :$cmd->setEqType('wes');$cmd->save();Quel est la bonne syntaxe ?CordialementThomas Guenneguez

**Comment by zoic21** [comment]
C'est bon cette partie la c'est au dessus qu'il y a une erreur : foreach (cmd::byEqLogicId($SubeqLogic->getLogicalId()) as $cmd) { ca c'est pas bon un logicialId n'est pas un ID...

**Comment by guenneguezt** [comment]
Bonjour,

Ce serait :
foreach (cmd::byEqLogicId($SubeqLogic->getId()) as $cmd) {

En fait le trouble vient de :
byEqLogicId veut dire by EqLogic by Id
Et non :
byEqLogicId veut dire by EqLogic by LogicId

Je suis un boulet, merci.

Merci
Thoams
