### ISSUE TITLE
[APP-MOBILE][IOS] Access externe impossible

### ISSUE THREAD

**Issue by Alexis2** [jeedom/issues#277]
Hello,

Je tourne sous la version 3.0.11 de Jeedom avec la derniere version du plugin mobile.
J'ai un probleme avec l'access depuis l'exterieur à Jeedom. Je peux y acceder à travers chrome depuis hors de chez moi mais impossible depuis l'application mobile: "Unable to connect to Jeedom" (tout marche bien en local).

Bonne journee,
Alexis

**Comment by rocket13011** [comment]
Bonjour,

vous utilisez les dns jeedom pour l'accès externe ?
pouvez-vous verifier l'adresse dans les paramètre de l'app Jeedom ?

Merci.

**Comment by unknownboy** [comment]
Salut, 

Pour information j'ai ouvert un ticket auprès du support pour le même genre de problème.
Dans la configuration jeedom, l'accès externe est NOK alors que je suis connecté au travers de cette URL.
Sans surprise, impossible de configurer l'application mobile à partir de l'accès externe (cela fonctionne en interne).
![probleme jeedom](https://user-images.githubusercontent.com/2530749/30038267-e7f4af4a-91c2-11e7-9e14-2a8647109c2f.png)

**Comment by stephaneSBO** [comment]
Bonjour, 

L'accès de l'extérieur est il fonctionnel via un navigateur web ? Êtes vous certain de l'utilité du /jeedom/ sur le lien externe ?
Cdl

**Comment by unknownboy** [comment]
Voir avec Alexandre du support. Je dispose d un reverse proxy apache sur une autre machine. Le /jeedom/ est obligatoire dans mon contexte.

**Comment by zoic21** [comment]
C'est le / a la fin qui va pas (après /jeedom), jeedom le supprime car non supporté, il faut je pense revoir la configuration du reverse proxy pour ne pas en avoir besoin.

**Comment by Alexis2** [comment]
Je vois que m'a réponse n'a pas été envoyé mais j'ai toujours le probleme. Je n'utilise pas les.dns jeedom mais un personnel et l'adresse est bien la bonne dans l'application.

Merci

**Comment by zoic21** [comment]
Sans capture d'écran log ou autre nous ne pouvons pas aider.

**Comment by unknownboy** [comment]
Bonjour Loïc, je viens de supprimer le trailing slash et j ai pareil. Toujours NOK sur la page de config.

**Comment by Alexis2** [comment]
Voici une capture de mon erreur.

**Comment by zoic21** [comment]
@unknownboy oui mais est ce que ton reverse proxy l'accepte sans / à la fin ? C'est pas sur ca
@Alexis2 pas de capture la....

**Comment by unknownboy** [comment]
Oui le reverse proxy accepte sans.

**Comment by zoic21** [comment]
Alors il y a un autre soucis dans ta configuration mais la je doute que le soucis vienne de jeedom...

**Comment by unknownboy** [comment]
Je m y connecte via : https://xxxx.ddns.net/jeedom
Ou avec le slash à la fin indifféremment.

**Comment by zoic21** [comment]
Tu es en dyndns ? Avec une box autre qu'une freebox ?

**Comment by unknownboy** [comment]
Dyndns -> freebox -> apache sur serveur perso interne -> raspberry jeedom

**Comment by Alexis2** [comment]
Oui l'upload n'a pas marcher, je la rajouterais ce soir depuis mon pc
Elle ne donne cependant pas beaucoup plus d'info que mon message original

**Comment by zoic21** [comment]
@Alexis2 oui mais sans ca je peux rien faire du tout
@unknownboy : ben je sais pas alors désolé pour moi c'est un soucis de configuration du reverse jeedom va juste tester une url et la il n'y arrive pas

**Comment by unknownboy** [comment]
Loïc je vais faire du debug dans jeedom et mon reverse. Je te tiens au courant.

**Comment by Alexis2** [comment]
Je t'envoie ça ce soir.
l'URL que j'utilise pour l'accès externe est http://xxxxx.hopto.org:1235 qui fonctionne bien depuis le navigateur

**Comment by unknownboy** [comment]
@zoic21 le bout de code qui fait la vérif : 
```php
public static function test($_mode = 'external', $_timeout = 10) {
		if (config::byKey('network::disableMangement') == 1) {
			return true;
		}
		if ($_mode == 'internal' && netMatch('127.0.*.*', self::getNetworkAccess($_mode, 'ip', '', false))) {
			return false;
		}
		$url = trim(self::getNetworkAccess($_mode, '', '', false), '/') . '/here.html';
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_TIMEOUT, $_timeout);
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
		curl_setopt($ch, CURLOPT_HEADER, false);
		if ($_mode == 'external') {
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
			curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
		}
		$data = curl_exec($ch);
		if (curl_errno($ch)) {
			log::add('network', 'debug', 'Erreur sur ' . $url . ' => ' . curl_errno($ch));
			curl_close($ch);
			return false;
		}
		curl_close($ch);
		if (trim($data) != 'ok') {
			log::add('network', 'debug', 'Retour NOK sur ' . $url . ' => ' . $data);
			return false;
		}
		return true;
	}
```
Voici le message de debug associé : 
[2017-09-09 00:08:37][DEBUG] : Retour NOK sur https://XXXXX.ddns.net:443/jeedom/here.html => <html><body><p>ok</p></body></html>

Tout semble pourtant OK. Mon reverse proxy voit bien passé la requête et renvoi bien la page "here.html".
