### ISSUE TITLE
Projet Jeedom

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#278]
Est il possible de déclarer php 5.6 comme déprécié pour aller vers PHP 7 voire 7.1 en version minium.

**Comment by zoic21** [comment]
Bonjour,
Ben non surtout pas on a encore 95% des utilisateurs dessus et les Smart sont en PHP 5.6

**Comment by ColonelMoutarde** [comment]
bah justement faut préparer l'avenir... ...C'est juste pour mettre un message qui indique que dans X versions ce sera php 7 au minimum. Libre à toi de définir dans quelle futur version tu compte arrêter php 5. Mais si tu ne donne pas de dead line, personne ne migrera jamais.

**Comment by zoic21** [comment]
Ca se fera on la bien en tete pas de soucis la dessus mais pour l'instant c'est beaucoup trop tot on le fera en temps voulu
