### ISSUE TITLE
[RFXCOM] Ajout dimming TRUST ALED 2709

### ISSUE THREAD

**Issue by zoic21** [jeedom/issues#279]
Ajouter le support du dimming sur TRUST ALED 2709

**Comment by nekopep** [comment]
Bonjour, j'ai 2 lampes de ce type et elles ne fonctionnaient pas avec les réglages de bases.
Etes vous intéréssé par les trames radio envoyées pat la télocommande associée?

**Comment by nekopep** [comment]
A noter que l'envoi de 2 trames ON consécutives active un mode qui fait dimmer les ampoules de facon cyclique jusqu'a l'appui d'un ON pour stopper le cyclage.

**Comment by nekopep** [comment]
Pour le dimming il faut limiter les valuers de 0 à 15 (0x0 - 0xF) et cela fonctionne.

**Comment by nekopep** [comment]
Ci joint le décodage des trames:

0B1100XX ID 01000070 -> canal 1 OFF
0B1100XX ID 09000070 -> canal 2 OFF
0B1100XX ID 05000070 -> canal 3 OFF
0B1100XX ID 0D000070 -> canal 4 OFF
                      0D010F70 -> canal 4 ON
                      0D020F70 -> canal D Dim 0xF 

0B1100XX #ID# CCZZZV70

XX -> Trame number (incremented by one for each sequence)
CC -> Canal:
    01 : 1
    09 : 2
    05 : 3
    0D : 4
ZZZ -> Command:
    000 : ON
    010 : 0FF
    020 : Dim
V -> dimming value (0-F)
