### ISSUE TITLE
[ZWAVE] Commande pour agir sur les fonction système

### ISSUE THREAD

**Issue by zoic21** [jeedom/issues#28]
Existe t'il d'autres commandes pour lire / agir sur les fonctions présentes dans système (0x27, 0x32, etc.) ?

**Comment by nechry** [comment]
Tout les commandes disponible sur les valeurs sont aussi disponible pour celle présente dans onglet Système
data[index].val pour lire la valeur (modifier l'index)
data[index].PressButton()
data[index].ReleaseButton()
data[index].ForceRefresh()
data[index].Set(value) Pour assigner la valeur value à l'index

il faut a chaque fois spécifier la CC et la bonne Instance
