### ISSUE TITLE
[CORE] Watchdog services

### ISSUE THREAD

**Issue by tmartinez69009** [jeedom/issues#280]
Bonjour,
Il serait intéressant de pouvoir rajouter à Jeedom un watchdog qui surveille les principaux composants : MySQL et Apache et qui relance les services en cas de plantage de ceux-ci.

En attendant, pour palier le soucis sur certaines boxs où le service mysql avait tendance a crashé, j'ai rajouté cette ligne dans le crontab : 
 * * * * * /sbin/service mysql status || /sbin/service mysql start

**Comment by zoic21** [comment]
C'est ajouté en 3.1
