### ISSUE TITLE
[core] Utilisation du moteur de template Twig

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#281]
Salut,
Je vois 3 principales valeurs ajouté à utiliser le moteur de template  Twig.

- Le moteur fait un échappement des valeurs affichées de base
- on gagne un cache très facilement donc on affiche les pages très rapidement.
- twig est très simple utiliser même par des non développeurs

mais il y aussi d'autres fonctionnalité sympas comme:

ps: je pompe cette explication de openclassroom

- Le code est plus clair : on sait où est le code HTML et on ne doit pas chercher après dans le code PHP. Pour reprendre la phrase du dessus on peut noter le fait que vous savez quel fichier éditer quand vous savez d'où vient l'erreur. 

- Avec un graphiste, c'est un réel plus. Les graphistes connaissent généralement HTML et CSS et pas toujours PHP. Le graphiste s'y retrouve donc beaucoup plus facilement.

Évidement on peux imaginer cela dans jeedom 4... pas tout de suite

**Comment by zoic21** [comment]
Salut,
Tu vas pas aimer mais je vois pas pourquoi ? En général un changement est motivé pour améliorer quelque chose la ça sera pas le cas on va même perdre en performance.

Je vois bien que tu veux faire rentrer le code de Jeedom dans un standard avec des outils standard mais je comprends pas pourquoi ? Ça marche bien comme ça non ? C'est performant ? C'est facilement maintenable non ? Alors pourquoi vouloir tout refaire avec des outils qui vont rajouter des couches de code, de complexité et de bug potentiels ?

**Comment by ColonelMoutarde** [comment]
il y a pleins de morceau de html dans le code en dehors des vues. C'est une façon de rationaliser.
Pour la rapidité on gagne un cache pour les vues donc de nombreux calculs ne sont effectué qu'une seule fois.
La class cmd en a plein il serait plus facile de les grouper dans des vues.

**Comment by zoic21** [comment]
Si tu regarde bien la classe cmd elle utilise déja du cache et un moteur de template il n'y en a donc pas besoin d'un nouveau. Pour le code html effectivement les class en on des fois mais rien de bien genant.

**Comment by ColonelMoutarde** [comment]
Comme tu veux...
