### ISSUE TITLE
Plugin eco rt2 : topic sur le Forum

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#282]
Bonjour,

Pouvez-vous ouvrir un topic sur le forum pour le plugin rt2 et mettre le lien sur le market car les utilisateurs postent dans le topic du plugin ecodevice et je ne sais pas quoi leur répondre ...
https://www.jeedom.com/forum/viewtopic.php?p=511351&sid=e6b7af737b76893c2e6472453f164206#p511351
Perso, je pense qu'il devrait être interdit de publier un plugin en stable tant que tous les champs ne sont pas renseignés... En tout cas le lien forum pour que les utilisateurs puissent échanger.

Merci
Thomas

**Comment by zoic21** [comment]
Bonjour,
Non il n'y aura pas de post pour le RT2 dédié si soucis il y a l'utilisateur poste dans le forum générique de la catégorie du plugin.
Pour ce qui est de la sortie stable je l'ai fait car il y avait une certaine demande en disant bien que il n'y a pas de doc n'y rien on m'a dit pas de soucis j'ai voulu aider mais ok je ne sortirai plus de plugin pour aider les gens.

**Comment by guenneguezt** [comment]
Bonjour,

Désolé, c'est juste que l'on poste dans le forum dédié à un autre plugin et que je me sens responsable de ce post en tant que développeur de ce plugin.
Mais du coup ce post est pollué par des demandes qui ne concernent pas ce plugin.

A+
Thomas

**Comment by magicgg91** [comment]
Pour info, j'ai crée 1 sujet pour que les utilisateurs postent au bon endroit.
https://www.jeedom.com/forum/viewtopic.php?f=149&t=29423

**Comment by guenneguezt** [comment]
Cool merci
