### ISSUE TITLE
Problème de publication de plugin sur le market

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#283]
Bonjour,

Lorsque je souhaite publier le plugin ftpd, j'ai l'erreur suivante :
Code : 0
Message : Impossible d'uploader le fichier

Il s'agit du plugin ftpd (2,9Mo).
J'ai plusieurs captures d'ecran dans la doc. Est-ce lié ?
Le dépot est sur : https://github.com/guenneguezt/plugin-ftpd

J'ai 2 jeedom :
un pour la prod
un pour le dev
J'ai tenté depuis les deux pour ce plugin et j'ai la même erreur. J'ai tenté un autre plugin et il passe.

Merci de votre aide
Thomas
PS : J'ai tenté une demande sur le forum, mais aucune réponse ;-)

**Comment by zoic21** [comment]
Bonjour,
Le soucis est du au market on travail sur la correction mais pour l'instant pas de délai.

PS : Le forum n'est pas la societé jeedom nous n'avons aucune obligation de réponse d'ou le faite qu'on ne réponde que très rarement et que sur ce qu'on veut.

**Comment by guenneguezt** [comment]
Bonjour Loic,

En premier lieu, merci de la réponse.

Je sais que le forum est différent de la société et qu'il n'y a aucune obligation de réponse.
J'ai posté sur le forum en premier lieu pour justement que les autres développeurs s'ils rencontrent le même souci soient informé.
Par contre, c'est dommage que lorsqu'il y a un truc qui ne fonctionne pas normalement sur l'infra jeedom, que la société ne communique pas.

Par contre, peux-tu me tenir au courant lorsque ce sera réglé ?
Le mieux aurait été de laissé le ticket ouvert jusqu'à résolution du problème ?

A+
Thomas

**Comment by zoic21** [comment]
Le soucis remonte a début aout je l'ai dit plein de fois partout et je ne ferais pas plus de com que ca dessus car pas le temps. 
Pour la résolution je sais pas quand ça arrivera mais ça se verra vite le market n'aura plus de soucis tout comme le forum.
