### ISSUE TITLE
[CORE] Profondeur (z-index) non conservée

### ISSUE THREAD

**Issue by DanoneKiD** [jeedom/issues#284]
Bonjour,

La propriété z-index d'un "objet" n'est pas conservée lors de la duplication d'un design.
voir https://www.jeedom.com/forum/viewtopic.php?f=24&t=29380
Apparemment c'est la méthode [preInsert ](https://github.com/jeedom/core/blob/f6d5419cb8818404e85b59e655e2e1ad42277bf5/core/class/plan.class.php#L125) de la classe [b]plan [/b]qui force le z-index à 1000

**Comment by zoic21** [comment]
Bonjour,
J'ai fait la correction (dans jeedom 3.1)

**Comment by DanoneKiD** [comment]
Ultra-rapide comme d'hab. Merci
