### ISSUE TITLE
[CORE] Groupement par année

### ISSUE THREAD

**Issue by JuLQE** [jeedom/issues#285]
Jeedom v3.0.11

Bonjour,

Avec la version 3.x de Jeedom, il est maintenant possible de regrouper les données par heure ou année dans l'historique. Cela fonctionne.
En revanche, ces 2 ajouts ne semblent pas avoir été reportés dans les paramètres des graphiques des Vues...

<img width="956" alt="groupement vues" src="https://user-images.githubusercontent.com/21390407/30439986-9aeb595a-9975-11e7-9cc3-9656e46179f2.PNG">

**Comment by zoic21** [comment]
Ca sera bon en jeedom 3.1

**Comment by JuLQE** [comment]
Merci

**Comment by JuLQE** [comment]
Jeedom v3.1.7

Bonjour,

Je viens de faire la mise à jour en 3.1.7, j'ai redémarré Jeedom, supprimé le cache de Chrome mais toujours pas de groupement "Sommes par année" dans les Vues...

Merci.
