### ISSUE TITLE
[CORE] install.sh devrait vérifier si jeedom n'est pas déjà installé ou se supprimer soi-même (via cron) après install

### ISSUE THREAD

**Issue by NebzHB** [jeedom/issues#287]
Pas grand chose mais en voulant installer un autre soft qui avait un install.sh aussi, j'ai relancé celui de jeedom et j'ai tout cassé... serait-il possible d'ajouter un petit check au début pour vérifier s'il n'est pas déjà là ? ou bien qu'il se supprime via cron à la fin de son exécution ?

**Comment by zoic21** [comment]
Bonjour,
Non pas possible juste en cas de soucis le install.sh doit tout écraser c'est volontaire.

**Comment by NebzHB** [comment]
alors il bug sur mysql si on le relance car il n'arrive pas à s'y connecter... désolé j'ai effacé la SD depuis mais je peux re-faire un test si nécessaire
