### ISSUE TITLE
[WIFip] Pas d'accès aux dépendances

### ISSUE THREAD

**Issue by Babatou** [jeedom/issues#289]
Impossible d'accéder aux dépendances du dit plugin.

**Comment by magicgg91** [comment]
Bonjour,
Oui mais sur quelle matériel ?

**Comment by Babatou** [comment]
Sur une box pro. V 3.0.11

en fait j'ai du passer a Mano cette ligne pour que la détection des réseaux soit prise en compte 

sh /var/www/html/plugins/wifip/3rdparty/install.sh
