### ISSUE TITLE
[CORE] Erreur 500 lors de l'installation de n'importe quel plugin

### ISSUE THREAD

**Issue by LemarinelNet** [jeedom/issues#290]
Bonjour,

Je viens d'installer jeedom manuellement sur ma Orange Pi qui tourne en DietPi (dérivée de debian).
J'ai téléchargé le depot "core" de github, et l'install s'est faite a peu pres sans souci (j'ai tenté l'install.sh avant... mais il m'a cassé mon serveur mysql, j'ai donc fini l'install à la main).

Une fois l'installation terminée, j'ai eu accès à l'interface jeedom sans souci. Tout a l'air de fonctionner, sauf que je ne peux pas installer de plugin. Je me rend dans le market, je sélectionne par exemple le plugin "Virtuel", et quand je clique sur "installer stable", j'ai un bandeau rouge "500 : Internal Server Error". Dans la console de developpement de chrome, il m'indique que repo.ajax.php semble etre la source de cette erreur (apres un peu plus de 2s d'execution). Il n'y a rien dans la sortie de cette requete.

La log d'erreur apache est vide, pour bien faire...

Si vous pouviez m'aider à debrouiller ce truc ?

**Comment by zoic21** [comment]
Bonjour,
Nous ne supportons pas l'orange pi donc ca va etre compliqué... Surtout si en plus il n'y a rien dans les logs je pense que vu que l'installation c'est mal passé il faut recommencer de 0.

**Comment by LemarinelNet** [comment]
L'orange pi fonctionne exactement comme une raspberry....
Au passage il y a quand même pas mal de trucs olé olé dans les scripts
d'install : définir des options de conf d'Apache , de PHP, de MySQL sans
prévenir l'utilisateur....
J'avais deplacé des fichiers de données de MySQL dans un autre dossier , le
service ne démarrait plus suite a l'installation,  ma home de www était
déplacée aussi , donc le script n'en tenait pas compte non plus...

**Comment by zoic21** [comment]
On part du principe que si vous utilisez le script jeedom est tout seul sur le systeme (de toute facon les utilisateurs trouvent que c'est déja trop compliqué avec le script donc je vais pas rajouter des trucs dedans).
Vu la description de l'installation le soucis est la vu qu'il y a eu de la bidouille on est plus sur le standard donc je peux difficilement aider.

**Comment by LemarinelNet** [comment]
En gros vous supportez uniquement jeedom sur une debian "nue de série" et
surtout sans rien autour... Autant dire que jeedom ne s'installe que via
l'image de la sd, ça sera moins compliqué pour tous ;)

**Comment by magicgg91** [comment]
Bah non, mais quand on veut faire cohabiter plusieurs logiciels, en Linux, DIY, si on doit mettre un peu les mains dans le cambouis, et bah on les met !

Et puis je me vois mal installer 1 SD sur mon NUC... ou dans 1 Smart

**Comment by LemarinelNet** [comment]
Je pensais que Jeedom, opensource, serait un peu plus près de la philosophie Linux que ça : Une brique qu'on peut faire cohabiter avec d'autres...
Justement j(ai mis les mains dans le cambouis : j'ai changé le dossier des fichiers des bases de mysql afin de les mettre sur un disque USB, j'ai déjà un serveur web avec des choses qui tournent dedans, j'ai deja des scripts php...
Du coup j'ai surtout constaté que jeedom avait écrasé ma conf mysql, et que du coup mysql ne trouvait plus ses fichiers...
Peu importe, ce qui me pose problème c'est semble-t-il un script qui plante pour une raison que j'ignore, et je vais effectivement devoir mettre les mains dans le code, car il semble qu'il manque un truc !
