### ISSUE TITLE
[CORE][BETA] Scénarios ne se supprimant pas

### ISSUE THREAD

**Issue by NebzHB** [jeedom/issues#291]
Bonjour,

lorsque on veut supprimer un scénario marqué comme actif, celui-ci ne se supprime pas et se lance.
il faut le désactiver avant de cliquer sur supprimer pour qu'il se supprime correctement

**Comment by zoic21** [comment]
Bonjour,
C'est normal si il est en cours il faut d'abord l'arreter puis le supprimer.

**Comment by NebzHB** [comment]
Non pas en cours, actif (enabled pas running)

et si on le supprime alors qu'il est actif, il démarre

**Comment by zoic21** [comment]
Alors c'est un truc chez toi car je reproduis pas

**Comment by NebzHB** [comment]
peut-etre des vieux scénarios migrés de v2...
