### ISSUE TITLE
fail2ban : desactivation

### ISSUE THREAD

**Issue by Dany21000** [jeedom/issues#292]
Salut, 

Puisque fail2ban n'est plus utilisé, il serai judicieux de le désactiver, voir meme de le supprimer.
Est ce qu'un simple systemctl disable fail2ban && systemctl stop fail2ban peut etre intégré dans un prochain upgrade ?

Il consomme des cycles CPU, pas tout le temps heureusement, mais régulièrement.

**Comment by zoic21** [comment]
Bonjour,
Non le fail2ban est utilisé je ne vois donc pas pk ont le supprimerais
