### ISSUE TITLE
[core/update] 3.1.3 qui reste en "update" alors que la mise à jour est ok

### ISSUE THREAD

**Issue by spyjo** [jeedom/issues#293]
Bonjour Loic,

Comme d'autres sur le forum, j'ai aussi le bug du 3.1.3 qui reste en "update" alors que la mise à jour est ok.
Du coup je viens un peu d'analyser le code:

Dans le fichier update.class.php , fonction checkUpdate() , le test suivant ne passe pas (de mon coté la fonction renvoie 1):
if (config::byKey('update::allowCore', 'core', 1) != 0)

C'est à cet endroit que le check update s'arrête avec le return, et du coup il ne mets pas à jour le status du core de "update" à "ok". En supprimant cette ligne, ça remarche de nouveau, le core est bien marqué comme à jour.

Voila si ça peut t'aider, ou sinon dis moi s'il faut regarder d'autres choses.

**Comment by zoic21** [comment]
Effectivement merci pour le retour j'ai corrigé et vais pousser l'update
