### ISSUE TITLE
[KODI] Problème d'installation des dépendances

### ISSUE THREAD

**Issue by DamienBraillard** [jeedom/issues#294]
Version Jeedom: 3.1.4
Version plugin Kodi: 2017-10-01 01:01:55
Système: Raspberry PI 3 avec Raspbian 9 stretch

Après la mise à jour, le message suivante apparaît dans le log:

> Aucun script ne correspond à votre type de linux : /var/www/html/plugins/kodi/core/class/../../resources/install_#stype#.sh /tmp/jeedom/kodi/dependance avec #stype# : apt

Après analyse, il s'agit d'un problème de nom entre le chemin du script à exécuter et le nom du dossier sur le disque.

Dans le chemin, le dossier est nommé "resources" avec un seul "s" alors que le dossier sur le disque est nommé "ressources" avec deux "s".

**En résumé:**
Dans le fichier "kodi.class.php", ligne 82:
`return array('script' => dirname(__FILE__) . '/../../resources/install_#stype#.sh ' . jeedom::getTmpFolder('kodi') . '/dependance', 'log' => log::getPathToLog(__CLASS__ . '_update'));`

Sur le disque:
`/var/www/html/plugins/kodi/ressources`

Il faut corriger un des deux ! Probablement le nom du dossier car toute l'arborescence utilise l'anglais.

Problème résolu chez moi après renommage du dossier en "resources".

Meilleures salutations et bon fix !

Damien Braillard

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour je viens de faire la correction et repousser le plugin (il devrait être sur le market d'ici quelques minutes).
