### ISSUE TITLE
[JEELINK] Ne pas perdre certains champs de l'eqLogic originel

### ISSUE THREAD

**Issue by NebzHB** [jeedom/issues#296]
Bonjour,

Je remarque que l'on perd certaines infos lors d'un lien jeelink, il est par exemple impossible de déterminer de quel plugin originel venait l'eqLogic créé (eqType_name), son logicalID disparrait aussi (ceux des cmd aussi), est-il possible de les placer qqpart ? (dans configuration.originalDatas par exemple ou que sais-je)

merci d'avance,
Nebz

**Comment by zoic21** [comment]
Bonjour,
Je ne sais pas comme ca c'est compliqué jeelink fait une grosse abstraction c'est normal c'est son but. Je garde l'idée mais pour l'instant non eqType_name sera forcement jeeLink ca je peux rien y faire.

**Comment by NebzHB** [comment]
oui logique, j'ai vu que tu l'utilises dans le code. L'idée était de ne pas perdre certaines infos qui peuvent s'avérer utiles. Merci

**Comment by zoic21** [comment]
Utiles pour ? Jeedom s'en sort très bien s'en c'est info

**Comment by NebzHB** [comment]
Pour que les plugins puissent déterminer le type de l'eqLogic

**Comment by zoic21** [comment]
Quels plugins ? Aucun plugin que j'ai développé n'en a besoin... Ils font tous de l'abstraction justement pour etre compatible avec tout d'un coup

**Comment by NebzHB** [comment]
Mon plugin en cours pourrait en avoir besoin, mais c'est un nice to have, pas un besoin.

**Comment by zoic21** [comment]
C'est quoi ton plugin ? Car vraiment je comprends pas comment c'est possible, normalement pas besoin dans jeedom si tu en as besoin je pense ya un soucis de conception...

**Comment by NebzHB** [comment]
Homebridge. J'utilise le eqType_name pour pouvoir afficher une interface pour par exemple mapper les modes d'alarme (du plugin alarme) aux modes de HomeKit pour faire une correspondance. ou le plugin thermostat et thermostatNetatmo pour mapper aussi les modes. J'utilise le logicalID de certaines commandes pour préconfigurer des types spécifique dans mon plugin pour des Type_Génériques qui n'existent pas (genre associer des informations sur le volume et le mute du plugin sonos à des types spécifiques dans mon plugin)

**Comment by zoic21** [comment]
Oui déjà avec les type générique tu devrais t'en sortir (même si je suis contre cette propriété) sinon avec le widget normalement tu fais que du rendu pour le rendu c'est le widget qui fait fois et en plus tu es compatible avec tout d'un seul coup

**Comment by NebzHB** [comment]
oui mais certains types génériques n'existent pas ou pas encore, c'était pour supporter certains types avant que Alex les développe de son coté.
bonne idée pour le widget, je creuse ça ! merci !
