### ISSUE TITLE
[CORE/Interface] Interface lente (dans certains endroits)

### ISSUE THREAD

**Issue by Grzywax** [jeedom/issues#297]
- Problem since Jeedom 3.1.5 still in Jeedom 3.1.6
- Platform: Linux jeedom 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
- Hardware VM on ESXi 6.0u3, 8 x vCPU (Intel 4Ghz each core), 8GB RAM, Higest Class SSD datastore.

Certaines parties de Jéedom prennent beaucoup de temps à ouvrir depuis la version 3.1.5. D'autres pages s'ouvrent très vite.
Par exemple, depuis la version 3.1.5, le tableau de bord et les pages mobiles chargent TRES RAPIDEMENT.
Pour entrer dans les paramètres de l'appareil (par exemple http://192.168.1.31/index.php?v=d&p=openzwave&m=openzwave&id=104), il est TRÈS RAPIDE.
Mais quand j'essaie d'ouvrir l'un de ses paramètres de commande, cela prend une éternité. La fenêtre est créée rapidement et il y a de l'engin spinnig (police géniale ??) runnig depuis longtemps avant de charger les paramètres de la commande.
La même chose se produit lorsque vous ouvrez un scénario ou un widget à éditer.
Il faut aussi beaucoup de temps pour enregistrer des changements dans différents endroits.

Cela a commencé immédiatement après la mise à jour vers 3.1.5. Rien d'autre n'a été annoncé dans le système en ce moment.

Si vous avez besoin de plus d'informations ou si vous avez besoin de moi pour effectuer un test, dites-moi s'il vous plaît.

EN:
Some parts of Jeedom takes a very long time to open since version 3.1.5. Other pages opens very fast. 
For example since version 3.1.5 Dashboard and mobile pages load VERY FAST.
To enter device settings (for example http://192.168.1.31/index.php?v=d&p=openzwave&m=openzwave&id=104) it's VERY FAST.
But when I try to open one of it's command settings it takes forever. Window is created fast and there is spinnig gear (font awesome??) runnig for long time before it loads command settings. 
Same thing happens when opening scenario or widget to edit. 
it also takes long time to save some changes in various places.

This started immediately after update to 3.1.5. Nothing else was uypdated in the system at this time.

If you need more info or you need me to perform some test - tell me please.

**Comment by Grzywax** [comment]
Update: 
Après l'installation de 3.1.7:
Aucun problème avec la page de configuration des scénarios d'ouverture - très vite maintenant
Aucun problème avec la configuration du périphérique de sauvegarde - très vite maintenant

Toujours un problème avec l'ouverture Configuration de la commande - très lent
Toujours un problème avec l'ouverture de la configuration générale de Jeedom - très lent

**Comment by zoic21** [comment]
Bonjour,
Malheureusement je doute qu'on trouve on a fait aucune optimisation nulle part entre la 3.1.5 et 3.1.7. je constate aussi de temps en temps des lenteurs mais ça dépend pas de la page ni du moment c'est de temps en temps comme ça.

**Comment by Grzywax** [comment]
Je n'aurais peut-être pas expliqué cela correctement.
Cela se produit à chaque fois - **chaque fois 100% fois** depuis 3.1.5.
Je parle ici de l'ouverture de la configuration de la commande. Voir la capture d'écran:
![image](https://user-images.githubusercontent.com/17531396/31252378-4cd8b7f0-aa21-11e7-95ac-d0962efe010b.png)

Chaque fois tous les jours - et je travaille tous les soirs avec Jeedom depuis quelques semaines.
La même chose se produit lors de l'ouverture de la configuration de Jeedom - voir le image:
![image](https://user-images.githubusercontent.com/17531396/31252584-ee52d1ce-aa21-11e7-8779-51a18fb8eed3.png)

Je peux convenir que, dans les scénarios, je pourrais me tromper, car je n'ai pas vérifié autant. Mais pour la configuration de la parametres commande et de la jeedom je suis 100% sûr qu'il y a un problème depuis 3.1.5 car ce n'est **pas intermittent**. Je peux cliquer 100 fois par jour, c'est toujours le même.

S'il vous plaît voir mon matériel, avec cette puissance il ne devrait pas y avoir de ralentissement - jamais. Et avant 3.1.5, je n'ai jamais eu ... C'est pourquoi c'est peut-être si évident pour moi. Je suppose que si quelqu'un utilise le RPI pour Jeéménie, il pourrait être habitué à avoir une interface lente.

Chaque fois que je clique sur la configuration de toute commande, j'obtiens cet écran pendant **10 secondes** - à chaque fois exactement **10s** (ce qui pourrait être un indicateur de ce qui provoque ceci - **chaque fois 10s**):
![image](https://user-images.githubusercontent.com/17531396/31253088-b98510f4-aa23-11e7-9d70-4943a4fa0112.png)

En comparaison, il faut **3 secondes** pour charger complètement mon **dashboard** qui possède plus de 4**0 périphériques et environ 200 widgets**. S'il vous plaît, réfléchissez à cela - pourquoi toujours 10s et toujours sur les mêmes pages?

**Merci d'avance**
Patrick

**Comment by Grzywax** [comment]
Il est à noter que pendant ce temps de chargement - il n'y a pas de charge dans la CPU, il n'y a pas de processus spécifique qui utilise plus de CPU à ce moment-là.
Il semble vraiment qu'il y ait un certain temps d'attente, un délai, timeout?
![image](https://user-images.githubusercontent.com/17531396/31254178-ea1e24c2-aa27-11e7-924e-fc2b703d2af1.png)
![image](https://user-images.githubusercontent.com/17531396/31254199-fb156c0e-aa27-11e7-9209-b805462f3ac4.png)

**Comment by bbreton09** [comment]
Peux tu faire un benchmark de ton jeedom. Menu Analyse -> Santé puis en haut a droit le petit compteur de vitesse.
![benchmark](https://user-images.githubusercontent.com/10090794/31265417-0433bbc8-aa6f-11e7-947d-b2e2ab65c6ef.JPG)

**Comment by Grzywax** [comment]
![image](https://user-images.githubusercontent.com/17531396/31267289-dbc41ae4-aa77-11e7-974e-eb4e01b1c54d.png)
![image](https://user-images.githubusercontent.com/17531396/31267311-ec5bb5a6-aa77-11e7-9f90-77bb0af4be64.png)
![image](https://user-images.githubusercontent.com/17531396/31267326-fb62d142-aa77-11e7-8a86-558e98fb6981.png)

Je n'ai jamais utilisé cela auparavant. Une chose drôle ... La page de santé est identique à la page de configuration de la commande - il faut 10s pour ouvrir chaque fois pour ouvrir - l'engrenage rotatif (et 10s pour actualiser - F5). Lorsque je frappe F5, il ne fera rien pendant 10 secondes, puis immédiatement en moins d'une seconde, il rechargera la page.

**Comment by zoic21** [comment]
Malheureusement je reproduis pas donc ça va être compliqué de faire quoique ce soit de mon coté. C'est bien avec chrome comme navigateur ? Ca le fait aussi en local ? Avec un autre pc client ? La vraiment si je reproduis pas pour moi c'est exterieure a Jeedom (ou un plugin tierce peut etre)

**Comment by Grzywax** [comment]
J'ai testé avec Firefox, Chrome, IE. Peut-être que c'est une relation avec
Apache et Jeedom? C'est juste sur ces plusieurs pages qu'il ne charge même
rien pendant 10s - exactement 10s (10,5s pour être exact).
Si je frappe F5 pour le rafraîchir, il ne fait rien pour 10s et ensuite il
recharge cette page dans les 0,5s. C'est plus comme le serveur web sur ces
quelques pages attend 10s pour rejouer, pour alimenter la page vers le
navigateur. Y a-t-il quelque chose de spécifique dans le code de ces pages
(Jeedom Setup, chaque configuration de commande et la santé de Jeedom)?

Patryk


2017-10-06 9:35 GMT+02:00 Loïc <notifications@github.com>:

**Comment by Grzywax** [comment]
J'ai trouvé la cause du problème.
J'ai donc le nom d'hôte de no-ip.com et sur mon routeur j'ai un port tcp: 18181 redirigé vers mon serveur jémodie 192.168.1.31 port tcp443. alors, permettez-moi d'utiliser mon jeedom à partir d'Internet en utilisant l'adresse https://myjeedomserver.no-ip.com:18181.
Tout bon pour l'instant.
J'ai donc mis ceci dans ma configuration de Jeedom:
![image](https://user-images.githubusercontent.com/17531396/31300669-31a7fc5a-aaf5-11e7-94a1-10cca79379a9.png)
Donc, avec cette configuration avec des informations réelles qui fonctionnent normalement à partir d'Internet, mais cela ne fonctionnera jamais à partir de mon réseau local car il n'y a pas de redirection pour le port 18181 depuis l'intérieur du réseau.
Avec cette configuration, il y a exactement un délai de 10 secondes (apache timeout ???) sur ces pages: configuration de la commande, configuration de Jeedom, santé de Jeedom.

Ensuite, j'ai essayé de mettre une adresse qui n'existe pas. Mon réseau - pas accessible du tout.
![image](https://user-images.githubusercontent.com/17531396/31300920-c9daae90-aaf6-11e7-86e0-207fa6fe57d6.png)
Avec cette configuration, il y a exactement un délai de 3,5 secondes (autre timeout ???) sur ces pages: configuration de la commande, configuration de Jeedom, santé de Jeedom.


Maintenant, dernière option si je mettrai un bon ip et un port local:
![image](https://user-images.githubusercontent.com/17531396/31301121-036452c8-aaf8-11e7-9d2f-3ed628eb072f.png)


Ou désactivez l'ip externe totalement:
![image](https://user-images.githubusercontent.com/17531396/31301141-1ebd4430-aaf8-11e7-8376-0aae93dec1a6.png)

Avec cette configuration, il y a exactement un délai de 0,5 secondes  sur toute Jeedom.

Il semble que ces pages (configuration de la commande, configuration jeedom ...) comprennent certains appels qui tentent d'obtenir quelque chose via un accès externe (adresse).

Il est aussi source de confusion, comme jeedom dit que cette configuration est seulement informatif et ne pas avoir d'impact sur les connexions jeedom.
![image](https://user-images.githubusercontent.com/17531396/31301256-ef0d8230-aaf8-11e7-802f-f553d14b3d78.png)

Patrick

**Comment by zoic21** [comment]
Pas d'impact sur la connexion à jeedom c'est vrai et informatif aussi mais jeedom ce sert de ça pour pas mal de calcul d'URL. Donc effectivement quand il y a un nok quelques part la dedans ça gêne jeedom et il faut le rendre ok.

**Comment by Grzywax** [comment]
Mais je ne pense pas que cette information devrait être utilisée pour charger des pages. Je veux dire qu'il ne devrait pas conditionner le temps de chargement d'une page.
Je veux dire - faire le calcul pour proposer l'adresse URL (de la commande etc...) - mais ne cherche pas à se connecter avec, especialy surtout pas pendant le chargement de la page.
