### ISSUE TITLE
Pas possible de créer un nouveau widget.

### ISSUE THREAD

**Issue by Grzywax** [jeedom/issues#298]
Lorsque j'essaie de créer un nouveau widget, je reçois cette erreur.
(J'ai essayé différents navigateurs et différents comptes, redémarrez la jémodie - toujours le même)
![image](https://user-images.githubusercontent.com/17531396/31302901-e934b7ae-ab05-11e7-924f-2bf29c3e727a.png)
![image](https://user-images.githubusercontent.com/17531396/31302909-03be894c-ab06-11e7-9576-437d36eb48e2.png)

Patrick

**Comment by skyline-ch** [comment]
Bonjour, 
une correction es en cours et sera disponible courant de la semaine prochaine

**Comment by Grzywax** [comment]
Merci !
