### ISSUE TITLE
[Alarm][Stable] Le temps d'activation n'est pas stable et le problème de réactivation.

### ISSUE THREAD

**Issue by Grzywax** [jeedom/issues#299]
Jeedom : 3.1.7
Alarm : 2017-09-26 11:52:36

Les actions (pas les actions immédiates mais les actions finales) sont lancées après plusieurs heures.
Ecample: Si mon déclencheur est réglé sur 2 minutes pour être activé, les actions "Activation OK" seront lancées parfois après 1 minute, parfois après 30 secondes et si tout va bien - après 2 minutes. (note: l'alarme ne sera pas pleinement activée si les actions sont lancées plus rapidement, mais si cela est déroutant)
Maintenant, le fonctionnement total n'est pas si grave car les déclencheurs ne seront pas activés avant le délai défini dans "Activation". Mais dans mon cas où j'utilise l'ampoule RVB pour afficher l'état d'alarme et ceci est activé dans "Activation OK", cela ne va pas.

Le deuxième problème se produit lorsque j'entre chez moi et que mon alram est activé - donc j'ai 1 minute pour désactiver l'alarme. Donc, je désactive mon alarme après 10 secondes, puis je l'active à nouveau après 30 secondes, et je sors de chez moi. L'alarme s'active correctement - sauf quelques instants plus tard, elle se déclenche automatiquement et les sirènes commencent. et tout est fermé - pas de mouvement, toutes les portes sont fermées.

Il semble que dans cette situation, je dois attendre une minute avant de réactiver l'alarme. Cela ne devrait pas fonctionner de cette façon.

**Comment by zoic21** [comment]
Bonjour,
Merci avant de poster une issue de bien les livres le recommandation. Là c'est n'importe quoi.

**Comment by Grzywax** [comment]
EN
I'm sorry maybe because my French is not the best, but I'm trying the best to help jeedom'a team. 
I have paid for this plugin and since two years this was not fixed (despite my bug reports in application).
Let me show screenshots to better understand the problem.
______________
**FR:
Je suis désolé peut-être parce que mon français n'est pas le meilleur, mais j'essaie d'aider l'équipe jeedom'a.
J'ai payé pour ce plugin et depuis deux ans ça n'a pas été corrigé (malgré mes rapports de bugs dans l'application).
Permettez-moi de montrer des captures d'écran pour mieux comprendre le problème.**

I have one sensor in "Door Upstairs" zone and it's Trigger time is set to 1 min:
**FR
J'ai un capteur dans la zone "Door Upstairs" et son temps de déclenchement est réglé sur 1 min:**
![image](https://user-images.githubusercontent.com/17531396/31523883-7fbcbf46-afb6-11e7-85b6-1ae659030e1c.png)

I have Test mode where I'm suing only "Door Upstairs" zone.
**FR
J'ai le mode Test où je poursuis uniquement la zone "Door Upstairs".**
![image](https://user-images.githubusercontent.com/17531396/31523958-d57ea89a-afb6-11e7-819f-b92d8e8d20a7.png)

When I activate my "test" mode immediate actions (orange - 1)  are started instantly 
My understanding is that "Green" action - number 2 on image should start after 1 minute (Trigger time):
**FR
Lorsque j'active mon mode "test", les actions immédiates (orange - 1) sont lancées instantanément
Je crois comprendre que l'action «verte» - numéro 2 sur l'image devrait commencer après 1 minute (temps de déclenchement):**
![image](https://user-images.githubusercontent.com/17531396/31524040-5d230b06-afb7-11e7-8ee5-835d166a18a7.png)

But "Green" actions are lunched sometimes after 1 minute, sometimes after 10 seconds or 20 secons or 34 secons.... 

Is that clearer information now ?

**FR
Mais les actions "vertes" sont lancées parfois après 1 minute, parfois après 10 secondes ou 20 secondes ou 34 secondes ....
Est-ce que cette information est plus claire maintenant?**
