### ISSUE TITLE
[CORE] [BETA] Log de mise à jour du slave ne s'affiche pas sur le master

### ISSUE THREAD

**Issue by Ssshafi** [jeedom/issues#3]
Lors d'un lancement de la mise à jour du slave à partir du maître, le message en vert (Le système est en cours de mise à jour) s'affiche bien mais la textbox où est censé s'afficher le log en direct reste vide.
**-Version :** Beta : Mise à jour le 2016-06-07 10:45
**-Plugins :** Rfxcom, Z-Wave, App Mobile, Data Transfert, Mail, OpenVPN, SMS, Slack, Agenda, Outil de Dev, Script, Virtuel, Widget, Camera, RTSP, Geoloc, Forecast.io, Weather : Mise à jour le 2016-06-07 10:45

Rien dans la console F12
J'ai vidé le http.error (master) avant de lancer la màj et il reste vide
Le jeenetwork n'a rien à part les notif de nouveau message.
Rien dans ces logs au niveau du slave non plus.
Sur le slave le log update y'a bien tout.

![majslave](https://cloud.githubusercontent.com/assets/11499123/15856970/14b652f6-2cb9-11e6-8914-b8a72a658f4a.png)

**Comment by zoic21** [comment]
Corrigé : https://github.com/jeedom/core/commit/bf456d3186534544f68f0f57a9a3be55e28e7c47

**Comment by zoic21** [comment]
Peux tu faire F12 puis console et me donner le retour ?
