### ISSUE TITLE
[CAMERA] Template Foscam R2

### ISSUE THREAD

**Issue by PuNiSHeR374** [jeedom/issues#30]
Bonjour,

Cela fait maintenant près de 2 mois que j'ai acheté une Foscam R2. N'étant pas encore intégré en natif dans le plugin Caméra, j'ai fait un template des commandes Principal de l'API pour usage personnel.

Je la partage avec vous, après, à vous de voir si vous voulez l'intégrer ou pas dans le plugin.
Cette caméra est de très bonne qualité, j'en suis plus que satisfait, aucun reproche à faire et les commandes fonctionnes parfaitement.

Commandes : 

Gauche, droite, haut, bas, Zoom In, Zoom Out, IR On, IR Off et j'ai ajouté la possibilité de configurer 5 Preset.

Les presets ne sont pas défini par des chiffres, mais par un Nom à attribuer lors de la programmation de celui-ci.

Bonne journée et bon courage dans vos debugs.

[camera.zip](https://github.com/jeedom/issues/files/375764/camera.zip)

**Comment by zoic21** [comment]
Bonjour,
merci pour l'ajout je viens de l'inclure dans le plugin
