### ISSUE TITLE
[DESIGN] Limites de déplacement des widgets de taille !=1

### ISSUE THREAD

**Issue by fwehrle** [jeedom/issues#301]
Bonjour,

Lorque l'on change la taille d'un widget dans un design et qu'on lui affecte une taille de widget <1 dans le paramètre d'affichage, il n'est plus déplaçable jusqu'au bord inférieur droit du design.
Testé avec un équipement du plugin camera, mais idem avec un virtuel.
Comme si la limite ne tenait pas compte du changement de taille.
Rien dans les logs, ni dans la console (F12).
Jeedom v3.1.7

**Comment by zoic21** [comment]
Bonjour,
C'est un bug connu du au navigateur. Nous ne pouvons rien y faire.

**Comment by fwehrle** [comment]
Ah ok.. je n'avais rien vu ici et sur le forum.. J'essayerai avec un autre navigateur.
Je suis sur Chrome.
Merci à toi

**Comment by zoic21** [comment]
Tous les navigateurs ont le meme soucis

**Comment by fwehrle** [comment]
Ah? tu aurais une réf du problème par hasard?

**Comment by zoic21** [comment]
Non c'est juste par analyse on voit que le navigateur ne prends pas la taille avec le paramètre zoom d'ou le soucis.
