### ISSUE TITLE
[Plugin Camera] Log dans camera_record systematique

### ISSUE THREAD

**Issue by fwehrle** [jeedom/issues#302]
Hello,

Lors d'un enregistrement, d'un snapshot ou lors du lancement et arret de l'enregistrement, le plugin ecrit dans le fichier camera_record.
Si ca n'a d'autre objectif que le debug (sinon, ne pas tenir compte de cette issue), je propose de remplacer : 
$cmd .= ' >> ' . log::getPathToLog('camera_record') . ' 2>&1 &';
Par : 
$cmd .= ' >> /dev/null 2>&1 &';
Ceci pour eviter de remplir ce fichier pour rien.

Voir pour ne le remplacer que si le log n'est pas en level debug?

**Comment by zoic21** [comment]
Bonjour,
Pour l'instant on prefere le laisser pour du debug une fois qu'on sera sur de la fonction on le retirera.

**Comment by fwehrle** [comment]
Bonjour,

Ok. Nickel. 
Merci pour le retour.
