### ISSUE TITLE
[Core] restauration de back up

### ISSUE THREAD

**Issue by Babatou** [jeedom/issues#303]
Sur jeedom 3.1.7 et Débian 9, message d'erreur :

The stream or file "/var/www/html/core/class/../../log/plugin" could not be opened: failed to open stream: Permission denied"

**Comment by bphoque** [comment]
Bonjour,

Il faut taper ceci dans un terminal pour remettre les droits : 

chmod -R 775 /var/www && chown -R www-data:www-data /var/www

**Comment by Babatou** [comment]
Merci pour ta réponse mais ceci est très très fréquent, il s'agirais semble t il plus d'un bugg.

**Comment by zoic21** [comment]
Ce n'est pas un bugs
