### ISSUE TITLE
Gaphique des liens

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#304]
Bonjour,

Ce serait bien dans les graphiques des liens que les icones puissent être différent en fonction du type de configuration.

A+
Thomas

**Comment by zoic21** [comment]
Bonjour,
Je comprends pas la demande si c'est mettre une image spécifique en fonction de l'équipement c'est déjà possible depuis longtemps.

**Comment by guenneguezt** [comment]
Bonjour,

Certains plugins gèrent des équipements de nature différente. Du coup, le logo pour tous les équipements est celui du plugin.
Par exemple se basé sur la variable de configuration si elle existe.
En fait en creusant, je peux réimplémenter la fonction getImage() pour ma classe d'équipement en fonction de ma variable de configuration.

A+
Thomas
