### ISSUE TITLE
Doc plugin template

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#308]
Bonjour,

En regardant le plugin template, le fichier https://github.com/jeedom/plugin-template/blob/master/plugin_info/info.json , j'ai des doutes et je ne sais pas où trouver l'information pour les lever.
La "category" doit a mon sens appartenir à une liste. Mais impossible de trouver la liste.

J'ai fait un grep dans mes plugin et j'ai :
 automation protocol
 automatisation
 communication
 devicecommunication
 energy
 finance
 health
 monitoring
 multimedia
 nature
 Objets connectés
 organization
 programming
 security
 Thermostat
 travel
 weather
 wellness
Certains me paraissent étrange.
Il faudrait peut-être mettre un commentaire dans le json template la liste de ceux autorisés ?

A+
Thomas

**Comment by zoic21** [comment]
Tu peux mettre ce que tu veux aucune limite coté jeedom pour celle déja existe tout est dans le fichier de config du core de jeedom

**Comment by guenneguezt** [comment]
Merci, j'en ai profiter pour proposer d'ajouter au plugin template :
https://github.com/jeedom/plugin-template/pull/22
