### ISSUE TITLE
[OPENZWAVE] POPUP "démarrer l'inclusion" --> mettre en mode non sécurisé par défaut ?

### ISSUE THREAD

**Issue by domotiquestore** [jeedom/issues#31]
Bonjour Nechry,

Suite à la dernière version du plugin OpenZWave, nous avons rencontré pas mal de souci avec des clients qui n'arrivaient pas à inclure correctement leurs modules (modules mal reconnus en ou en "unknown" alors que le template existe).

Nous avons par exemple reproduit le problème avec un module Qubino ZMNHTD1 dont le type et numéro de modèle étaient différents et manifestement erronés lors d'une tentative d'inclusion sécurisée mais était parfaitement reconnu en inclusion normale. 
A noter que pour le moment, les modules Qubino Z+ ne gèrent pas l'inclusion sécurisée.

Nous pensons qu'une inclusion en mode non sécurisé par défaut limiterait les problèmes et qu'une petite phrase affichée à droite du mode sécurisé et qui dirait "veuillez vérifier que votre module gère le mode sécurisé. En cas d'échec d'inclusion ou de module mal reconnu, nous vous recommandons de l'exclure et de le ré-inclure en mode non sécurisé".

Autre idée : ajouter en bas de fenêtre un lien vers la section du manuel qui traite de l'inclusion / exclusion.
En effet, nous avons de plus en plus de clients "grands débutants" qui choisissent Jeedom et beaucoup bloquent à cette étape et ont tendance à se perdre dans la documentation du plugin qui, bien qu'elle soit très bien faite, est tout de même très dense.

Cordialement,
Jérôme domotique-store

**Comment by nechry** [comment]
@domotiquestore  Il serait préférable de faire les Issues du plugin dans le projet openzwave.

J'ai inclue plusieurs modules qui ne gère pas la classe Security ou encore ne sont même pas en ZWave+ sans problème. je suis plutôt étonné de votre remonté. bien entendue je n'ai pas validé avec la totalité des modules sur le marché.

Les inclusions sécurisé par défaut sont le mode standard sur la plus par des box qui gère le ZWave+. Avez vous essayé le même module sur une autre box?

Pour ce qui est d'ajouter le commentaire j'avais initialement pensé le faire.

Je vais voir si c'est envisageable d'inclure un lien sur une section de la documentation.

**Comment by domotiquestore** [comment]
@nechry suite à ta remarque, nous avons fait des tests sur 6 modules Qubino Z+ après avoir réinitialisé notre contrôleur Z-Wave ... Tout a parfaitement fonctionné.
Les soucis constatés sur la jeedom de notre labo étaient donc probablement causées par un problème de contrôleur Z-Wave (on fait des tests toutes la journée et même si on le réinitialise régulièrement on peut parfois avoir des bugs bizarres).

Pour les autres cas, après vérification auprès de mes collègues, on a eu des soucis avec un module vision (mais suspicion de défaut du module) et des problèmes sur ... eedomus (oups ! incompréhension avec un des collègues).

Toutes mes excuses, donc, pour cette issue non justifiée (garde tout de même l'idée des aides).

PS: Félicitations pour ton travail, le plugin ZWave est un modèle du genre ;)

Jérôme.

**Comment by nechry** [comment]
@domotiquestore merci du retour et de la confirmation du bon fonctionnement. Il est toute fois pas impossible pour un module très spécifique que l'inclusion Secure, bien que retro-compatible en non secure, ne passe pas. C'est pour pour cette raison que j'ai donné la possibilité de faire une non secure sans devoir aller chercher trop loin. 

dès que j'ai un peux de temps je regarde pour ajouter une note à l'assistant d'inclusion ainsi que la possibilité de lancer un page dur la doc section inclusion.
