### ISSUE TITLE
[CORE] Modifier la conf d'un plugin

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#310]
Bonjour,

Lorsque l'on modifie la configuration d'un plugin, celui-ci n'est pas informé de leur modification.
Il serait intéressant si l'on modifie une variable comme dans la source suivante :
https://github.com/jeedom/core/blob/master/core/ajax/config.ajax.php#L76
Que ça appelle un fonction static de class de plugin si elle existe genre "configChange".

A+
Thomas

**Comment by zoic21** [comment]
Bonjour,
Ça existe déjà faut regarder la classe config
