### ISSUE TITLE
[Core/Command] Mauvais calcul StateDuration

### ISSUE THREAD

**Issue by Grzywax** [jeedom/issues#311]
Jeedom 3.1.7 sur esxi VM (Debian)
(Tous les plugins dans les dernières versions)

J'ai virtuel # [Test] [vEgg toilettes vers le bas] [Motion] # qui est réglé sur "1" par motion sersor 433Mhz. Cette commande virtuelle n'est jamais réinitialisée à "0" donc une fois qu'elle est réglée à un par le capteur elle reste à "1" - mais à chaque détection du capteur StateDuration de cette commande virtuelle est en train de se réinitialiser à zéro.

Ici, nous voyons que le capteur virtuel et le capteur déclencheur ont la même StateDuration
![image](https://user-images.githubusercontent.com/17531396/31867470-b7b01a88-b790-11e7-9e85-7601d9588e69.png)

Ici, nous pouvons voir que la commande virtuelle est tout le temps à "1" - elle ne change pas son état mais sa StateDuration est réinitialisée.
![image](https://user-images.githubusercontent.com/17531396/31867526-a965259e-b791-11e7-8580-cf460fc2204a.png)

**Comment by Grzywax** [comment]
Pourquoi est-il fermé? Est-ce qu'une solution est bientôt disponible? Ou ce n'est pas un problème valide? Ou l'information n'est pas suffisante?

**Comment by zoic21** [comment]
Fermé car résolu le commit qui résous le soucis est dans le lien.

**Comment by Grzywax** [comment]
Parfait ! Je suis heureux de pouvoir aider.

**Comment by Grzywax** [comment]
Parfait ! Je suis heureux de pouvoir aider.

2017-10-23 13:56 GMT+02:00 Loïc <notifications@github.com>:
