### ISSUE TITLE
Amélioration du systeme de support utilisateur

### ISSUE THREAD

**Issue by zoic21** [jeedom/issues#314]
A étudier mais je pense que l'on pourrait améliorer le systeme de support  : 
- faire une sorte de pastbin pour les logs
- idem pour l'envoi d'un backup

Scénario type : l'utilisateur ouvre un ticket au support pour un probleme. Suite à l'analyse il nous manque soit des infos, soit un accès, soit il faut qu'on reproduise chez nous. On peut donc dans l'interface de jeedom créer un menu support. Dans celui-ci on retrouve 3 actions possible : 
- envoi des logs au support
- envoi d'un accès au support
- envoi d'un backup

Pour que ça soit possible le support devra communiquer un code à l'utilisateur (code généré par le market qui validera la demande) et ajoutera au profils de l'utilisateur la demande (log/backup/accès)

**Comment by rocket13011** [comment]
très bonne idée ! peut-être un lien clivable plutôt qu'un code, comme ça l'utilisateur a juste a cliquer sur celui-ci pour confirmer non ?

**Comment by zoic21** [comment]
A voir le code est beaucoup plus simple a gérer surtout si c'est pas le market qui gère ça

**Comment by rocket13011** [comment]
il faut trouver le plus User-Friendly possible, a réfléchir au mieux.
