### ISSUE TITLE
Templace de widget

### ISSUE THREAD

**Issue by zoic21** [jeedom/issues#316]
Créer un systeme de template de widget, type le widget prise ou l'utilisateur peut choisir l'icone on et l'icone off. Plus tard on pourra l'étendre  avec des images. Dans l'idée on recherche des tags type : #icon_xxx# dans le code du widget. On pourrait même imaginer une entête en début de widget qui liste les tag template et les valeurs par défaut.

On pourra comme ça diminuer grandement le nombre de widget du core et permettre une plus grande personnalisation sans passer par le plugin widget.

**Comment by Sartog** [comment]
Excellente idée (tu sais vendre du rêve toi :) )!

C'est déjà possible à faire grâce aux Paramètres optionnels widget et en adaptant le code du widget, mais il faut se rappeler de la syntaxe à utiliser et il faut penser à mettre à jour son widget quand nécessaire.

Une liste déroulante, toujours dans Paramètres optionnels widget, permettant de choisir l'icone / l'image souhaitée parmi les images présentent dans le widget serait bien pratique !

Peut-être étendre l'idée à un widget "texte" (type line ou title) un peu plus personnalisable pour éviter de devoir créer un widget par mise en forme ?
