### ISSUE TITLE
[MOBILE][BETA] lancement impossible d'un scenario depuis la page des favoris

### ISSUE THREAD

**Issue by magicgg91** [jeedom/issues#32]
Problème reproduit sous iOS et Android
Jeedom 2.3.12/2.4
Appli 1.0 (92) et 1.0.1

Depuis la page des favoris, ajout d'un scenario OK
Par contre, lancement impossible

Alors que le lancement d'un scenario depuis la page des scénarios est OK, et aussi depuis le dashboard OK

**Comment by rocket13011** [comment]
corrigé 1.0.1
