### ISSUE TITLE
Supprimer les quotes automatique dans l'évaluation des expressions

### ISSUE THREAD

**Issue by zoic21** [jeedom/issues#322]
Bien que le systeme de cote automatique soit pratique (ajout des " automatiquement autour des commandes) celui-ci pose de nombreux soucis avec le systeme de tag dans les scénarios. Ces problèmes n'ont malheureusement pas de solution possible dans le code (le code ne peut pas deviner ce qui doit être entouré de " ou pas car il ne sait pas quoi on parle). Il faudrait donc retirer ce systeme de cote automatique (en plus on gagnera un peu de performance dans l'évaluation des condition). A noter que cela à un impact sur les utilisateurs qui devront revoir leur scénario. Exemple : 
variable(test) == "toto" devient "variable(test)" == "toto"
trigger(#[object][eqLogic][cmd]#) == 1 && #[object][eqLogic][cmd]# == 1 && #[object][eqLogic][cmd]# == "Absent" devient trigger(#[object][eqLogic][cmd]#) == 1 && #[object][eqLogic][cmd]# == 1 && "#[object][eqLogic][cmd]#" == "Absent"

**Comment by Sartog** [comment]
Bonjour Loïc,

Si j'ai bien compris et en prenant ton exemple #[object][eqLogic][cmd]# == "Absent" deviendra "#[object][eqLogic][cmd]#" == "Absent" (et admettons que #[object][eqLogic][cmd]# vaut Présent), en supprimant les quotes, nous tomberions donc sur l'évaluation Présent == "Absent", retournant une erreur (je suppose).

N'est-il pas possible, dans le core, de mettre une vérification du type de l'information et d'y mettre les quotes si elle est du type string (par exemple) ?

Bon après, si il faut mettre des quotes dans une partie des mes évaluations ça ne me pose pas de problème mais il est vrai que ce n'est pas naturel.

**Comment by zoic21** [comment]
Si c'est possible c'est ce que fait jeedom actuellement mais ça pose des soucis sur d'autre partie de jeedom car il ne sait pas quand il faut mettre des quote au variable ou au tag c'est beaucoup trop complexe car dépend du contexte. Le mieux est que l'utilisateur gère ça lui même.

**Comment by Sartog** [comment]
👍 

Merci pour ta réponse
