### ISSUE TITLE
[ZWAVE][BETA]

### ISSUE THREAD

**Issue by ZitouneOlivier** [jeedom/issues#328]
Image du nas_wr01za power plug n'est pas détourée... La voici en version propre !!
![600 3 4231_nas wr01ze power plug](https://user-images.githubusercontent.com/16152728/32286418-af24885a-bf2d-11e7-88a6-091932c7b583.jpg)

**Comment by romanais** [comment]
Bonsoir, je débute sur Github.
Si j'ai d'autres images de ce types retouchées, est-ce que je peux les poster toutes ici ?

**Comment by zoic21** [comment]
Bonjour,
Non ca ne sera bientot plus possible on est en train de migrer de github a jira pour mieux gerer le projet il faudra attendre que l'on maitrise bien l'outils pour qu'on reouvre ce genre de possibilités.
