### ISSUE TITLE
[CORE] Sauvegarde - Pouvoir paramétrer le nombre et taille en fonction de la destination

### ISSUE THREAD

**Issue by Sartog** [jeedom/issues#329]
Bonjour,

Utilisant la fonctionnalité de sauvegarde SAMBA (celle du core) sur un NAS Synology, cette dernière a les mêmes restrictions que la sauvegarde en local (que j'ai mis à 30 jours et 3Go).

L'espace de stockage étant moins important en local que sur NAS, il serait intéressant de pouvoir paramétrer les restrictions (nombre de sauvegarde et taille maxi) en fonction de la destination de stockage.
Cela permettrait de soulager le stockage local au profit du stockage NAS.

A disposition pour en parler.

Matériel :
- Smart sous Jeedom 3.1.17

**Comment by zoic21** [comment]
Bonjour,
C'est trop compliqué a mettre en place pour l’intérêt et la demande désolé....

**Comment by Sartog** [comment]
Ok, je comprends.
Merci Loïc de m'avoir répondu.
