### ISSUE TITLE
Fichier inutile dans un plugin

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#331]
Lorsque des fichiers d'un plugin sont supprimé, il semblerait que la mise à jour du plugin ne les supprime pas.
Quel est la meilleur solution pour les supprimer ?
Faut-il mettre des unlink dans plugin_info/install.php function monplugin_update.php ?

Merci
Thomas

**Comment by zoic21** [comment]
Bonjour,
Effectivement la solution est dans le function update du plugin.
