### ISSUE TITLE
[CORE] [JSON RPC] Enhancement - possibilité de créer/sauvegarder un cmd

### ISSUE THREAD

**Issue by mch1307** [jeedom/issues#335]
Merci pour #333 et #334, c'est top !
En rapport avec la #333, serait-il possible d'implémenter une méthode "save" pour un cmd?

**Comment by zoic21** [comment]
C'est ajouté

**Comment by mch1307** [comment]
Super, Merci!!

**Comment by mch1307** [comment]
Comme je suis un peu dessus, je veux bien essayer de mettre la doc json rpc à jour.
Dites-moi comment procéder si ca vous intéresse ;)

**Comment by zoic21** [comment]
Elle a été mise à jour en même temps que les modifications.

**Comment by mch1307** [comment]
autant pour moi, je ne regardais pas la bonne branche..
