### ISSUE TITLE
[CORE][BETA] JSON RPC - cmd::save renvoie "Type Incorrect"

### ISSUE THREAD

**Issue by mch1307** [jeedom/issues#339]
### Version 
core 3.1.8
### Developpement lié: 
#335
### Probleme:
L'api renvoie systematiquement une erreur "Type Incorrect" quand on appelle cmd::save
Je pense que le probleme se trouve dans les lignes 634-635 dans jeeAPI.php:
```
if ($jsonrpc->getMethod() == 'cmd::save') {
	$typeEqLogic = $params['eqType_name'] . 'Cmd';
	if ($typeEqLogic == '' || !class_exists($typeCmd)) {
```
Le $typeCmd n'est pas initialisé. J'ai essayé en remplacant `!class_exists($typeCmd)` par `!class_exists($typeEqLogic)` et ca a l'air de fonctionner

**Comment by mch1307** [comment]
Désolé, ca ne fonctionne pas, par analogie, je pense qu'il faut tester la class avec et sans le 'Cmd' non?
J'ai fait comme ca et ca fontionne
```
if ($jsonrpc->getMethod() == 'cmd::save') {
    $typeEqLogic = $params['eqType_name'];
    $typeCmd = $params['eqType_name'] . 'Cmd';
    if ($typeEqLogic == '' || !class_exists($typeCmd) || !class_exists($typeEqLogic)) {

```

**Comment by zoic21** [comment]
Et maintenant ?

**Comment by mch1307** [comment]
Tu as refait une modif? Je ne la vois pas.
Celle d'y a une heure ne fonctionne pas

**Comment by zoic21** [comment]
j'ai oublié de la pousser la ca devrait etre bon.

**Comment by mch1307** [comment]
ok je reteste.
Il y a un moyen de forcer l'update du core quand on est deja en 3.1.8?
J'ai pas trouvé,donc l'update le fichier a la main avec un get..

**Comment by zoic21** [comment]
Oui cliquer sur le bouton "Mettre à jour"

**Comment by mch1307** [comment]
Oui je me doutais ;)
mais il ne fait rien

**Comment by zoic21** [comment]
Si si il mets a jour jeedom même si aucune mise à jour n'est détecter . Attention c'est en fonction de la branche sur laquelle Jeedom est configuré.

**Comment by mch1307** [comment]
ah ok, je suis sur le master.
Bon à savoir
Sinon ca fonctionne  maintenant.
By the way, j'ai vu qqs incohérences dans la doc rpc, je les remonte? Si ca peut aider..
Merci

**Comment by zoic21** [comment]
Oui oui faut pas hesiter ou par merge request.

**Comment by mch1307** [comment]
ok, meme pour un .MD?
Apres je ne sais pas toujours si c'est un bug de la doc ou du code ;)
