### ISSUE TITLE
[Core] valeur fantôme dans l’historique

### ISSUE THREAD

**Issue by scotty92fr** [jeedom/issues#341]
Version Jeedom :  3.1.7

Bonjour,

Je viens de m’apercevoir que j'ai une valeur fantôme dans les courbes d'historique:

J'ai paramétré une courbe :  ![capture d ecran 2017-11-12 a 08 31 46](https://user-images.githubusercontent.com/6825089/32696902-1b343438-c784-11e7-8e3f-3af815d61e7d.png)

quand je coche « Variation » , j’obtiens: ![capture d ecran 2017-11-12 a 08 34 44](https://user-images.githubusercontent.com/6825089/32696911-65511c5c-c784-11e7-9999-6cb5af16b3ce.png)  or si je comprends bien normalement elle devrait redescendre à 0 

c'est encore plus flagrant en mode barre: ![capture d ecran 2017-11-12 a 08 36 42](https://user-images.githubusercontent.com/6825089/32696932-aeb295b0-c784-11e7-8710-882393d845cf.png)

La courbe d'origine est juste. La dernière valeur (celle du dernier jour) reprend la dernière valeur obtenue. Hier c'était pareil, mais à la date d'hier. 

je ne retrouve pas ce comportement pour une valeur qui a une variation entre hier et aujourd'hui.

Cordialement 
Scotty92fr

**Comment by zoic21** [comment]
Bonjour,
Je comprends pas tout mais je pense pas qu'il y ai un bug. Jeedom prolonge la dernière valeur du graphique jusqu'a la date de fin d'ou le comportement constaté.

**Comment by scotty92fr** [comment]
Bonsoir Loic,

ok Loic, c'est pas bien grave mais juste pour expliquer

Sur le premier graphique, entre le 9 le 10, la valeur passe de 16689 à 16690 soit un delta de 1, les jours suivant pas d'augmentation.
En passant en variation, j'ai bien le pic entre le 9 et 10 mais je devrais être à 0 les jours suivant. mais Jeedom reprends la valeur 1 le jour de la date de fin ce qui n'est pas normal  sinon cela ferait 2 en variation pour la période

**Comment by zoic21** [comment]
Ok je vois donc pas de bug le delta c'est entre 2 valeurs si la valeur bouge pas pas de nouveaux calcul de delta que ça fasse un jour un an ou dix ans. Chez toi pas de nouvelles valeur le delta n'est donc pas recalculé.
