### ISSUE TITLE
[CORE] Mcrypt

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#342]
Le core de jeedom et certaines extensions placées dans vendor utilisent mcrypt (php-mcrypt). 
La libraire mcrypt (dédiée à la sécurité) qui est appelée par php-mcrypt, n'est plus maintenue depuis 8 ans !
Pas de correction de bug ni rien !!! Pour une lib dédiée à la sécurité c'est un problème.
Je recommande la suppression de cette extension du projet et de ses dépendances. 

- [http://php.net/manual/fr/intro.mcrypt.php](http://php.net/manual/fr/intro.mcrypt.php)
- [https://en.wikipedia.org/wiki/Mcrypt](https://en.wikipedia.org/wiki/Mcrypt)

**Comment by zoic21** [comment]
Bonjour,
Cette extension est utilisée dans vendor, il est donc difficile de la supprimer comme ca sans creer de gros bugs. De toute facon elle n'est jamais utilisée pour de la sécurité donc pas besoin de la supprimer.
