### ISSUE TITLE
[plugin] [camera] affichage heure GMT

### ISSUE THREAD

**Issue by Babatou** [jeedom/issues#343]
Les cameras prennent en compte l'heure GMT et non la time zone.

**Comment by zoic21** [comment]
Bonjour,
Je suis pas de comprends merci de détaillé un peu plus... La je comprend que leur affiché sur le flux des caméras et pas bon. Cela n'est pas géré par jeedom mais par la camera.
Merci de détailler un peu plus les soucis a l'avenir sous peine sinon de fermeture immédiate sans que l'on se penche sur le probleme.

**Comment by Babatou** [comment]
Bonjour,

Autant pour moi, je vais y veiller.
Dans la config Générale de Jeedom l'utilisateur a bien indiqué le fuseau horraire de Paris.
Sa box internet comme serveur de temps
En revanche, l'heure du système reste sur UTC et c'est cette heure qui est utilisée par exemple pour l'horodatage des caméras.
