### ISSUE TITLE
[CORE] [JSON RPC] Enhancement - Ajout de filtre dans API JSON EqLogic

### ISSUE THREAD

**Issue by prysme01** [jeedom/issues#344]
Bonjour, 

En référence a mon post https://www.jeedom.com/forum/viewtopic.php?f=140&t=31447&p=545107#p544912

Serait il possible d'ajouter un ou des filtres pour mieux cibler le retour de la commande eqLogic::fullById afin de limiter le nombre d'information renvoyées par équipement, idéalement soit
- un filtre pour ne renvoyer que la partie de l'arbre qui nous intéresse (path=a.b.c)
- par type d'information (generic_type) ou autre.

L'idée est de limiter le trafic et la charge sur le client (IOT, Rpi..)

Merci d'avance.

**Comment by zoic21** [comment]
Bonjour,
Ça me semble compliqué, cette méthode n'est déjà que sur les équipements donc pas non plus la qu'il y a le plus d'information. De plus mettre en place un filtre ou autre ralentirai la réponse coté jeedom car il faut valider le filtre commande par commande.
Dans ce genre de cas je recommande de faire un plugin coté Jeedom pour justement ce genre de chose, voir par exemple le plugin imperihome qui utilise un fichier json template charger dans lequel on vient remplacer les valeurs des commandes (sans accès BDD en passant directement par le cache).

**Comment by prysme01** [comment]
Je comprend mais sans aller jusqu’à valider ou implémenter des filtres de fou, un simple filtre byCmdID en plus pour ne renvoyer que la section de la commande demandée, c'est inenvisageable ?

**Comment by zoic21** [comment]
Ca existe déja donc pas trop envi de dupliquer.... Comme dit sur le forum c'est dans la doc.

**Comment by prysme01** [comment]
Merci effectivement ca existe avec la API JSON Cmd | cmd::execCmd
