### ISSUE TITLE
Absence de répertoire /var/www/html/tmp

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#346]
Bonjour,

J'ai plusieurs utilisateurs de plugin confronté à l'absence de répertoire /var/www/html/tmp.
Je pensais que ce répertoire été créé par Jeedom.
Avez-vous une idée ?
Le problème semble surtout concerner debian 9.
https://www.jeedom.com/forum/viewtopic.php?f=140&t=2439&start=640
https://www.jeedom.com/forum/viewtopic.php?p=536856#p535732

A+
Thomas

**Comment by zoic21** [comment]
Bonjour,
C'est normal il faut maintenant passer par jeedom::getTmpFolder('id_plugin') qui renvoi le chemin vers le dossier tmp pour le plugin en question

**Comment by guenneguezt** [comment]
Merci 👍
