### ISSUE TITLE
[MOBILE][BETA] Espeasy, affiche une seul température du noeud 

### ISSUE THREAD

**Issue by tocks53** [jeedom/issues#35]
Problème reproduit sous iOS
Jeedom 2.4.3
Appli 1.0.1

Le problème est que l’application affiche que une seul des températures d'un noeud ESPEASY.
Pourtant les generique_type sont bien renseignés

![selection_526](https://cloud.githubusercontent.com/assets/7701808/17242813/8a2e299e-5579-11e6-9bca-ab53198dd797.png)
 

De plus actuellement, il y en a deux, mais il faut prévoir un nombre de température indéfini

**Comment by rocket13011** [comment]
il faudra les intégrer avec le generic_type Générique ( sur la v1.0.1 ) non temperature.
