### ISSUE TITLE
[MOBILE][BETA] Generique_type Chauffage

### ISSUE THREAD

**Issue by tocks53** [jeedom/issues#37]
Problème reproduit sous iOS 10
Jeedom 2.4.3
Appli 1.0.1

Mes chauffages électriques sont contrôlé par des module zwave relay.

De base jeedom, les a configuré comme des lampes.

J'ai donc modifier les génériques_types comme cela, même si je n'utilise pas le fil pilote.

![selection_528](https://cloud.githubusercontent.com/assets/7701808/17243319/5c97048a-557c-11e6-9410-193c83f7d343.png)

Mais cela me met une erreur sur l'application jeedom

[DISPLAY] undifined is not an object (eveluating 'e.energy.off)

**Comment by rocket13011** [comment]
1.1.0 (13)
