### ISSUE TITLE
[APP][1.2] Generique_type Détection  de fumée pas appliqué sur les commandes chaleurs

### ISSUE THREAD

**Issue by tocks53** [jeedom/issues#38]
Problème reproduit sous iOS 10
Jeedom 2.4.3
Appli 1.0.1

Le generique_type n'est pas ajouter automatiquement sur la commande chaleur

![selection_527](https://cloud.githubusercontent.com/assets/7701808/17243430/117d8b1c-557d-11e6-887b-77f1c5076bee.png)

**Comment by rocket13011** [comment]
on part sur issue-app
