### ISSUE TITLE
[MOBILE][BETA] Pièce qui reste visible alors que plus d'équipements

### ISSUE THREAD

**Issue by magicgg91** [jeedom/issues#39]
Jeedom 2.4.4 maj 2016-08-18 09:54:55
Plugin App Mobile maj 2016-08-19 14:09:21

Appli iOS 1.0.1

J'ai 1 pièce qui a des équipements visibles sur le dashboard de Jeedom
J'ai 1 équipement qui a des generic_type configurés
Cette pièce et son équipement sont donc visibles dans les pièces de l'application

J'enlève les generic_type de mon équipement et donc la pièce se retrouve sans aucun équipement configuré pour être envoyé à l'application.

Mais la pièce reste affichée dans l'application, même si elle est vide

**Comment by rocket13011** [comment]
toujours meme souci ?

**Comment by magicgg91** [comment]
Oui,bug toujours présent dans l'appli 1.2.0 (3)

**Comment by rocket13011** [comment]
Modification effectuer sur le Plugin mobile.
