### ISSUE TITLE
[CAMERA][BETA] caractères spéciaux dans le "nom de l'équipement caméra"

### ISSUE THREAD

**Issue by philippeMo** [jeedom/issues#4]
bonjour,
je rencontre un problème avec la capture d'image dans la Version :2016-06-04 14:03:16 
je pense que cela vient des caractères spéciaux dans le nom de l'équipement 
ex : "Cam-Garage/Portail" ne permettra pas de sauvegarder l'image dans le fichier lors d'une capture, dans les dernières versions beta. 
si j’enlève le "/" cela fonctionne correctement.
le problème n'est pas présent sur la version stable avec le même nom d'equipement.
merci

**Comment by zoic21** [comment]
Corrigé : https://github.com/jeedom/core/commit/dfb7562b7e77a289ff3ce3114010112f0526e8af les carracteres \ et / ne devraient pas être autorisé.
