### ISSUE TITLE
[CORE]Composer et dossier vendor

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#41]
Salut,
Comme j'ai du temps, je me suis penché sur le github de jeedom et je me demande pourquoi le dossier vendor à été commité dans le projet car de toute façon on réalise un composer update pour mettre à jours les dépendances.
ce dossier est gros et il alourdi le projet pour rien, il faudrait le passe dans le gitignore. Pour cela il faut le supprimer puis ajouter les dossier dans le .gitignore et faire un commit

**Comment by zoic21** [comment]
Bonjour,
Il n'y a pas de composer update lors de l'installation ou de la mise à jour de jeedom d'ou l'ajout du dossier vendor. De plus cela nous permet de fixer une version facilement et donc de garantir plus facilement l'ensemble de jeedom.

**Comment by ColonelMoutarde** [comment]
Dans ce cas il faut mettre de façon explicite le numéro de version 
`
"doctrine/cache": "^1.4.0"
"doctrine/cache": "1.4.5"
`

**Comment by zoic21** [comment]
Oui oui c'est possible mais plus complexe et si plus complexe plus de chance d'avoir des cas bizarres avec instabilité ou soucis lors du déploiement.
