### ISSUE TITLE
[CORE] Jeedom exceptions

### ISSUE THREAD

**Issue by ColonelMoutarde** [jeedom/issues#42]
Pourquoi créer ses propres exception et ce n'est pas une perte de temps:
- Pour pouvoir plus facilement ajouter des fonctionnalités aux exceptions comme un log automatique ou autre
- Pour bien séparer les exceptions du langage PHP de celle que renvoie Jeedom.
- Pour les créateurs de plugins pour les obliger à travailler avec leur propres exceptions aussi (mais là c'est à voir si c'est pertinent)

J'ai bien conscience que ce changement ne s'improvise pas et il n'est peut-être pas non plus une nécessité immédiate. C'est une réflexion à moyen terme.

Je suis ouvert à vos remarques et suggestion mais si les patrons son ok je veux bien me charger du dev sur une branche à part qui n'aura que cette fonctionnalité.

**Comment by zoic21** [comment]
Bonjour,
Je comprendre bien mais c'est beaucoup trop complexe a faire maintenant et j'aime bien rester sur du standard.
