### ISSUE TITLE
[MOBILE][BETA] suite réinit, impossible de choisir le type d'accueil 

### ISSUE THREAD

**Issue by phifi92** [jeedom/issues#43]
version apps mobile : 1.0.2

Suite à réinit de l'apps mobile, après la configuration via le QRCode, le choix du type d'accueil (SIMPLE ou COMPLEXE) est très difficile.
Par exemple, pour le complexe, il a fallu que je clique en haut à droite de l'image COMPLEXE

**Comment by rocket13011** [comment]
iOS ou Android ?

**Comment by phifi92** [comment]
iOS 10 (dernière bêta) / iPhone 6S

**Comment by rocket13011** [comment]
Ok je regarde demain

**Comment by rocket13011** [comment]
Correction dans la prochaine beta (6)
