### ISSUE TITLE
[MOBILE][BETA] oeil Fibaro, anti-sabotage : Detecté

### ISSUE THREAD

**Issue by phifi92** [jeedom/issues#44]
version apps mobile : 1.0.2
Oeil Fibaro a comme valeur pour l'anti-sabotage : détecté
Alors qu'aucune détection de sabotage est en cours.

idem après actualisation.

**Comment by rocket13011** [comment]
tu peux me donner la valeur de ton état sabotage.

**Comment by phifi92** [comment]
Je viens de faire le test : 
- apps mobile : détecté 
- bouton "tester" de Jeedom : 0

**Comment by rocket13011** [comment]
Ok ton sabotage est en inverse ?

**Comment by rocket13011** [comment]
Fait
