### ISSUE TITLE
[APP][1.1] Generic_type pour Barrier_Operator

### ISSUE THREAD

**Issue by nechry** [jeedom/issues#45]
Ajout d'un type générique afin de gérer plus facilement les modules dédier aux portails.

prise en compte dans l'app mobile avec affichage 2 états 
prise en compte dans homeBridge

**Comment by rocket13011** [comment]
Pour la 1.1

**Comment by rocket13011** [comment]
En cours

**Comment by rocket13011** [comment]
Pas de gachette > mais info OK (gâchette en 1.1.1)

**Comment by rocket13011** [comment]
Pareil que pour garage, present dans prochaine roadmap
