### ISSUE TITLE
[MOBILE][BETA] Generic_type pour Garage_Door_Openner

### ISSUE THREAD

**Issue by nechry** [jeedom/issues#46]
Ajout d'un type générique afin de gérer plus facilement les modules garage door controller

Prise en compte dans l'app mobile:
- 2 états pour les modules simple.
  Etat: Opened (255), Closed (0). 
  Commandes: Open, Close et Stop.
- 5 états pour les vrai contrôleur comme le Aeotec ZW062.
  Etat: Opened (255), Closed (0), Opening (254), Closing (252), Stopped (253).
  Commandes:  Open, Close et Stop

Prise en compte dans homeBridge, possible inspiration:
https://github.com/nechry/homebridge-http-jeedom/blob/master/index.js#L476

**Comment by rocket13011** [comment]
Pour la 1.1

**Comment by rocket13011** [comment]
En cours

**Comment by rocket13011** [comment]
Pas de Gachette pour la 1.1 mais information > OK

**Comment by rocket13011** [comment]
ajout des generic_type garage dans une prochaine Roadmap
