### ISSUE TITLE
[MOBILE][BETA] Confirmer l'action activé -> Oups, Erreur de commande !

### ISSUE THREAD

**Issue by phifi92** [jeedom/issues#47]
Version apps mobile : 1.0.2
iPhone 6S iOS 10

Prenons l'exemple du plugin alarme, sur la commande lock j'ai demandé une confirmation de l'action (OK via Design et Dash). Toutefos, depuis l'apps mobile, que ce choix est activé avec un code, ou sans code, j'obtiens systématiquement l'erreur : Oups, Erreur de commande !

Pour moi c'est une régression, je n'avais pas ce souci avant.

**Comment by rocket13011** [comment]
c'est normal, la function a était ajouter sur la 2.4 dans l'api, cela sera dispo sur l'app avant la sortie de la 2.4 ;-)

**Comment by rocket13011** [comment]
Arrive dans la Build 7 iOS et Build 107 Android
