### ISSUE TITLE
[MOBILE][BETA] - 1 module RFXCOM / 2boutons on-off / 2 etats

### ISSUE THREAD

**Issue by apages2** [jeedom/issues#48]
Version apps mobile : 1.0.2
 iPhone 6 iOS 8.4

Lorsque j'utilise un bouton Chacon en RFXCOM avec 2 boutons ON, 2 boutons OFF, et 2 états.
J'ai configuré les 2 première commandes ON et OFF pour mettre a jour l'etat 1, idem pour les 2 commandes suivantes avec l'etat2.

Dans l'appli mobile (Pièces), quand j'appui sur le bouton 1, l'etat du BT2 se fige, l'etat du BT1 passe sur allumé
impossible de rappuyer sur le BT2, obligé de faire retour puis de revenir ou de raffraichir. Quand je reclique dessus rien ne se passe.
Quand j'appui sur le BT1, le statut alterne de  allumer a eteint (fonctionnement classique)
![config_eqlogic](https://cloud.githubusercontent.com/assets/12720395/18103114/9858fdce-6ef5-11e6-874c-8c657a343624.PNG)
![config_generic_type](https://cloud.githubusercontent.com/assets/12720395/18103113/9856755e-6ef5-11e6-982b-7ad986534db3.PNG)

**Comment by apages2** [comment]
Pour information, j'ai le meme comportement avec le plugin boxio

**Comment by rocket13011** [comment]
possible de tester en mettant les valeur min et max ? sur les états ?

**Comment by rocket13011** [comment]
je clos pas de nouvelle
