### ISSUE TITLE
[MOBILE][BETA] - Probleme Slider dans equipement lumiere

### ISSUE THREAD

**Issue by apages2** [jeedom/issues#49]
Version apps mobile : 1.0.2
 iPhone 6 iOS 8.4
Version Jeedom 2.3 18

Lorsque j'utilise un equipement RFXCOM de type lumière avec Variateur. Le bouton On et Off fonctionne correctement (action et retour d'etat)
Par contre quand j'utilise le slider, l'action se produit bien sur la lampe, mais le slider reviens automatiquement a 0 sur l'appli mobile

**Comment by rocket13011** [comment]
Voir avec la nouvelle Beta iOS

**Comment by apages2** [comment]
Testé avec la derniere Beta 1.0.2(5).

Le problème reste identique sur le slider

**Comment by rocket13011** [comment]
peux tu me donner le « tester », du state de ton RFXCOM ? une fois que tu a modifier ça valeur avec le slider (directement dans la cmd du plugin RFXCOM sur la box )

**Comment by rocket13011** [comment]
Slider OK / souci de configuration de l'etat sur le plugin RFXCOM
