### ISSUE TITLE
[CORE][BETA 2016-06-09 11:22:00] Erreur qui impact le widget "light (core)"

### ISSUE THREAD

**Issue by Masterfion** [jeedom/issues#5]
Le soucis concerne l'option "Retour à la ligne forcé avant le widget" dans l'affichage avancé de la commande ON ou OFF du widget "light (core)" (mais il concerne probablement les autres widgets core).

Le "<br>" est affiché avant le widget mais lorsque le luminaire est ON et que l'on coche l'option "Retour à la ligne forcé" pour le ON et le OFF alors deux "<br>" sont cumulés.

La seule solution consiste à ne cocher cette option que sur la commande ON (si elle l'est uniquement sur la commande OFF, ça ne fonctionne pas lorsque l'état est ON).

**Comment by zoic21** [comment]
Bonjour,
Puis je avoir une capture ?

**Comment by Masterfion** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/16133911/15959626/ef4f4942-2efb-11e6-9a9c-d57f1c006baa.jpg)

**Comment by zoic21** [comment]
OK je comprends comme ca je ne vois pas comment je peux corriger mais je vais y reflechir.

**Comment by Masterfion** [comment]
En mettant le BR dans le code du widget et non avant ?

**Comment by zoic21** [comment]
Pas possible c'est gère par le core pour être compatible avec tous les widgets. C'est donc mis entre 2 widget.

**Comment by Masterfion** [comment]
Sinon tester "si case cochée sur CMD 1 ou si case cochée sur CMD 2..." alors BR (un seul) ?

**Comment by zoic21** [comment]
Pas possible ou alors je ralentirais plus que fortement l'affichage car les commandes ne serait plus indépendante.
