### ISSUE TITLE
[MOBILE][BETA] - Statuts des Scenarios

### ISSUE THREAD

**Issue by apages2** [jeedom/issues#52]
Version apps mobile : 1.0.2(8)
iPhone 6 iOS 8.4

Lorsque j'execute un scenario via un declencheur physique (Inter RFXCOM ou Inter BOXIO), le statut du scenario passe en in progress dans l'appli mobile, mais ne se rafraichit pas automatiquement.

Obligé de forcer la mise a jour (déplacer la fenetre vers le bas sous ios)

**Comment by rocket13011** [comment]
ok sur 1.1 ?

**Comment by rocket13011** [comment]
pas de nouvelle je clos
