### ISSUE TITLE
[MOBILE][BETA] - Template Volet Roulant dans appli mobile

### ISSUE THREAD

**Issue by apages2** [jeedom/issues#53]
Version apps mobile : 1.0.2(8)
iPhone 6 iOS 8.4

Dans le plugin BOXIO, pour un Volet Roulant, j'utilise un bouton UP, un bouton DOWN et un bouton STOP.

Quand j'associe les generics type a mes commandes, (flap_up, flap_down, flap_stop,flap_statut), je n'ai pas de bouton up,down,stop dans l'appli mobile (onglet pieces)

Si je supprime le generique type flap_statut, j'ai mes boutons, mais je n'ai plus de retour d'etat pour le volet

**Comment by rocket13011** [comment]
ok j'ajoute ça ^^

**Comment by rocket13011** [comment]
![capture d ecran 2016-09-07 a 17 36 55](https://cloud.githubusercontent.com/assets/1051575/18318360/b2ce59d8-7521-11e6-952a-bf1d2e4190d1.jpg)

**Comment by rocket13011** [comment]
Prochaine Beta
