### ISSUE TITLE
Proposition de modification sur le core

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/issues#55]
Bonjour,

J'ai fait plusieurs soumissions d'évolution via pull request dont certaines datent de presque 1 mois et je n'ai pas eu de retour. Je sais qu'il y a plein de chose à faire, mais est-ce que quelqu'un les traite ?

Merci
Thomas

**Comment by zoic21** [comment]
Bonjour,
C'est moi qui le fait mais sur mon temps libre ce qui me manque en ce moment....

**Comment by guenneguezt** [comment]
Ok, je comprends ;-) 

En fait c'est que plus ça attends plus il risque d'y avoir des
différences entre le code proposé et la version actuelle. Donc la fusion
sera difficile. 

Bon courage 

Thomas 

Le 2016-09-16 09:09, Loïc a écrit : 

> Bonjour,
> C'est moi qui le fait mais sur mon temps libre ce qui me manque en ce moment.... 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/jeedom/issues/issues/55#issuecomment-247533199
[2]
