### ISSUE TITLE
[CORE] Refonte de la gestion des droits

### ISSUE THREAD

**Issue by zoic21** [jeedom/issues#56]
On supprime la page de configuration avancé (et donc pour la partie technique la table aussi)
ensuite on crée des profils pour les utilisateurs :
- administrateur => peut tout faire
- utilisateur => voit tous les page dashboard, vue, design peut agir sur la domotique mais ne peut rien configurer
- utilisateur limité => ne peut rien par défaut
  En mode utilisateur limité on a en plus un bouton : ajouter droits qui ouvrira une fenêtre ou l'on ajoutera des droits sur des équipements une fois ajouté il pourra les voir et faire des actions dessus

**Comment by ColonelMoutarde** [comment]
Salut,
Pour la gestion du mot de passe il y a cette fonctionnalité robuste qui est arrivée avec php5.5. C'est beaucoup plus robuste que d'utiliser un simple sha1 sur le mot de pass admin.
Pense-tu que ce serai pertinent de l'utiliser ?

**Comment by zoic21** [comment]
Salut,
C'est pas pour ca cette refonte je ne pense pas changer la gestion des mots de passe car c'est assez robuste à mon sens le systeme actuel en plus il y a des sécurité qui empêché le brute force dans jeedom.

**Comment by ColonelMoutarde** [comment]
pour connaitre le mot de passe admin dans l'état actuel tu n'a pas besoin de faire un brut force.
Il suffit de copier/coller le hash dans un site de ce type: [http://md5decrypt.net/Sha1/](url)
pour connaitre un mot de passe possible.

**Comment by zoic21** [comment]
Ils utilisent un dictionnaire pour le faire donc ca marche pas souvent, je viens de tester et il ne décrypte que les mots de passe très simple.

**Comment by ColonelMoutarde** [comment]
normalement tu dois mettre un "salt" du sel en plus de ton mot de passe avant le hashage mais ce n'est pas le cas actuellement.
voici un tuto tres complet
[https://openclassrooms.com/courses/securiser-les-mots-de-passe-des-utilisateurs-avec-php](url)

pour connaitre le mot de passe admin de base c'est très facile il suffit de regarder les sources du projet.
surtout si l'utilisateur ne prend pas la peine de le changer.

**Comment by zoic21** [comment]
Oui oui je connais tout ca mais le salt doit être différent sur chaque jeedom ce qui lors d'une recuperation du backup complique les chose.
Pour le mot de passe par défaut oui il est connu (comme tout les produit web presque) mais il y a un message indiquant qu'il faut le changer.

**Comment by ColonelMoutarde** [comment]
Quand tu install un wordpress par exemple, il te demande de choisir un log in et un mot de passe. Comme cela il n'y en a pas un par défault.

**Comment by zoic21** [comment]
Oui mais nous ne pouvons pas le faire avec le déploiement automatique des images. Donc je ne peux pas changer ca.

**Comment by ColonelMoutarde** [comment]
Je pense que ce sujet mérite réflexion, je te propose si tu est ok pour recopier la discussion sur le forum.
Avec plusieurs cerveau on va bien trouver une solution :)

**Comment by zoic21** [comment]
On peut mais c'est pas du tout le but de cette issue de revoir ça ni même sur la roadmap pour le moment. La sécurité de jeedom a été audité par une société externe nous avons fait les changements recommandé donc je ne ferais pas trop dévolution la dessus.
