### ISSUE TITLE
[SONOS3][BETA] "nom de l'objet" décalé et mauvaise largeur du Widget 

### ISSUE THREAD

**Issue by Masterfion** [jeedom/issues#6]
Bonjour,

Le widget du plugin SONOS3 comporte deux erreurs d'affichage :
- le "nom de l'objet" n'est pas aligné sur le nom de l'équipement
- la largeur du widget doit être augmentée de 15px lors de son insertion dans un design pour que les commandes soient correctement placées (2ème screenshot)

![2016-06-10_115022](https://cloud.githubusercontent.com/assets/16133911/15960860/1a9adf7a-2f02-11e6-9add-e3f00983fd85.jpg)
![2016-06-10_115140](https://cloud.githubusercontent.com/assets/16133911/15960861/1a9b99e2-2f02-11e6-84d3-e212c3380e2d.jpg)

**Comment by zoic21** [comment]
Pour la largeur je réfléchis a comment corrigé car ca casse tous le dashboard si je le fais comme ça (je doute de pouvoir trouver une solution la pour le coup)

**Comment by Masterfion** [comment]
Sur le dashboard, la largeur est bonne pourtant... c'est certainement lié au pas imposé sur les tuiles.
Lors de l'insertion d'un Sonos sur un Design, la largeur n'est pas celle du Dashboard.

**Comment by zoic21** [comment]
C'est ca c'est sur mais c'est pas vraiment contournable
