### ISSUE TITLE
[Legrand Bus] Faire un plugin

### ISSUE THREAD

**Issue by zoic21** [jeedom/issues#62]

**Comment by z0ph** [comment]
Bonjour,

Est-il prévu de faire un plugin pour MyHome (Legrand) ou BTCINO F454 ? Bus SCS

Comme peut le faire cette box domotique: 
http://blog.myombox.fr/tutoriels-myombox/installation-dun-reseau-domotique-filaire-busscs-de-chez-legrand-et-bticino

Merci,

**Comment by guillaume-bzh** [comment]
Bonjour,

+1, car j'ai vu qu'il y a un Plugin MyHome dans le Market Jeedom, mais en fait il est limité à MyHome Play (Protocols Zigbee en sans fil).

Merci par avance.
