### ISSUE TITLE
[WIDGET] File not found : market.list.php

### ISSUE THREAD

**Issue by phifi92** [jeedom/issues#7]
Core : 2016-06-14 19:00:01
Plugin : 2016-03-12 19:04:27
Sur une installation vierge faite directement en bêta, post installation du plugin widget, quand je clique sur Market du plugin Widget, j'obtiens : File not found : market.list.php
Sur cette machine en SSH :

dmetre@jeedom:~$ find /var/www/html/ -iname market.*.php
/var/www/html/core/repo/market.display.repo.php
/var/www/html/core/repo/market.send.repo.php
/var/www/html/core/repo/market.repo.php
/var/www/html/core/repo/market.list.repo.php

Si je fais la même commande sur une autre machine qui est aussi en bêta :
/var/www/html/jeedom/desktop/modal/market.comment.php
/var/www/html/jeedom/desktop/modal/market.list.php
/var/www/html/jeedom/desktop/modal/market.display.php
/var/www/html/jeedom/desktop/modal/market.send.php
/var/www/html/jeedom/desktop/modal/market.allChangelog.php
/var/www/html/jeedom/core/ajax/market.ajax.php
/var/www/html/jeedom/core/class/market.class.php
/var/www/html/jeedom/core/repo/market.send.repo.php
/var/www/html/jeedom/core/repo/market.display.repo.php
/var/www/html/jeedom/core/repo/market.repo.php
/var/www/html/jeedom/core/repo/market.list.repo.php

**Comment by Czara** [comment]
Bonjour, 

J'ai la même erreur en version 2.3.12.

J'ai regardé le correctif appliqué au fichier /var/www/html/plugins/widget/desktop/js/widget.js qui consiste à remplacer market par update : https://github.com/jeedom/plugin-widget/commit/a103d018324f8c78e240e75ed9f478d5fa8ad0b7 mais la modification est déjà effective.

Pourtant j'ai toujours le même message d'erreur.

Merci

Christophe

**Comment by zoic21** [comment]
Je viens de repousser une stable de jeedom avez vous toujours le soucis ?

**Comment by Czara** [comment]
Bonjour, 

J'ai maintenant accès au Market depuis la page Widget, mais en poussant les tests plus loin je me rends compte que c'est la même chose sur la page script. File not found : market.list.php

Merci

Christophe
