### ISSUE TITLE
[CORE][BETA]

### ISSUE THREAD

**Issue by philippeMo** [jeedom/issues#95]
version jeedom 2.5.0
- la fonction  "afficher le nom " dans "configuration commande" sur une commande de type info ne fonctionne pas .
- faute de frappe sur le "ET" qui devrait être en minuscule (voir screen ci-dessous)

![image](https://cloud.githubusercontent.com/assets/19261395/18617618/ec348b92-7dd3-11e6-9812-1b616b63c340.png)

**Comment by zoic21** [comment]
Bonjour,
- Pas de soucis chez moi est ce bien sur un widget core ?
- c'est volontaire

**Comment by philippeMo** [comment]
![image](https://cloud.githubusercontent.com/assets/19261395/18618208/40da3ce2-7de2-11e6-8c74-a947e0ddcd39.png)

oui , voilà le widget qui correspond sur lequel j'ai désactivé statistique et affichage du nom sur la commande info température
