### ISSUE TITLE
[CORE][BETA] Le trigger est vide si le scénario est déclenché par un scénario

### ISSUE THREAD

**Issue by Masterfion** [jeedom/issues#98]
Hello :)

Auparavant lorsqu'un scénario était déclenché par un autre scénario le trigger valait "Lancement provoqué par le scénario XXX".

Je testais le déclencheur ainsi :
SI trigger() matches "/Lancement provoqué par le scénario/" ...

Depuis quelques temps, si un scénario est déclenché par un autre scénario, le déclencheur est vide.

Normal ? Paranormal ?
Merciiiii

**Comment by zoic21** [comment]
Bonjour,
 C'est normal est voulu ça permet d'optimiser un peu le système.

**Comment by fwehrle** [comment]
Bonjour,
Je viens de découvrir cette dépréciation sur le forum. La plupart de mes scénarios fonctionnant comme ca, il va falloir que je revois intégralement mes 200 scénarios... Ok...
Je ne critique pas ce choix : si ca peut améliorer la vitesse d'execution, pas de problème.
Par contre, serait-il possible d'anticiper ce genre de décision, et d'indiquer les fonctions dépréciées dans la doc et surtout de communiquer sur le sujet AVANT le déploiement en stable. Par ex. sur le blog, ou dans la doc ("fonction dépréciée en v2.4.4")?
Parce qu'il n'y a rien de plus pénible que de le découvrir un matin quand les scénarios ne se sont pas lancés... 
Bref, un peu plus de communication ne ferait pas de mal...
Merci

**Comment by zoic21** [comment]
Bonjour,
Je suis désolé du problème que vous rencontrez celui-ci est entièrement ma faute tout comme le manque de communication qui est aussi de ma faute et je m'en excuse. J'aimerais vous dire que ça ne se reproduira plus mais ça serait faux j'essaye de faire du mieux que je peux mais malheureusement l'être humain a ses limites. Je ne peux que donc vous conseiller de vous tourner vers une autre solution si vous voulez éviter ces soucis de communication et désagréments.

**Comment by fwehrle** [comment]
Bonjour Loic,
Merci pour ce message. Tout le monde fait des erreurs, et c'est bien de le reconnaitre.
On veut bien faire, améliorer des points, et on oublie de communiquer dessus. 
Maintenant, en dehors de l'agacement (relatif) que je tenais à vous communiquer, mon intervention a surtout pour but d'essayer d'améliorer ce qui peut l'être. Je sais que vos problème de communication se reproduirons surement. Vous êtes une petite équipe, avec beaucoup de boulot (je suis dans le même cas). Mais si vous dites essayer de vous améliorer, ca me va. J'apporte des idées (prévenir avec un petit post de blog, un changelog des regressions voulues, maj de la doc, etc..). A vous de voir si elles sont applicables. :)
Mais rassurez-vous, je ne changerais pas de solution pour si peu... du moment que le message est passé et que vous en tenez compte (ce qui semble être le cas).
Merci a vous. Franck
