### ISSUE TITLE
[APP] Retour d'etat lumiere ne fonctionne pas sur le dashboard de l'app mobile

### ISSUE THREAD

**Issue by ouaibsky** [jeedom/issues#99]
J'utilise app mobile avec des objets définis par le plugin eibd avec principalement des lumières et retour d’état.
Sur les écrans par pièces cela fonctionne bien: Quand je click sur une icône ampoule pour allumer, elle change lorsque je reçois l’état de l'actionneur
Sur l’écran de dashboard/raccourcis, aucun état n'est affiche, selon ne sert donc a rien car il faut être dans le pièce pour voir si on a allumer ou éteindre (ou alors aller dans vue par pièce)

Possible doublon avec #84
Christophe

- la version de jeedom: 2.3.18
- plugin mobile: 2016-08-19 14:09:21
- plugin eibd: 2016-09-12 08:40:20

**Comment by rocket13011** [comment]
Clôture doublon sera présent dans la 1.1
